<template>
  <div class="art-full-height" v-loading="loading">
    <ElRow :gutter="16" class="mb-4">
      <ElCol v-for="item in cards" :key="item.label" :xs="12" :sm="6"><ElCard shadow="never" class="wallet-card"><div class="card-label">{{item.label}}</div><div class="card-value">¥ {{money(item.value)}}</div></ElCard></ElCol>
    </ElRow>
    <ElCard shadow="never" class="mb-4"><div class="member-row"><div><div class="member-title">{{wallet?.member?.level_name||'普通会员'}}</div><div class="member-desc">{{wallet?.member?.benefit_description||'充值后可获得会员成长与专属权益'}}</div></div><div class="member-extra"><span>累计充值 ¥ {{money(wallet?.member?.total_recharge_amount)}}</span><ElTag type="warning">会员折扣 {{percent(wallet?.member?.discount_rate||1)}}</ElTag></div></div></ElCard>
    <ElCard shadow="never" class="mb-4"><template #header><div class="section-header"><div><strong>充值套餐</strong><div class="hint">充值金额进入现金余额，赠送金额进入赠送余额</div></div></div></template><ElRow :gutter="14"><ElCol v-for="plan in plans" :key="plan.id" :xs="24" :sm="12" :lg="8"><div class="plan" :class="{selected:selectedPlan?.id===plan.id}" @click="selectedPlan=plan"><div class="plan-name">{{plan.planName}}</div><div class="plan-price">¥ {{money(plan.rechargeAmount)}}</div><div class="plan-bonus">赠送 ¥ {{money(plan.bonusAmount)}}</div><ElButton v-auth="'customer:wallet:recharge'" type="primary" class="!w-full mt-3" @click.stop="confirmRecharge(plan)">立即充值</ElButton></div></ElCol></ElRow><ElEmpty v-if="!plans.length" description="暂无可用充值套餐"/></ElCard>
    <ElCard shadow="never"><template #header><div class="section-header"><strong>资金流水</strong><ElSelect v-model="query.businessType" clearable placeholder="全部类型" class="!w-44" @change="search"><ElOption label="充值" value="RECHARGE"/><ElOption label="订单支付" value="ORDER_PAYMENT"/><ElOption label="订单退款" value="ORDER_REFUND"/></ElSelect></div></template><ElTable :data="transactions" empty-text="暂无资金流水"><ElTableColumn prop="transaction_no" label="流水号" min-width="220"/><ElTableColumn prop="business_type" label="业务类型" width="120"><template #default="{row}">{{businessText(row.business_type)}}</template></ElTableColumn><ElTableColumn prop="balance_type" label="余额类型" width="100"><template #default="{row}">{{row.balance_type==='CASH'?'现金余额':'赠送余额'}}</template></ElTableColumn><ElTableColumn prop="amount" label="变动金额" width="130"><template #default="{row}"><span :class="row.direction==='IN'?'income':'expense'">{{row.direction==='IN'?'+':'-'}} ¥ {{money(row.amount)}}</span></template></ElTableColumn><ElTableColumn prop="balance_after" label="变动后余额" width="130"><template #default="{row}">¥ {{money(row.balance_after)}}</template></ElTableColumn><ElTableColumn prop="remark" label="说明" min-width="150"/><ElTableColumn prop="created_at" label="时间" width="180"/></ElTable><div class="pagination"><ElPagination v-model:current-page="query.current" v-model:page-size="query.size" :total="total" layout="total, prev, pager, next" @change="loadTransactions"/></div></ElCard>
  </div>
</template>
<script setup lang="ts">
import{fetchCustomerWallet,fetchRechargePlans,fetchWalletTransactions,rechargeCustomerWallet}from'@/api/business-manage'
const loading=ref(false),wallet=ref<any>(),plans=ref<any[]>([]),selectedPlan=ref<any>(),transactions=ref<any[]>([]),total=ref(0),query=reactive({current:1,size:20,businessType:''});const cards=computed(()=>[{label:'总余额',value:wallet.value?.account?.totalBalance},{label:'现金余额',value:wallet.value?.account?.cashBalance},{label:'赠送余额',value:wallet.value?.account?.bonusBalance},{label:'冻结余额',value:wallet.value?.account?.frozenBalance}])
async function load(){loading.value=true;try{[wallet.value,plans.value]=await Promise.all([fetchCustomerWallet(),fetchRechargePlans()]);selectedPlan.value=plans.value[0];await loadTransactions()}finally{loading.value=false}}async function loadTransactions(){const d=await fetchWalletTransactions(query);transactions.value=d.records;total.value=d.total}function search(){query.current=1;loadTransactions()}
async function confirmRecharge(plan:any){await ElMessageBox.confirm(`确认模拟充值 ¥ ${money(plan.rechargeAmount)}，并获得赠送 ¥ ${money(plan.bonusAmount)} 吗？`,'确认充值',{type:'warning'});const requestNo=`web-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;const result=await rechargeCustomerWallet(plan.id,requestNo);ElMessage.success(`充值成功，到账 ¥ ${money(result.cashAmount)}，赠送 ¥ ${money(result.bonusAmount)}`);await load()}
const money=(v:any)=>Number(v||0).toFixed(2),percent=(v:any)=>`${(Number(v||0)*100).toFixed(0)}%`,businessText=(s:string)=>({RECHARGE:'充值',ORDER_PAYMENT:'订单支付',ORDER_REFUND:'订单退款'}[s]||s)
onMounted(load)
</script>
<style scoped>.wallet-card{min-height:108px}.card-label,.hint,.member-desc{color:var(--el-text-color-secondary);font-size:13px}.card-value{font-size:27px;font-weight:600;margin-top:15px}.member-row,.section-header{display:flex;align-items:center;justify-content:space-between}.member-title{font-size:18px;font-weight:600;margin-bottom:8px}.member-extra{display:flex;align-items:center;gap:16px;color:var(--el-text-color-regular)}.plan{padding:18px;border:1px solid var(--el-border-color);border-radius:10px;cursor:pointer;transition:.2s;margin-bottom:14px}.plan:hover,.plan.selected{border-color:var(--el-color-primary);box-shadow:0 5px 18px rgb(64 158 255 / 10%)}.plan-name{font-weight:600}.plan-price{font-size:27px;font-weight:700;color:var(--el-color-primary);margin:12px 0 4px}.plan-bonus{color:var(--el-color-success);font-size:13px}.pagination{display:flex;justify-content:flex-end;margin-top:18px}.income{color:var(--el-color-success);font-weight:600}.expense{color:var(--el-color-danger);font-weight:600}</style>
