package com.peiwan.platform.fulfillment;
import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController public class FulfillmentController{private final FulfillmentService service;private final AuditService audit;public FulfillmentController(FulfillmentService s,AuditService a){service=s;audit=a;}
 @PreAuthorize("hasAuthority('player:order:start')") @PutMapping("/api/player/orders/{id}/start") public ApiResponse<?> start(Authentication a,@PathVariable long id,HttpServletRequest r){service.start(uid(a),id);audit.operation(a,"player:order:start","ORDER",id,"开始服务",r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('player:order:submit')") @PutMapping("/api/player/orders/{id}/submit") public ApiResponse<?> submit(Authentication a,@PathVariable long id,@RequestBody FulfillmentService.Submit b,HttpServletRequest r){service.submit(uid(a),id,b);audit.operation(a,"player:order:submit","ORDER",id,"提交完成凭证",r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:fulfillment:list') or hasRole('admin')") @GetMapping("/api/business/fulfillment/list") public ApiResponse<?> list(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String status){return ApiResponse.ok(service.list(current,size,status));}
 @PreAuthorize("hasAuthority('business:fulfillment:detail') or hasRole('admin')") @GetMapping("/api/business/fulfillment/{id}") public ApiResponse<?> detail(@PathVariable long id){return ApiResponse.ok(service.detail(id));}
 @PreAuthorize("hasAuthority('business:fulfillment:review') or hasRole('admin')") @PutMapping("/api/business/fulfillment/{id}/review") public ApiResponse<?> review(Authentication a,@PathVariable long id,@RequestBody Review b,HttpServletRequest r){service.review(id,b.action(),b.remark(),uid(a));audit.operation(a,"business:fulfillment:review","FULFILLMENT",id,b.action()+":"+b.remark(),r);return ApiResponse.ok();}
 private long uid(Authentication a){return(Long)a.getPrincipal();}public record Review(String action,String remark){}
}
