package com.peiwan.platform.fulfillment;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service public class FulfillmentService{
 private final FulfillmentMapper fulfillments;private final FulfillmentProofMapper proofs;private final FulfillmentAuditMapper audits;private final FulfillmentDataMapper data;private final PlayerMapper players;private final OrderMapper orders;private final OrderStatusLogMapper orderLogs;
 public FulfillmentService(FulfillmentMapper fulfillments,FulfillmentProofMapper proofs,FulfillmentAuditMapper audits,FulfillmentDataMapper data,PlayerMapper players,OrderMapper orders,OrderStatusLogMapper orderLogs){this.fulfillments=fulfillments;this.proofs=proofs;this.audits=audits;this.data=data;this.players=players;this.orders=orders;this.orderLogs=orderLogs;}
 @Transactional public void start(long userId,long orderId){var p=player(userId);var o=ownOrder(orderId,p.id);if(!"ASSIGNED".equals(o.orderStatus))throw new IllegalArgumentException("只有已接单订单可以开始服务");o.orderStatus="IN_SERVICE";o.serviceStartedAt=LocalDateTime.now();o.updatedAt=LocalDateTime.now();orders.updateById(o);var f=new FulfillmentEntity();f.orderId=orderId;f.playerId=p.id;f.fulfillmentStatus="IN_SERVICE";fulfillments.insert(f);logOrder(orderId,"ASSIGNED","IN_SERVICE",userId,"陪玩师开始服务");}
 @Transactional public void submit(long userId,long orderId,Submit c){var p=player(userId);var o=ownOrder(orderId,p.id);if(!"IN_SERVICE".equals(o.orderStatus))throw new IllegalArgumentException("只有服务中订单可以提交完成凭证");if(c.completionNote()==null||c.completionNote().isBlank())throw new IllegalArgumentException("请填写完成说明");if(c.proofUrls()==null||c.proofUrls().isEmpty())throw new IllegalArgumentException("请至少上传一项完成凭证");if(c.proofUrls().size()>9)throw new IllegalArgumentException("完成凭证最多9项");var f=fulfillments.selectOne(new QueryWrapper<FulfillmentEntity>().eq("order_id",orderId));if(f==null)throw new IllegalArgumentException("履约记录不存在");fulfillments.update(null,new UpdateWrapper<FulfillmentEntity>().eq("id",f.id).set("fulfillment_status","PENDING_REVIEW").set("completion_note",c.completionNote()).set("actual_quantity",c.actualQuantity()).set("submitted_at",LocalDateTime.now()).set("review_remark",null).set("updated_at",LocalDateTime.now()));proofs.delete(new QueryWrapper<FulfillmentProofEntity>().eq("fulfillment_id",f.id));int i=0;for(String url:c.proofUrls())if(url!=null&&!url.isBlank()){var proof=new FulfillmentProofEntity();proof.fulfillmentId=f.id;proof.proofType="MEDIA";proof.proofUrl=url;proof.sortNo=i++;proofs.insert(proof);}o.orderStatus="PENDING_CONFIRM";o.completionSubmittedAt=LocalDateTime.now();o.updatedAt=LocalDateTime.now();orders.updateById(o);logOrder(orderId,"IN_SERVICE","PENDING_CONFIRM",userId,"陪玩师提交完成凭证");audit(f.id,"SUBMIT","IN_SERVICE","PENDING_REVIEW","提交完成凭证",userId);}
 public Map<String,Object> list(int current,int size,String status){current=Math.max(1,current);size=Math.min(100,Math.max(1,size));var result=data.fulfillments(new Page<>(current,size),status);return Map.of("records",result.getRecords().stream().map(this::view).toList(),"current",current,"size",size,"total",result.getTotal());}
 public Map<String,Object> detail(long id){var row=data.detail(id);if(row==null)throw new IllegalArgumentException("履约记录不存在");var x=new LinkedHashMap<>(view(row));x.put("proofUrls",data.proofUrls(id));x.put("audits",data.audits(id));return x;}
 @Transactional public void review(long id,String action,String remark,long operator){var f=fulfillments.selectById(id);if(f==null)throw new IllegalArgumentException("履约记录不存在");if(!"PENDING_REVIEW".equals(f.fulfillmentStatus))throw new IllegalArgumentException("只有待审核记录可以处理");var o=orders.selectById(f.orderId);if(o==null)throw new IllegalArgumentException("订单不存在");if("REJECT".equals(action)){if(remark==null||remark.isBlank())throw new IllegalArgumentException("驳回必须填写原因");reviewFields(f,"REJECTED",remark,operator);o.orderStatus="IN_SERVICE";o.updatedAt=LocalDateTime.now();orders.updateById(o);logOrder(o.id,"PENDING_CONFIRM","IN_SERVICE",operator,"完成凭证驳回："+remark);audit(id,"REJECT","PENDING_REVIEW","REJECTED",remark,operator);return;}if(!"APPROVE".equals(action))throw new IllegalArgumentException("审核动作无效");Integer hours=data.confirmHours();if(hours==null)throw new IllegalArgumentException("未配置订单确认规则");reviewFields(f,"WAIT_CUSTOMER_CONFIRM",remark,operator);o.orderStatus="WAIT_CUSTOMER_CONFIRM";o.customerConfirmDeadline=LocalDateTime.now().plusHours(hours);o.updatedAt=LocalDateTime.now();orders.updateById(o);logOrder(o.id,"PENDING_CONFIRM","WAIT_CUSTOMER_CONFIRM",operator,"完成凭证审核通过，等待用户确认");audit(id,"APPROVE","PENDING_REVIEW","WAIT_CUSTOMER_CONFIRM",remark,operator);}
 private void reviewFields(FulfillmentEntity f,String status,String remark,long operator){f.fulfillmentStatus=status;f.reviewedBy=operator;f.reviewedAt=LocalDateTime.now();f.reviewRemark=remark;f.updatedAt=LocalDateTime.now();fulfillments.updateById(f);}
 private PlayerEntity player(long uid){var p=players.selectOne(new QueryWrapper<PlayerEntity>().eq("user_id",uid).eq("enabled",true).eq("audit_status","APPROVED"));if(p==null)throw new IllegalArgumentException("当前账号未绑定可用的陪玩师资料");return p;}private OrderEntity ownOrder(long oid,long pid){var o=orders.selectOne(new QueryWrapper<OrderEntity>().eq("id",oid).eq("assigned_player_id",pid));if(o==null)throw new IllegalArgumentException("订单不存在或不属于当前陪玩师");return o;}
 private void logOrder(long o,String from,String to,long op,String reason){var l=new OrderStatusLogEntity();l.orderId=o;l.fromStatus=from;l.toStatus=to;l.operatorId=op;l.reason=reason;orderLogs.insert(l);}private void audit(long f,String action,String from,String to,String remark,long op){var a=new FulfillmentAuditEntity();a.fulfillmentId=f;a.action=action;a.beforeStatus=from;a.afterStatus=to;a.remark=remark;a.operatorId=op;audits.insert(a);}
 private Map<String,Object> view(Map<String,Object>r){var x=new LinkedHashMap<String,Object>();String[][]k={{"id","id"},{"orderId","order_id"},{"orderNo","order_no"},{"orderStatus","order_status"},{"playerId","player_id"},{"playerName","player_name"},{"playerNo","player_no"},{"productName","product_name"},{"fulfillmentStatus","fulfillment_status"},{"completionNote","completion_note"},{"actualQuantity","actual_quantity"},{"submittedAt","submitted_at"},{"reviewRemark","review_remark"},{"reviewedAt","reviewed_at"}};for(var a:k)if(r.containsKey(a[1]))x.put(a[0],r.get(a[1]));return x;}public record Submit(String completionNote,java.math.BigDecimal actualQuantity,List<String>proofUrls){}
}
