-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '4ad538e929e4cc55' HASH '64a073ace7380051d72b5b847b24a9b20f78b1ea624ef2917a8545dbeb4c3bfc' ADMIN;         
CREATE CACHED TABLE "public"."flyway_schema_history"(
    "installed_rank" INTEGER NOT NULL,
    "version" CHARACTER VARYING(50),
    "description" CHARACTER VARYING(200) NOT NULL,
    "type" CHARACTER VARYING(20) NOT NULL,
    "script" CHARACTER VARYING(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" CHARACTER VARYING(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
);               
ALTER TABLE "public"."flyway_schema_history" ADD CONSTRAINT "public"."flyway_schema_history_pk" PRIMARY KEY("installed_rank");
-- 51 +/- SELECT COUNT(*) FROM public.flyway_schema_history;  
CREATE INDEX "public"."flyway_schema_history_s_idx" ON "public"."flyway_schema_history"("success" NULLS LAST);
CREATE CACHED TABLE "public"."sys_user"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 97) DEFAULT ON NULL NOT NULL,
    "username" CHARACTER VARYING(64) NOT NULL,
    "password" CHARACTER VARYING(100) NOT NULL,
    "nickname" CHARACTER VARYING(64) NOT NULL,
    "email" CHARACTER VARYING(128),
    "phone" CHARACTER VARYING(32),
    "gender" CHARACTER VARYING(16),
    "avatar" CHARACTER VARYING(512),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);      
ALTER TABLE "public"."sys_user" ADD CONSTRAINT "public"."CONSTRAINT_7" PRIMARY KEY("id");     
-- 8 +/- SELECT COUNT(*) FROM public.sys_user;
CREATE CACHED TABLE "public"."sys_menu"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 260) DEFAULT ON NULL NOT NULL,
    "parent_id" BIGINT,
    "type" CHARACTER VARYING(16) NOT NULL,
    "name" CHARACTER VARYING(64) NOT NULL,
    "path" CHARACTER VARYING(255),
    "component" CHARACTER VARYING(255),
    "title" CHARACTER VARYING(64) NOT NULL,
    "icon" CHARACTER VARYING(128),
    "auth_mark" CHARACTER VARYING(128),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "hidden" BOOLEAN DEFAULT FALSE NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "keep_alive" BOOLEAN DEFAULT FALSE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);       
ALTER TABLE "public"."sys_menu" ADD CONSTRAINT "public"."CONSTRAINT_74A4" PRIMARY KEY("id");  
-- 142 +/- SELECT COUNT(*) FROM public.sys_menu;              
CREATE INDEX "public"."ix_sys_menu_parent" ON "public"."sys_menu"("parent_id" NULLS LAST);    
CREATE UNIQUE NULLS DISTINCT INDEX "public"."ux_sys_menu_auth_mark" ON "public"."sys_menu"("auth_mark" NULLS LAST);           
CREATE CACHED TABLE "public"."sys_login_log"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 1590) DEFAULT ON NULL NOT NULL,
    "username" CHARACTER VARYING(64),
    "success" BOOLEAN NOT NULL,
    "ip_address" CHARACTER VARYING(64),
    "user_agent" CHARACTER VARYING(512),
    "message" CHARACTER VARYING(255),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "public"."sys_login_log" ADD CONSTRAINT "public"."CONSTRAINT_E" PRIMARY KEY("id");
-- 172 +/- SELECT COUNT(*) FROM public.sys_login_log;         
CREATE CACHED TABLE "public"."sys_user_role"(
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL
);              
ALTER TABLE "public"."sys_user_role" ADD CONSTRAINT "public"."CONSTRAINT_6" PRIMARY KEY("user_id", "role_id");
-- 14 +/- SELECT COUNT(*) FROM public.sys_user_role;          
CREATE INDEX "public"."ix_sys_user_role_role" ON "public"."sys_user_role"("role_id" NULLS LAST);              
CREATE CACHED TABLE "public"."sys_role_menu"(
    "role_id" BIGINT NOT NULL,
    "menu_id" BIGINT NOT NULL
);              
ALTER TABLE "public"."sys_role_menu" ADD CONSTRAINT "public"."CONSTRAINT_65" PRIMARY KEY("role_id", "menu_id");               
-- 168 +/- SELECT COUNT(*) FROM public.sys_role_menu;         
CREATE INDEX "public"."ix_sys_role_menu_menu" ON "public"."sys_role_menu"("menu_id" NULLS LAST);              
CREATE CACHED TABLE "public"."sys_role"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "name" CHARACTER VARYING(64) NOT NULL,
    "code" CHARACTER VARYING(64) NOT NULL,
    "description" CHARACTER VARYING(255),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "built_in" BOOLEAN DEFAULT FALSE NOT NULL
);        
ALTER TABLE "public"."sys_role" ADD CONSTRAINT "public"."CONSTRAINT_74A" PRIMARY KEY("id");   
-- 3 +/- SELECT COUNT(*) FROM public.sys_role;
CREATE CACHED TABLE "public"."sys_operation_log"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 444) DEFAULT ON NULL NOT NULL,
    "operator_id" BIGINT,
    "operation" CHARACTER VARYING(128) NOT NULL,
    "target_type" CHARACTER VARYING(64) NOT NULL,
    "target_id" CHARACTER VARYING(64),
    "detail" CHARACTER VARYING(1000),
    "ip_address" CHARACTER VARYING(64),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);       
ALTER TABLE "public"."sys_operation_log" ADD CONSTRAINT "public"."CONSTRAINT_E9" PRIMARY KEY("id");           
-- 88 +/- SELECT COUNT(*) FROM public.sys_operation_log;      
CREATE CACHED TABLE "public"."pw_game"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 65) DEFAULT ON NULL NOT NULL,
    "game_code" CHARACTER VARYING(64) NOT NULL,
    "game_name" CHARACTER VARYING(64) NOT NULL,
    "icon_url" CHARACTER VARYING(512),
    "cover_url" CHARACTER VARYING(512),
    "platform_type" CHARACTER VARYING(16) NOT NULL,
    "description" CHARACTER VARYING(500),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);              
ALTER TABLE "public"."pw_game" ADD CONSTRAINT "public"."CONSTRAINT_F" PRIMARY KEY("id");      
-- 2 +/- SELECT COUNT(*) FROM public.pw_game; 
CREATE CACHED TABLE "public"."pw_game_position"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "game_id" BIGINT NOT NULL,
    "position_code" CHARACTER VARYING(64) NOT NULL,
    "position_name" CHARACTER VARYING(64) NOT NULL,
    "icon_url" CHARACTER VARYING(512),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);      
ALTER TABLE "public"."pw_game_position" ADD CONSTRAINT "public"."CONSTRAINT_1" PRIMARY KEY("id");             
-- 12 +/- SELECT COUNT(*) FROM public.pw_game_position;       
CREATE CACHED TABLE "public"."pw_order_item"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 101) DEFAULT ON NULL NOT NULL,
    "order_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    "sku_id" BIGINT NOT NULL,
    "product_code" CHARACTER VARYING(64) NOT NULL,
    "product_name" CHARACTER VARYING(128) NOT NULL,
    "sku_code" CHARACTER VARYING(64) NOT NULL,
    "sku_name" CHARACTER VARYING(128) NOT NULL,
    "product_type" CHARACTER VARYING(32) NOT NULL,
    "unit_price" DECIMAL(12, 2) NOT NULL,
    "quantity" INTEGER NOT NULL,
    "subtotal_amount" DECIMAL(12, 2) NOT NULL,
    "service_snapshot" CHARACTER LARGE OBJECT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "pricing_rule_id" BIGINT
);      
ALTER TABLE "public"."pw_order_item" ADD CONSTRAINT "public"."CONSTRAINT_5" PRIMARY KEY("id");
-- 18 +/- SELECT COUNT(*) FROM public.pw_order_item;          
CREATE INDEX "public"."ix_pw_order_item_order" ON "public"."pw_order_item"("order_id" NULLS LAST);            
CREATE CACHED TABLE "public"."pw_player_level"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 65) DEFAULT ON NULL NOT NULL,
    "game_id" BIGINT NOT NULL,
    "level_code" CHARACTER VARYING(32) NOT NULL,
    "level_name" CHARACTER VARYING(64) NOT NULL,
    "description" CHARACTER VARYING(255),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);          
ALTER TABLE "public"."pw_player_level" ADD CONSTRAINT "public"."CONSTRAINT_D5B1C" PRIMARY KEY("id");          
-- 7 +/- SELECT COUNT(*) FROM public.pw_player_level;         
CREATE INDEX "public"."ix_pw_player_level_game" ON "public"."pw_player_level"("game_id" NULLS LAST);          
CREATE CACHED TABLE "public"."pw_product"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 1042) DEFAULT ON NULL NOT NULL,
    "game_id" BIGINT NOT NULL,
    "category_id" BIGINT NOT NULL,
    "product_code" CHARACTER VARYING(64) NOT NULL,
    "product_name" CHARACTER VARYING(128) NOT NULL,
    "subtitle" CHARACTER VARYING(255),
    "description" CHARACTER VARYING(2000),
    "cover_url" CHARACTER VARYING(512),
    "product_type" CHARACTER VARYING(32) DEFAULT 'SERVICE' NOT NULL,
    "status" CHARACTER VARYING(32) DEFAULT 'DRAFT' NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "validity_days" INTEGER,
    "purchase_limit" INTEGER,
    "pricing_mode" CHARACTER VARYING(32) DEFAULT 'FIXED_SKU' NOT NULL
);       
ALTER TABLE "public"."pw_product" ADD CONSTRAINT "public"."CONSTRAINT_4" PRIMARY KEY("id");   
-- 17 +/- SELECT COUNT(*) FROM public.pw_product;             
CREATE INDEX "public"."ix_pw_product_game" ON "public"."pw_product"("game_id" NULLS LAST);    
CREATE INDEX "public"."ix_pw_product_category" ON "public"."pw_product"("category_id" NULLS LAST);            
CREATE CACHED TABLE "public"."pw_player_game_position"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 65) DEFAULT ON NULL NOT NULL,
    "player_game_id" BIGINT NOT NULL,
    "position_id" BIGINT NOT NULL,
    "skill_level" CHARACTER VARYING(32),
    "is_primary" BOOLEAN DEFAULT FALSE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);   
ALTER TABLE "public"."pw_player_game_position" ADD CONSTRAINT "public"."CONSTRAINT_D" PRIMARY KEY("id");      
-- 6 +/- SELECT COUNT(*) FROM public.pw_player_game_position; 
CREATE CACHED TABLE "public"."pw_player_tag"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "tag_code" CHARACTER VARYING(64) NOT NULL,
    "tag_name" CHARACTER VARYING(64) NOT NULL,
    "tag_color" CHARACTER VARYING(32),
    "tag_group" CHARACTER VARYING(16) DEFAULT 'OTHER' NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);  
ALTER TABLE "public"."pw_player_tag" ADD CONSTRAINT "public"."CONSTRAINT_AA" PRIMARY KEY("id");               
-- 5 +/- SELECT COUNT(*) FROM public.pw_player_tag;           
CREATE CACHED TABLE "public"."pw_player_tag_rel"(
    "player_id" BIGINT NOT NULL,
    "tag_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);         
ALTER TABLE "public"."pw_player_tag_rel" ADD CONSTRAINT "public"."CONSTRAINT_C" PRIMARY KEY("player_id", "tag_id");           
-- 10 +/- SELECT COUNT(*) FROM public.pw_player_tag_rel;      
CREATE CACHED TABLE "public"."pw_player_media"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "player_id" BIGINT NOT NULL,
    "media_type" CHARACTER VARYING(32) NOT NULL,
    "media_url" CHARACTER VARYING(512) NOT NULL,
    "thumbnail_url" CHARACTER VARYING(512),
    "title" CHARACTER VARYING(128),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "audit_status" CHARACTER VARYING(16) DEFAULT 'PENDING' NOT NULL,
    "audit_remark" CHARACTER VARYING(500),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);               
ALTER TABLE "public"."pw_player_media" ADD CONSTRAINT "public"."CONSTRAINT_D5" PRIMARY KEY("id");             
-- 0 +/- SELECT COUNT(*) FROM public.pw_player_media;         
CREATE INDEX "public"."ix_pw_player_media_player" ON "public"."pw_player_media"("player_id" NULLS LAST);      
CREATE CACHED TABLE "public"."pw_player_audit"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 65) DEFAULT ON NULL NOT NULL,
    "player_id" BIGINT NOT NULL,
    "audit_type" CHARACTER VARYING(16) NOT NULL,
    "before_status" CHARACTER VARYING(16),
    "after_status" CHARACTER VARYING(16) NOT NULL,
    "result" CHARACTER VARYING(16) NOT NULL,
    "reason" CHARACTER VARYING(500),
    "snapshot_data" CHARACTER VARYING(4000),
    "auditor_id" BIGINT,
    "audited_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);     
ALTER TABLE "public"."pw_player_audit" ADD CONSTRAINT "public"."CONSTRAINT_D51" PRIMARY KEY("id");            
-- 2 +/- SELECT COUNT(*) FROM public.pw_player_audit;         
CREATE INDEX "public"."ix_pw_player_audit_player" ON "public"."pw_player_audit"("player_id" NULLS LAST);      
CREATE CACHED TABLE "public"."pw_player_status_log"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "player_id" BIGINT NOT NULL,
    "status_type" CHARACTER VARYING(32) NOT NULL,
    "before_value" CHARACTER VARYING(32),
    "after_value" CHARACTER VARYING(32) NOT NULL,
    "reason" CHARACTER VARYING(500),
    "operator_type" CHARACTER VARYING(16) NOT NULL,
    "operator_id" BIGINT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);    
ALTER TABLE "public"."pw_player_status_log" ADD CONSTRAINT "public"."CONSTRAINT_FB" PRIMARY KEY("id");        
-- 5 +/- SELECT COUNT(*) FROM public.pw_player_status_log;    
CREATE INDEX "public"."ix_pw_player_status_log_player" ON "public"."pw_player_status_log"("player_id" NULLS LAST);            
CREATE CACHED TABLE "public"."pw_product_category"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 34) DEFAULT ON NULL NOT NULL,
    "game_id" BIGINT,
    "parent_id" BIGINT,
    "category_code" CHARACTER VARYING(64) NOT NULL,
    "category_name" CHARACTER VARYING(64) NOT NULL,
    "icon_url" CHARACTER VARYING(512),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);   
ALTER TABLE "public"."pw_product_category" ADD CONSTRAINT "public"."CONSTRAINT_E99" PRIMARY KEY("id");        
-- 8 +/- SELECT COUNT(*) FROM public.pw_product_category;     
CREATE INDEX "public"."ix_pw_product_category_parent" ON "public"."pw_product_category"("parent_id" NULLS LAST);              
CREATE INDEX "public"."ix_pw_product_category_game" ON "public"."pw_product_category"("game_id" NULLS LAST);  
CREATE CACHED TABLE "public"."pw_sku_commitment"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "sku_id" BIGINT NOT NULL,
    "rule_type" CHARACTER VARYING(32) NOT NULL,
    "title" CHARACTER VARYING(128) NOT NULL,
    "target_value" DECIMAL(18, 2),
    "target_unit" CHARACTER VARYING(32),
    "description" CHARACTER VARYING(1000),
    "failure_action" CHARACTER VARYING(500),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 
ALTER TABLE "public"."pw_sku_commitment" ADD CONSTRAINT "public"."CONSTRAINT_A6" PRIMARY KEY("id");           
-- 0 +/- SELECT COUNT(*) FROM public.pw_sku_commitment;       
CREATE INDEX "public"."ix_pw_sku_commitment_sku" ON "public"."pw_sku_commitment"("sku_id" NULLS LAST);        
CREATE CACHED TABLE "public"."pw_order_commitment"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "order_id" BIGINT NOT NULL,
    "order_item_id" BIGINT NOT NULL,
    "source_commitment_id" BIGINT,
    "rule_type" CHARACTER VARYING(32) NOT NULL,
    "title" CHARACTER VARYING(128) NOT NULL,
    "target_value" DECIMAL(18, 2),
    "target_unit" CHARACTER VARYING(32),
    "description" CHARACTER VARYING(1000),
    "failure_action" CHARACTER VARYING(500),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 
ALTER TABLE "public"."pw_order_commitment" ADD CONSTRAINT "public"."CONSTRAINT_5A6" PRIMARY KEY("id");        
-- 0 +/- SELECT COUNT(*) FROM public.pw_order_commitment;     
CREATE INDEX "public"."ix_pw_order_commitment_order" ON "public"."pw_order_commitment"("order_id" NULLS LAST);
CREATE INDEX "public"."ix_pw_order_commitment_item" ON "public"."pw_order_commitment"("order_item_id" NULLS LAST);            
CREATE CACHED TABLE "public"."pw_game_server"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "game_id" BIGINT NOT NULL,
    "server_code" CHARACTER VARYING(64) NOT NULL,
    "server_name" CHARACTER VARYING(64) NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);    
ALTER TABLE "public"."pw_game_server" ADD CONSTRAINT "public"."CONSTRAINT_8B2" PRIMARY KEY("id");             
-- 2 +/- SELECT COUNT(*) FROM public.pw_game_server;          
CREATE INDEX "public"."ix_pw_game_server_game" ON "public"."pw_game_server"("game_id" NULLS LAST);            
CREATE CACHED TABLE "public"."pw_product_sku"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 1046) DEFAULT ON NULL NOT NULL,
    "product_id" BIGINT NOT NULL,
    "sku_code" CHARACTER VARYING(64) NOT NULL,
    "sku_name" CHARACTER VARYING(128) NOT NULL,
    "price" DECIMAL(12, 2) NOT NULL,
    "unit_type" CHARACTER VARYING(32) NOT NULL,
    "unit_count" DECIMAL(10, 2) DEFAULT 1 NOT NULL,
    "min_quantity" INTEGER DEFAULT 1 NOT NULL,
    "max_quantity" INTEGER,
    "stock_mode" CHARACTER VARYING(16) DEFAULT 'UNLIMITED' NOT NULL,
    "stock_quantity" INTEGER,
    "service_minutes" INTEGER,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "market_price" DECIMAL(12, 2),
    "player_count" INTEGER DEFAULT 1 NOT NULL,
    "price_type" CHARACTER VARYING(20) DEFAULT 'PER_PLAYER' NOT NULL
);           
ALTER TABLE "public"."pw_product_sku" ADD CONSTRAINT "public"."CONSTRAINT_31" PRIMARY KEY("id");              
-- 26 +/- SELECT COUNT(*) FROM public.pw_product_sku;         
CREATE INDEX "public"."ix_pw_product_sku_product" ON "public"."pw_product_sku"("product_id" NULLS LAST);      
CREATE CACHED TABLE "public"."pw_fulfillment"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 67) DEFAULT ON NULL NOT NULL,
    "order_id" BIGINT NOT NULL,
    "order_member_id" BIGINT NOT NULL,
    "player_id" BIGINT NOT NULL,
    "fulfillment_status" CHARACTER VARYING(24) DEFAULT 'IN_SERVICE' NOT NULL,
    "completion_note" CHARACTER VARYING(1000),
    "actual_quantity" DECIMAL(10, 2),
    "submitted_at" TIMESTAMP,
    "reviewed_by" BIGINT,
    "reviewed_at" TIMESTAMP,
    "review_remark" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);             
ALTER TABLE "public"."pw_fulfillment" ADD CONSTRAINT "public"."CONSTRAINT_75" PRIMARY KEY("id");              
-- 11 +/- SELECT COUNT(*) FROM public.pw_fulfillment;         
CREATE INDEX "public"."ix_pw_fulfillment_order" ON "public"."pw_fulfillment"("order_id" NULLS LAST, "fulfillment_status" NULLS LAST);         
CREATE INDEX "public"."ix_pw_fulfillment_player" ON "public"."pw_fulfillment"("player_id" NULLS LAST, "fulfillment_status" NULLS LAST);       
CREATE CACHED TABLE "public"."pw_service_exception_request"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "request_no" CHARACTER VARYING(48) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "request_type" CHARACTER VARYING(16) NOT NULL,
    "source_order_member_id" BIGINT,
    "target_player_id" BIGINT,
    "applicant_type" CHARACTER VARYING(16) NOT NULL,
    "applicant_user_id" BIGINT NOT NULL,
    "reason" CHARACTER VARYING(1000) NOT NULL,
    "proof_urls" CHARACTER LARGE OBJECT,
    "request_status" CHARACTER VARYING(32) NOT NULL,
    "review_remark" CHARACTER VARYING(1000),
    "reviewed_by" BIGINT,
    "reviewed_at" TIMESTAMP,
    "replacement_order_member_id" BIGINT,
    "resolved_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);        
ALTER TABLE "public"."pw_service_exception_request" ADD CONSTRAINT "public"."CONSTRAINT_20" PRIMARY KEY("id");
-- 1 +/- SELECT COUNT(*) FROM public.pw_service_exception_request;            
CREATE INDEX "public"."ix_pw_service_exception_order" ON "public"."pw_service_exception_request"("order_id" NULLS LAST, "request_status" NULLS LAST, "id" NULLS LAST);        
CREATE INDEX "public"."ix_pw_service_exception_target" ON "public"."pw_service_exception_request"("target_player_id" NULLS LAST, "request_status" NULLS LAST, "id" NULLS LAST);               
CREATE CACHED TABLE "public"."pw_product_service"(
    "product_id" BIGINT NOT NULL,
    "service_id" BIGINT NOT NULL,
    "service_quantity" DECIMAL(10, 2) DEFAULT 1 NOT NULL,
    "unit_type" CHARACTER VARYING(32) DEFAULT 'ORDER' NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL
);            
ALTER TABLE "public"."pw_product_service" ADD CONSTRAINT "public"."CONSTRAINT_3" PRIMARY KEY("product_id", "service_id");     
-- 24 +/- SELECT COUNT(*) FROM public.pw_product_service;     
CREATE INDEX "public"."ix_pw_product_service_service" ON "public"."pw_product_service"("service_id" NULLS LAST);              
CREATE CACHED TABLE "public"."pw_fulfillment_proof"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) DEFAULT ON NULL NOT NULL,
    "fulfillment_id" BIGINT NOT NULL,
    "proof_type" CHARACTER VARYING(16) NOT NULL,
    "proof_url" CHARACTER VARYING(512) NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);        
ALTER TABLE "public"."pw_fulfillment_proof" ADD CONSTRAINT "public"."CONSTRAINT_AE" PRIMARY KEY("id");        
-- 1 +/- SELECT COUNT(*) FROM public.pw_fulfillment_proof;    
CREATE CACHED TABLE "public"."pw_sku_level_price"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 65) DEFAULT ON NULL NOT NULL,
    "sku_id" BIGINT NOT NULL,
    "player_level_id" BIGINT NOT NULL,
    "price" DECIMAL(12, 2) NOT NULL,
    "market_price" DECIMAL(12, 2),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "public"."pw_sku_level_price" ADD CONSTRAINT "public"."CONSTRAINT_5470" PRIMARY KEY("id");        
-- 54 +/- SELECT COUNT(*) FROM public.pw_sku_level_price;     
CREATE INDEX "public"."ix_pw_sku_level_price_sku" ON "public"."pw_sku_level_price"("sku_id" NULLS LAST);      
CREATE INDEX "public"."ix_pw_sku_level_price_level" ON "public"."pw_sku_level_price"("player_level_id" NULLS LAST);           
CREATE CACHED TABLE "public"."pw_order_game_profile"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 101) DEFAULT ON NULL NOT NULL,
    "order_id" BIGINT NOT NULL,
    "game_id" BIGINT NOT NULL,
    "game_name" CHARACTER VARYING(64) NOT NULL,
    "game_account" CHARACTER VARYING(128),
    "game_nickname" CHARACTER VARYING(128),
    "server_name" CHARACTER VARYING(128),
    "rank_name" CHARACTER VARYING(128),
    "extra_requirement" CHARACTER VARYING(1000),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "customer_game_profile_id" BIGINT,
    "server_id" BIGINT,
    "current_rank_id" BIGINT,
    "target_rank_id" BIGINT,
    "current_rank_name" CHARACTER VARYING(128),
    "target_rank_name" CHARACTER VARYING(128)
);           
ALTER TABLE "public"."pw_order_game_profile" ADD CONSTRAINT "public"."CONSTRAINT_CF" PRIMARY KEY("id");       
-- 18 +/- SELECT COUNT(*) FROM public.pw_order_game_profile;  
CREATE INDEX "public"."ix_pw_order_profile_order" ON "public"."pw_order_game_profile"("order_id" NULLS LAST); 
CREATE CACHED TABLE "public"."pw_order_status_log"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 178) DEFAULT ON NULL NOT NULL,
    "order_id" BIGINT NOT NULL,
    "from_status" CHARACTER VARYING(32),
    "to_status" CHARACTER VARYING(32) NOT NULL,
    "operator_id" BIGINT,
    "reason" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "public"."pw_order_status_log" ADD CONSTRAINT "public"."CONSTRAINT_2" PRIMARY KEY("id");          
-- 25 +/- SELECT COUNT(*) FROM public.pw_order_status_log;    
CREATE INDEX "public"."ix_pw_order_status_log_order" ON "public"."pw_order_status_log"("order_id" NULLS LAST);
CREATE CACHED TABLE "public"."pw_dispatch_rule"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "rule_name" CHARACTER VARYING(64) NOT NULL,
    "grab_minutes" INTEGER DEFAULT 10 NOT NULL,
    "max_candidates" INTEGER DEFAULT 10 NOT NULL,
    "allow_busy" BOOLEAN DEFAULT FALSE NOT NULL,
    "max_active_orders" INTEGER DEFAULT 1 NOT NULL,
    "allow_reoffer_after_reject" BOOLEAN DEFAULT FALSE NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);     
ALTER TABLE "public"."pw_dispatch_rule" ADD CONSTRAINT "public"."CONSTRAINT_C7" PRIMARY KEY("id");            
-- 1 +/- SELECT COUNT(*) FROM public.pw_dispatch_rule;        
CREATE CACHED TABLE "public"."pw_dispatch_task"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 163) DEFAULT ON NULL NOT NULL,
    "task_no" CHARACTER VARYING(40) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "dispatch_mode" CHARACTER VARYING(16) NOT NULL,
    "task_status" CHARACTER VARYING(24) NOT NULL,
    "target_player_id" BIGINT,
    "accepted_player_id" BIGINT,
    "attempt_no" INTEGER DEFAULT 1 NOT NULL,
    "candidate_count" INTEGER DEFAULT 0 NOT NULL,
    "deadline_at" TIMESTAMP NOT NULL,
    "created_by" BIGINT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "accepted_at" TIMESTAMP,
    "cancelled_at" TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);       
ALTER TABLE "public"."pw_dispatch_task" ADD CONSTRAINT "public"."CONSTRAINT_C7E" PRIMARY KEY("id");           
-- 8 +/- SELECT COUNT(*) FROM public.pw_dispatch_task;        
CREATE INDEX "public"."ix_pw_dispatch_task_order" ON "public"."pw_dispatch_task"("order_id" NULLS LAST);      
CREATE INDEX "public"."ix_pw_dispatch_task_status" ON "public"."pw_dispatch_task"("task_status" NULLS LAST);  
CREATE CACHED TABLE "public"."pw_dispatch_candidate"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 165) DEFAULT ON NULL NOT NULL,
    "task_id" BIGINT NOT NULL,
    "player_id" BIGINT NOT NULL,
    "match_score" DECIMAL(8, 2) DEFAULT 0 NOT NULL,
    "active_order_count" INTEGER DEFAULT 0 NOT NULL,
    "candidate_status" CHARACTER VARYING(24) DEFAULT 'PENDING' NOT NULL,
    "notified" BOOLEAN DEFAULT FALSE NOT NULL,
    "responded_at" TIMESTAMP,
    "reject_reason" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);        
ALTER TABLE "public"."pw_dispatch_candidate" ADD CONSTRAINT "public"."CONSTRAINT_E92" PRIMARY KEY("id");      
-- 10 +/- SELECT COUNT(*) FROM public.pw_dispatch_candidate;  
CREATE INDEX "public"."ix_pw_dispatch_candidate_task" ON "public"."pw_dispatch_candidate"("task_id" NULLS LAST);              
CREATE CACHED TABLE "public"."pw_dispatch_action_log"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 166) DEFAULT ON NULL NOT NULL,
    "task_id" BIGINT NOT NULL,
    "order_id" BIGINT NOT NULL,
    "player_id" BIGINT,
    "action_type" CHARACTER VARYING(24) NOT NULL,
    "from_status" CHARACTER VARYING(24),
    "to_status" CHARACTER VARYING(24),
    "operator_id" BIGINT,
    "reason" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);          
ALTER TABLE "public"."pw_dispatch_action_log" ADD CONSTRAINT "public"."CONSTRAINT_FD" PRIMARY KEY("id");      
-- 14 +/- SELECT COUNT(*) FROM public.pw_dispatch_action_log; 
CREATE INDEX "public"."ix_pw_dispatch_action_task" ON "public"."pw_dispatch_action_log"("task_id" NULLS LAST);
CREATE CACHED TABLE "public"."pw_player"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 38) DEFAULT ON NULL NOT NULL,
    "player_no" CHARACTER VARYING(32) NOT NULL,
    "user_id" BIGINT,
    "nickname" CHARACTER VARYING(64) NOT NULL,
    "real_name" CHARACTER VARYING(64),
    "gender" CHARACTER VARYING(16) DEFAULT 'UNKNOWN' NOT NULL,
    "phone" CHARACTER VARYING(32),
    "email" CHARACTER VARYING(128),
    "avatar_url" CHARACTER VARYING(512),
    "cover_url" CHARACTER VARYING(512),
    "introduction" CHARACTER VARYING(1000),
    "voice_url" CHARACTER VARYING(512),
    "audit_status" CHARACTER VARYING(16) DEFAULT 'DRAFT' NOT NULL,
    "work_status" CHARACTER VARYING(16) DEFAULT 'OFFLINE' NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "audit_remark" CHARACTER VARYING(500),
    "approved_at" TIMESTAMP,
    "last_online_at" TIMESTAMP,
    "order_count" INTEGER DEFAULT 0 NOT NULL,
    "rating_score" DECIMAL(4, 2) DEFAULT 0 NOT NULL,
    "rating_count" INTEGER DEFAULT 0 NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "remark" CHARACTER VARYING(500),
    "created_by" BIGINT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_by" BIGINT,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "max_active_orders" INTEGER DEFAULT 1 NOT NULL
);     
ALTER TABLE "public"."pw_player" ADD CONSTRAINT "public"."CONSTRAINT_8" PRIMARY KEY("id");    
-- 6 +/- SELECT COUNT(*) FROM public.pw_player;               
CREATE INDEX "public"."ix_pw_player_status" ON "public"."pw_player"("audit_status" NULLS LAST, "work_status" NULLS LAST, "enabled" NULLS LAST);               
CREATE CACHED TABLE "public"."pw_fulfillment_audit"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) DEFAULT ON NULL NOT NULL,
    "fulfillment_id" BIGINT NOT NULL,
    "action" CHARACTER VARYING(16) NOT NULL,
    "before_status" CHARACTER VARYING(24),
    "after_status" CHARACTER VARYING(24) NOT NULL,
    "remark" CHARACTER VARYING(500),
    "operator_id" BIGINT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);        
ALTER TABLE "public"."pw_fulfillment_audit" ADD CONSTRAINT "public"."CONSTRAINT_AD" PRIMARY KEY("id");        
-- 3 +/- SELECT COUNT(*) FROM public.pw_fulfillment_audit;    
CREATE CACHED TABLE "public"."pw_order_rule"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "customer_confirm_hours" INTEGER DEFAULT 24 NOT NULL,
    "auto_complete_enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);             
ALTER TABLE "public"."pw_order_rule" ADD CONSTRAINT "public"."CONSTRAINT_5A" PRIMARY KEY("id");               
-- 1 +/- SELECT COUNT(*) FROM public.pw_order_rule;           
CREATE CACHED TABLE "public"."pw_after_sale"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "after_sale_no" CHARACTER VARYING(40) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "customer_id" BIGINT NOT NULL,
    "reason_type" CHARACTER VARYING(32) NOT NULL,
    "description" CHARACTER VARYING(1000) NOT NULL,
    "after_sale_status" CHARACTER VARYING(24) DEFAULT 'PENDING' NOT NULL,
    "result_type" CHARACTER VARYING(24),
    "result_remark" CHARACTER VARYING(1000),
    "handled_by" BIGINT,
    "handled_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);        
ALTER TABLE "public"."pw_after_sale" ADD CONSTRAINT "public"."CONSTRAINT_89" PRIMARY KEY("id");               
-- 0 +/- SELECT COUNT(*) FROM public.pw_after_sale;           
CREATE INDEX "public"."ix_pw_after_sale_order" ON "public"."pw_after_sale"("order_id" NULLS LAST);            
CREATE INDEX "public"."ix_pw_after_sale_status" ON "public"."pw_after_sale"("after_sale_status" NULLS LAST);  
CREATE CACHED TABLE "public"."pw_after_sale_proof"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "after_sale_id" BIGINT NOT NULL,
    "proof_url" CHARACTER VARYING(512) NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);           
ALTER TABLE "public"."pw_after_sale_proof" ADD CONSTRAINT "public"."CONSTRAINT_F4" PRIMARY KEY("id");         
-- 0 +/- SELECT COUNT(*) FROM public.pw_after_sale_proof;     
CREATE CACHED TABLE "public"."pw_after_sale_log"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "after_sale_id" BIGINT NOT NULL,
    "action" CHARACTER VARYING(24) NOT NULL,
    "from_status" CHARACTER VARYING(24),
    "to_status" CHARACTER VARYING(24) NOT NULL,
    "remark" CHARACTER VARYING(1000),
    "operator_id" BIGINT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);               
ALTER TABLE "public"."pw_after_sale_log" ADD CONSTRAINT "public"."CONSTRAINT_9" PRIMARY KEY("id");            
-- 0 +/- SELECT COUNT(*) FROM public.pw_after_sale_log;       
CREATE CACHED TABLE "public"."pw_member_level"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "level_code" CHARACTER VARYING(32) NOT NULL,
    "level_name" CHARACTER VARYING(64) NOT NULL,
    "level_no" INTEGER NOT NULL,
    "min_recharge_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "discount_rate" DECIMAL(6, 4) DEFAULT 1 NOT NULL,
    "benefit_description" CHARACTER VARYING(1000),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);          
ALTER TABLE "public"."pw_member_level" ADD CONSTRAINT "public"."CONSTRAINT_CD" PRIMARY KEY("id");             
-- 3 +/- SELECT COUNT(*) FROM public.pw_member_level;         
CREATE CACHED TABLE "public"."pw_user_member"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 65) DEFAULT ON NULL NOT NULL,
    "user_id" BIGINT NOT NULL,
    "level_id" BIGINT NOT NULL,
    "growth_value" BIGINT DEFAULT 0 NOT NULL,
    "total_recharge_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "started_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "expired_at" TIMESTAMP,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);        
ALTER TABLE "public"."pw_user_member" ADD CONSTRAINT "public"."CONSTRAINT_76" PRIMARY KEY("id");              
-- 2 +/- SELECT COUNT(*) FROM public.pw_user_member;          
CREATE CACHED TABLE "public"."pw_recharge_plan"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "plan_code" CHARACTER VARYING(40) NOT NULL,
    "plan_name" CHARACTER VARYING(80) NOT NULL,
    "recharge_amount" DECIMAL(14, 2) NOT NULL,
    "bonus_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "member_days" INTEGER,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);   
ALTER TABLE "public"."pw_recharge_plan" ADD CONSTRAINT "public"."CONSTRAINT_C2" PRIMARY KEY("id");            
-- 3 +/- SELECT COUNT(*) FROM public.pw_recharge_plan;        
CREATE CACHED TABLE "public"."pw_wallet_account"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 98) DEFAULT ON NULL NOT NULL,
    "owner_type" CHARACTER VARYING(16) NOT NULL,
    "owner_id" BIGINT NOT NULL,
    "cash_balance" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "bonus_balance" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "frozen_balance" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);           
ALTER TABLE "public"."pw_wallet_account" ADD CONSTRAINT "public"."CONSTRAINT_C1" PRIMARY KEY("id");           
-- 4 +/- SELECT COUNT(*) FROM public.pw_wallet_account;       
CREATE CACHED TABLE "public"."pw_trade_payment"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 71) DEFAULT ON NULL NOT NULL,
    "payment_no" CHARACTER VARYING(48) NOT NULL,
    "request_no" CHARACTER VARYING(64) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "payment_channel" CHARACTER VARYING(24) NOT NULL,
    "payment_status" CHARACTER VARYING(24) NOT NULL,
    "payable_amount" DECIMAL(14, 2) NOT NULL,
    "cash_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "bonus_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "refunded_cash_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "refunded_bonus_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "paid_at" TIMESTAMP,
    "refunded_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);            
ALTER TABLE "public"."pw_trade_payment" ADD CONSTRAINT "public"."CONSTRAINT_7A" PRIMARY KEY("id");            
-- 13 +/- SELECT COUNT(*) FROM public.pw_trade_payment;       
CREATE INDEX "public"."ix_pw_trade_payment_user" ON "public"."pw_trade_payment"("user_id" NULLS LAST, "id" NULLS LAST);       
CREATE CACHED TABLE "public"."pw_wallet_transaction"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 71) DEFAULT ON NULL NOT NULL,
    "transaction_no" CHARACTER VARYING(48) NOT NULL,
    "account_id" BIGINT NOT NULL,
    "owner_type" CHARACTER VARYING(16) NOT NULL,
    "owner_id" BIGINT NOT NULL,
    "balance_type" CHARACTER VARYING(16) NOT NULL,
    "direction" CHARACTER VARYING(8) NOT NULL,
    "business_type" CHARACTER VARYING(32) NOT NULL,
    "business_no" CHARACTER VARYING(48) NOT NULL,
    "amount" DECIMAL(14, 2) NOT NULL,
    "balance_before" DECIMAL(14, 2) NOT NULL,
    "balance_after" DECIMAL(14, 2) NOT NULL,
    "remark" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);          
ALTER TABLE "public"."pw_wallet_transaction" ADD CONSTRAINT "public"."CONSTRAINT_E1" PRIMARY KEY("id");       
-- 20 +/- SELECT COUNT(*) FROM public.pw_wallet_transaction;  
CREATE INDEX "public"."ix_pw_wallet_tx_owner" ON "public"."pw_wallet_transaction"("owner_type" NULLS LAST, "owner_id" NULLS LAST, "id" NULLS LAST);           
CREATE INDEX "public"."ix_pw_wallet_tx_business" ON "public"."pw_wallet_transaction"("business_type" NULLS LAST, "business_no" NULLS LAST);   
CREATE CACHED TABLE "public"."pw_order_settlement"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 67) DEFAULT ON NULL NOT NULL,
    "settlement_no" CHARACTER VARYING(48) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "order_amount" DECIMAL(14, 2) NOT NULL,
    "platform_amount" DECIMAL(14, 2) NOT NULL,
    "distributable_amount" DECIMAL(14, 2) NOT NULL,
    "settlement_status" CHARACTER VARYING(24) NOT NULL,
    "settled_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "public"."pw_order_settlement" ADD CONSTRAINT "public"."CONSTRAINT_22" PRIMARY KEY("id");         
-- 6 +/- SELECT COUNT(*) FROM public.pw_order_settlement;     
CREATE CACHED TABLE "public"."pw_service_level_price"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "service_id" BIGINT NOT NULL,
    "player_level_id" BIGINT NOT NULL,
    "unit_type" CHARACTER VARYING(16) NOT NULL,
    "price" DECIMAL(12, 2) NOT NULL,
    "market_price" DECIMAL(12, 2),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);       
ALTER TABLE "public"."pw_service_level_price" ADD CONSTRAINT "public"."CONSTRAINT_27" PRIMARY KEY("id");      
-- 21 +/- SELECT COUNT(*) FROM public.pw_service_level_price; 
CREATE INDEX "public"."ix_pw_service_level_price_service" ON "public"."pw_service_level_price"("service_id" NULLS LAST);      
CREATE INDEX "public"."ix_pw_service_level_price_level" ON "public"."pw_service_level_price"("player_level_id" NULLS LAST);   
CREATE CACHED TABLE "public"."pw_commission_rule"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "rule_code" CHARACTER VARYING(32) NOT NULL,
    "rule_name" CHARACTER VARYING(64) NOT NULL,
    "commission_rate" DECIMAL(6, 4) NOT NULL,
    "min_withdraw_amount" DECIMAL(14, 2) NOT NULL,
    "withdraw_weekday" INTEGER NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);  
ALTER TABLE "public"."pw_commission_rule" ADD CONSTRAINT "public"."CONSTRAINT_6D" PRIMARY KEY("id");          
-- 1 +/- SELECT COUNT(*) FROM public.pw_commission_rule;      
CREATE CACHED TABLE "public"."pw_player_account"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 34) DEFAULT ON NULL NOT NULL,
    "player_id" BIGINT NOT NULL,
    "available_balance" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "frozen_balance" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "total_income" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "total_withdrawn" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);              
ALTER TABLE "public"."pw_player_account" ADD CONSTRAINT "public"."CONSTRAINT_E61" PRIMARY KEY("id");          
-- 2 +/- SELECT COUNT(*) FROM public.pw_player_account;       
CREATE CACHED TABLE "public"."pw_service_member_transfer"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "order_id" BIGINT NOT NULL,
    "exception_request_id" BIGINT NOT NULL,
    "from_order_member_id" BIGINT NOT NULL,
    "to_order_member_id" BIGINT NOT NULL,
    "transferred_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);             
ALTER TABLE "public"."pw_service_member_transfer" ADD CONSTRAINT "public"."CONSTRAINT_2C" PRIMARY KEY("id");  
-- 1 +/- SELECT COUNT(*) FROM public.pw_service_member_transfer;              
CREATE INDEX "public"."ix_pw_service_transfer_order" ON "public"."pw_service_member_transfer"("order_id" NULLS LAST, "id" NULLS LAST);        
CREATE CACHED TABLE "public"."pw_withdrawal_request"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "withdrawal_no" CHARACTER VARYING(48) NOT NULL,
    "player_id" BIGINT NOT NULL,
    "amount" DECIMAL(14, 2) NOT NULL,
    "payout_method" CHARACTER VARYING(32) NOT NULL,
    "account_name" CHARACTER VARYING(64) NOT NULL,
    "account_no" CHARACTER VARYING(128) NOT NULL,
    "withdrawal_status" CHARACTER VARYING(20) NOT NULL,
    "review_remark" CHARACTER VARYING(500),
    "reviewed_by" BIGINT,
    "reviewed_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);   
ALTER TABLE "public"."pw_withdrawal_request" ADD CONSTRAINT "public"."CONSTRAINT_2A" PRIMARY KEY("id");       
-- 0 +/- SELECT COUNT(*) FROM public.pw_withdrawal_request;   
CREATE INDEX "public"."ix_pw_withdrawal_player" ON "public"."pw_withdrawal_request"("player_id" NULLS LAST, "id" NULLS LAST); 
CREATE CACHED TABLE "public"."pw_player_account_transaction"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 35) DEFAULT ON NULL NOT NULL,
    "transaction_no" CHARACTER VARYING(48) NOT NULL,
    "account_id" BIGINT NOT NULL,
    "player_id" BIGINT NOT NULL,
    "balance_type" CHARACTER VARYING(16) NOT NULL,
    "direction" CHARACTER VARYING(8) NOT NULL,
    "business_type" CHARACTER VARYING(32) NOT NULL,
    "business_no" CHARACTER VARYING(48) NOT NULL,
    "amount" DECIMAL(14, 2) NOT NULL,
    "balance_before" DECIMAL(14, 2) NOT NULL,
    "balance_after" DECIMAL(14, 2) NOT NULL,
    "remark" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);   
ALTER TABLE "public"."pw_player_account_transaction" ADD CONSTRAINT "public"."CONSTRAINT_8D" PRIMARY KEY("id");               
-- 3 +/- SELECT COUNT(*) FROM public.pw_player_account_transaction;           
CREATE INDEX "public"."ix_pw_player_account_tx" ON "public"."pw_player_account_transaction"("player_id" NULLS LAST, "id" NULLS LAST);         
CREATE CACHED TABLE "public"."pw_player_profile_draft"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "player_id" BIGINT NOT NULL,
    "profile_data" CHARACTER LARGE OBJECT NOT NULL,
    "draft_status" CHARACTER VARYING(16) DEFAULT 'DRAFT' NOT NULL,
    "review_remark" CHARACTER VARYING(500),
    "submitted_at" TIMESTAMP,
    "reviewed_by" BIGINT,
    "reviewed_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);          
ALTER TABLE "public"."pw_player_profile_draft" ADD CONSTRAINT "public"."CONSTRAINT_90" PRIMARY KEY("id");     
-- 1 +/- SELECT COUNT(*) FROM public.pw_player_profile_draft; 
CREATE INDEX "public"."ix_pw_player_profile_draft_status" ON "public"."pw_player_profile_draft"("draft_status" NULLS LAST, "submitted_at" NULLS LAST);        
CREATE CACHED TABLE "public"."pw_game_rank_system"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "game_id" BIGINT NOT NULL,
    "system_code" CHARACTER VARYING(64) NOT NULL,
    "system_name" CHARACTER VARYING(64) NOT NULL,
    "description" CHARACTER VARYING(255),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);    
ALTER TABLE "public"."pw_game_rank_system" ADD CONSTRAINT "public"."CONSTRAINT_A2" PRIMARY KEY("id");         
-- 2 +/- SELECT COUNT(*) FROM public.pw_game_rank_system;     
CREATE INDEX "public"."ix_pw_game_rank_system_game" ON "public"."pw_game_rank_system"("game_id" NULLS LAST);  
CREATE CACHED TABLE "public"."pw_player_game"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 97) DEFAULT ON NULL NOT NULL,
    "player_id" BIGINT NOT NULL,
    "game_id" BIGINT NOT NULL,
    "game_nickname" CHARACTER VARYING(64),
    "game_account" CHARACTER VARYING(128),
    "server_name" CHARACTER VARYING(128),
    "rank_name" CHARACTER VARYING(64),
    "rank_level" INTEGER,
    "experience_years" INTEGER,
    "introduction" CHARACTER VARYING(500),
    "proof_url" CHARACTER VARYING(512),
    "is_primary" BOOLEAN DEFAULT FALSE NOT NULL,
    "audit_status" CHARACTER VARYING(16) DEFAULT 'PENDING' NOT NULL,
    "audit_remark" CHARACTER VARYING(500),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "price_level_id" BIGINT,
    "server_id" BIGINT,
    "rank_id" BIGINT
);     
ALTER TABLE "public"."pw_player_game" ADD CONSTRAINT "public"."CONSTRAINT_A" PRIMARY KEY("id");               
-- 7 +/- SELECT COUNT(*) FROM public.pw_player_game;          
CREATE INDEX "public"."ix_pw_player_game_player" ON "public"."pw_player_game"("player_id" NULLS LAST);        
CREATE CACHED TABLE "public"."pw_order_member"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 68) DEFAULT ON NULL NOT NULL,
    "order_id" BIGINT NOT NULL,
    "player_id" BIGINT NOT NULL,
    "member_status" CHARACTER VARYING(24) DEFAULT 'ACCEPTED' NOT NULL,
    "join_source" CHARACTER VARYING(24) DEFAULT 'LEGACY' NOT NULL,
    "dispatch_task_id" BIGINT,
    "joined_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "service_started_at" TIMESTAMP,
    "completed_at" TIMESTAMP,
    "cancelled_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 
ALTER TABLE "public"."pw_order_member" ADD CONSTRAINT "public"."CONSTRAINT_3B" PRIMARY KEY("id");             
-- 17 +/- SELECT COUNT(*) FROM public.pw_order_member;        
CREATE INDEX "public"."ix_pw_order_member_order" ON "public"."pw_order_member"("order_id" NULLS LAST, "member_status" NULLS LAST);            
CREATE INDEX "public"."ix_pw_order_member_player" ON "public"."pw_order_member"("player_id" NULLS LAST, "member_status" NULLS LAST);          
CREATE CACHED TABLE "public"."pw_game_rank"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 65) DEFAULT ON NULL NOT NULL,
    "rank_system_id" BIGINT NOT NULL,
    "rank_code" CHARACTER VARYING(64) NOT NULL,
    "rank_name" CHARACTER VARYING(64) NOT NULL,
    "tier_no" INTEGER DEFAULT 0 NOT NULL,
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);        
ALTER TABLE "public"."pw_game_rank" ADD CONSTRAINT "public"."CONSTRAINT_76F" PRIMARY KEY("id");               
-- 16 +/- SELECT COUNT(*) FROM public.pw_game_rank;           
CREATE INDEX "public"."ix_pw_game_rank_system" ON "public"."pw_game_rank"("rank_system_id" NULLS LAST);       
CREATE CACHED TABLE "public"."pw_customer_game_profile"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 129) DEFAULT ON NULL NOT NULL,
    "user_id" BIGINT NOT NULL,
    "game_id" BIGINT NOT NULL,
    "server_id" BIGINT,
    "game_account" CHARACTER VARYING(128) NOT NULL,
    "game_nickname" CHARACTER VARYING(128) NOT NULL,
    "is_default" BOOLEAN DEFAULT FALSE NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);    
ALTER TABLE "public"."pw_customer_game_profile" ADD CONSTRAINT "public"."CONSTRAINT_EA" PRIMARY KEY("id");    
-- 3 +/- SELECT COUNT(*) FROM public.pw_customer_game_profile;
CREATE INDEX "public"."ix_pw_customer_game_profile_user" ON "public"."pw_customer_game_profile"("user_id" NULLS LAST, "game_id" NULLS LAST);  
CREATE CACHED TABLE "public"."pw_customer_game_rank"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 129) DEFAULT ON NULL NOT NULL,
    "profile_id" BIGINT NOT NULL,
    "rank_system_id" BIGINT NOT NULL,
    "rank_id" BIGINT NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 
ALTER TABLE "public"."pw_customer_game_rank" ADD CONSTRAINT "public"."CONSTRAINT_26" PRIMARY KEY("id");       
-- 3 +/- SELECT COUNT(*) FROM public.pw_customer_game_rank;   
CREATE INDEX "public"."ix_pw_customer_game_rank_profile" ON "public"."pw_customer_game_rank"("profile_id" NULLS LAST);        
CREATE CACHED TABLE "public"."pw_order_settlement_detail"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 69) DEFAULT ON NULL NOT NULL,
    "settlement_id" BIGINT NOT NULL,
    "order_id" BIGINT NOT NULL,
    "order_member_id" BIGINT,
    "player_id" BIGINT,
    "detail_type" CHARACTER VARYING(32) NOT NULL,
    "amount" DECIMAL(14, 2) NOT NULL,
    "calculation_base" DECIMAL(14, 2),
    "rate" DECIMAL(8, 4),
    "remark" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);     
ALTER TABLE "public"."pw_order_settlement_detail" ADD CONSTRAINT "public"."CONSTRAINT_82" PRIMARY KEY("id");  
-- 12 +/- SELECT COUNT(*) FROM public.pw_order_settlement_detail;             
CREATE UNIQUE NULLS DISTINCT INDEX "public"."uk_pw_settlement_member_type" ON "public"."pw_order_settlement_detail"("settlement_id" NULLS LAST, "order_member_id" NULLS LAST, "detail_type" NULLS LAST);      
CREATE INDEX "public"."ix_pw_settlement_detail_order" ON "public"."pw_order_settlement_detail"("order_id" NULLS LAST, "id" NULLS LAST);       
CREATE CACHED TABLE "public"."pw_trade_order"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 103) DEFAULT ON NULL NOT NULL,
    "order_no" CHARACTER VARYING(40) NOT NULL,
    "customer_id" BIGINT NOT NULL,
    "business_type" CHARACTER VARYING(32) NOT NULL,
    "trade_status" CHARACTER VARYING(32) NOT NULL,
    "title" CHARACTER VARYING(128),
    "total_amount" DECIMAL(14, 2) NOT NULL,
    "discount_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "payable_amount" DECIMAL(14, 2) NOT NULL,
    "paid_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "refunded_amount" DECIMAL(14, 2) DEFAULT 0 NOT NULL,
    "payment_status" CHARACTER VARYING(24) DEFAULT 'UNPAID' NOT NULL,
    "refund_status" CHARACTER VARYING(24) DEFAULT 'NONE' NOT NULL,
    "customer_remark" CHARACTER VARYING(1000),
    "cancel_reason" CHARACTER VARYING(500),
    "paid_at" TIMESTAMP,
    "completed_at" TIMESTAMP,
    "cancelled_at" TIMESTAMP,
    "created_by" BIGINT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "public"."pw_trade_order" ADD CONSTRAINT "public"."CONSTRAINT_14" PRIMARY KEY("id");              
-- 25 +/- SELECT COUNT(*) FROM public.pw_trade_order;         
CREATE INDEX "public"."ix_pw_trade_order_customer" ON "public"."pw_trade_order"("customer_id" NULLS LAST, "business_type" NULLS LAST, "id" NULLS LAST);       
CREATE INDEX "public"."ix_pw_trade_order_status" ON "public"."pw_trade_order"("business_type" NULLS LAST, "trade_status" NULLS LAST, "id" NULLS LAST);        
CREATE CACHED TABLE "public"."pw_service_order"(
    "order_id" BIGINT NOT NULL,
    "requested_player_id" BIGINT,
    "requested_player_level_id" BIGINT,
    "player_level_code" CHARACTER VARYING(32),
    "player_level_name" CHARACTER VARYING(64),
    "required_player_count" INTEGER DEFAULT 1 NOT NULL,
    "pricing_mode" CHARACTER VARYING(32) DEFAULT 'FIXED_SKU' NOT NULL,
    "price_type" CHARACTER VARYING(20) DEFAULT 'PER_PLAYER' NOT NULL,
    "base_unit_price" DECIMAL(14, 2),
    "contact_name" CHARACTER VARYING(64),
    "contact_phone" CHARACTER VARYING(32),
    "service_status" CHARACTER VARYING(32) NOT NULL,
    "assigned_at" TIMESTAMP,
    "service_started_at" TIMESTAMP,
    "completion_submitted_at" TIMESTAMP,
    "customer_confirm_deadline" TIMESTAMP,
    "customer_confirmed_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 
ALTER TABLE "public"."pw_service_order" ADD CONSTRAINT "public"."CONSTRAINT_DF" PRIMARY KEY("order_id");      
-- 18 +/- SELECT COUNT(*) FROM public.pw_service_order;       
CREATE INDEX "public"."ix_pw_service_order_status" ON "public"."pw_service_order"("service_status" NULLS LAST, "order_id" NULLS LAST);        
CREATE INDEX "public"."ix_pw_service_order_requested_player" ON "public"."pw_service_order"("requested_player_id" NULLS LAST, "order_id" NULLS LAST);         
CREATE CACHED TABLE "public"."pw_recharge_order"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 66) DEFAULT ON NULL NOT NULL,
    "recharge_no" CHARACTER VARYING(40) NOT NULL,
    "request_no" CHARACTER VARYING(64) NOT NULL,
    "user_id" BIGINT NOT NULL,
    "plan_id" BIGINT NOT NULL,
    "recharge_amount" DECIMAL(14, 2) NOT NULL,
    "bonus_amount" DECIMAL(14, 2) NOT NULL,
    "recharge_status" CHARACTER VARYING(20) NOT NULL,
    "paid_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "trade_order_id" BIGINT
);               
ALTER TABLE "public"."pw_recharge_order" ADD CONSTRAINT "public"."CONSTRAINT_8B" PRIMARY KEY("id");           
-- 7 +/- SELECT COUNT(*) FROM public.pw_recharge_order;       
CREATE UNIQUE NULLS DISTINCT INDEX "public"."uk_pw_recharge_trade_order" ON "public"."pw_recharge_order"("trade_order_id" NULLS LAST);        
CREATE CACHED TABLE "public"."pw_platform_ledger"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 35) DEFAULT ON NULL NOT NULL,
    "ledger_no" CHARACTER VARYING(48) NOT NULL,
    "order_id" BIGINT,
    "settlement_detail_id" BIGINT,
    "business_type" CHARACTER VARYING(32) NOT NULL,
    "direction" CHARACTER VARYING(8) NOT NULL,
    "amount" DECIMAL(14, 2) NOT NULL,
    "remark" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "public"."pw_platform_ledger" ADD CONSTRAINT "public"."CONSTRAINT_896" PRIMARY KEY("id");         
-- 3 +/- SELECT COUNT(*) FROM public.pw_platform_ledger;      
CREATE INDEX "public"."ix_pw_platform_ledger_order" ON "public"."pw_platform_ledger"("order_id" NULLS LAST, "id" NULLS LAST); 
CREATE CACHED TABLE "public"."pw_player_earning"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 67) DEFAULT ON NULL NOT NULL,
    "earning_no" CHARACTER VARYING(48) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "order_member_id" BIGINT,
    "settlement_detail_id" BIGINT,
    "player_id" BIGINT NOT NULL,
    "order_amount" DECIMAL(14, 2) NOT NULL,
    "commission_rate" DECIMAL(6, 4) NOT NULL,
    "commission_amount" DECIMAL(14, 2) NOT NULL,
    "player_amount" DECIMAL(14, 2) NOT NULL,
    "earning_status" CHARACTER VARYING(20) NOT NULL,
    "settled_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);         
ALTER TABLE "public"."pw_player_earning" ADD CONSTRAINT "public"."CONSTRAINT_12" PRIMARY KEY("id");           
-- 6 +/- SELECT COUNT(*) FROM public.pw_player_earning;       
CREATE UNIQUE NULLS DISTINCT INDEX "public"."uk_pw_player_earning_member" ON "public"."pw_player_earning"("order_member_id" NULLS LAST);      
CREATE INDEX "public"."ix_pw_player_earning_order" ON "public"."pw_player_earning"("order_id" NULLS LAST, "id" NULLS LAST);   
CREATE CACHED TABLE "public"."pw_service_liability"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "liability_no" CHARACTER VARYING(48) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "exception_request_id" BIGINT,
    "liability_type" CHARACTER VARYING(32) NOT NULL,
    "root_order_member_id" BIGINT,
    "liable_order_member_id" BIGINT NOT NULL,
    "beneficiary_order_member_id" BIGINT,
    "liable_player_id" BIGINT NOT NULL,
    "beneficiary_player_id" BIGINT,
    "calculation_base" DECIMAL(14, 2) NOT NULL,
    "rate" DECIMAL(8, 4) NOT NULL,
    "amount" DECIMAL(14, 2) NOT NULL,
    "liability_status" CHARACTER VARYING(24) NOT NULL,
    "determined_by" BIGINT,
    "determined_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "remark" CHARACTER VARYING(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);        
ALTER TABLE "public"."pw_service_liability" ADD CONSTRAINT "public"."CONSTRAINT_51" PRIMARY KEY("id");        
-- 0 +/- SELECT COUNT(*) FROM public.pw_service_liability;    
CREATE UNIQUE NULLS DISTINCT INDEX "public"."uk_pw_service_liability_member" ON "public"."pw_service_liability"("order_id" NULLS LAST, "liability_type" NULLS LAST, "liable_order_member_id" NULLS LAST);     
CREATE INDEX "public"."ix_pw_service_liability_order" ON "public"."pw_service_liability"("order_id" NULLS LAST, "id" NULLS LAST);             
CREATE CACHED TABLE "public"."pw_service_penalty_ledger"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "ledger_no" CHARACTER VARYING(48) NOT NULL,
    "liability_id" BIGINT NOT NULL,
    "order_id" BIGINT NOT NULL,
    "player_id" BIGINT NOT NULL,
    "counterparty_player_id" BIGINT,
    "entry_type" CHARACTER VARYING(32) NOT NULL,
    "direction" CHARACTER VARYING(8) NOT NULL,
    "amount" DECIMAL(14, 2) NOT NULL,
    "balance_before" DECIMAL(14, 2) NOT NULL,
    "balance_after" DECIMAL(14, 2) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);   
ALTER TABLE "public"."pw_service_penalty_ledger" ADD CONSTRAINT "public"."CONSTRAINT_5E" PRIMARY KEY("id");   
-- 0 +/- SELECT COUNT(*) FROM public.pw_service_penalty_ledger;               
CREATE UNIQUE NULLS DISTINCT INDEX "public"."uk_pw_service_penalty_entry" ON "public"."pw_service_penalty_ledger"("liability_id" NULLS LAST, "player_id" NULLS LAST, "direction" NULLS LAST); 
CREATE INDEX "public"."ix_pw_service_penalty_order" ON "public"."pw_service_penalty_ledger"("order_id" NULLS LAST, "id" NULLS LAST);          
CREATE CACHED TABLE "public"."pw_service_item"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) DEFAULT ON NULL NOT NULL,
    "game_id" BIGINT NOT NULL,
    "service_code" CHARACTER VARYING(64) NOT NULL,
    "service_name" CHARACTER VARYING(64) NOT NULL,
    "service_type" CHARACTER VARYING(32) NOT NULL,
    "description" CHARACTER VARYING(1000),
    "sort_no" INTEGER DEFAULT 0 NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "usage_type" CHARACTER VARYING(32) DEFAULT 'STANDALONE' NOT NULL
);          
ALTER TABLE "public"."pw_service_item" ADD CONSTRAINT "public"."CONSTRAINT_E6" PRIMARY KEY("id");             
-- 6 +/- SELECT COUNT(*) FROM public.pw_service_item;         
CREATE INDEX "public"."ix_pw_service_item_game" ON "public"."pw_service_item"("game_id" NULLS LAST);          
CREATE CACHED TABLE "public"."pw_service_pause_record"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "order_id" BIGINT NOT NULL,
    "pause_request_id" BIGINT NOT NULL,
    "resume_request_id" BIGINT,
    "pause_reason" CHARACTER VARYING(1000) NOT NULL,
    "resume_reason" CHARACTER VARYING(1000),
    "paused_at" TIMESTAMP NOT NULL,
    "resumed_at" TIMESTAMP,
    "paused_by" BIGINT NOT NULL,
    "resumed_by" BIGINT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);             
ALTER TABLE "public"."pw_service_pause_record" ADD CONSTRAINT "public"."CONSTRAINT_E5" PRIMARY KEY("id");     
-- 0 +/- SELECT COUNT(*) FROM public.pw_service_pause_record; 
CREATE INDEX "public"."ix_pw_service_pause_order" ON "public"."pw_service_pause_record"("order_id" NULLS LAST, "paused_at" NULLS LAST, "id" NULLS LAST);      
ALTER TABLE "public"."pw_player_level" ADD CONSTRAINT "public"."CONSTRAINT_D5B1CB" UNIQUE NULLS DISTINCT ("game_id", "level_code");           
ALTER TABLE "public"."pw_player" ADD CONSTRAINT "public"."CONSTRAINT_8E" UNIQUE NULLS DISTINCT ("player_no"); 
ALTER TABLE "public"."pw_recharge_plan" ADD CONSTRAINT "public"."CONSTRAINT_C27" UNIQUE NULLS DISTINCT ("plan_code");         
ALTER TABLE "public"."pw_service_exception_request" ADD CONSTRAINT "public"."CONSTRAINT_20F" UNIQUE NULLS DISTINCT ("request_no");            
ALTER TABLE "public"."pw_player" ADD CONSTRAINT "public"."CONSTRAINT_8E4" UNIQUE NULLS DISTINCT ("user_id");  
ALTER TABLE "public"."pw_withdrawal_request" ADD CONSTRAINT "public"."CONSTRAINT_2A4" UNIQUE NULLS DISTINCT ("withdrawal_no");
ALTER TABLE "public"."pw_service_item" ADD CONSTRAINT "public"."CONSTRAINT_E62" UNIQUE NULLS DISTINCT ("service_code");       
ALTER TABLE "public"."pw_order_member" ADD CONSTRAINT "public"."CONSTRAINT_3BD" UNIQUE NULLS DISTINCT ("order_id", "player_id");              
ALTER TABLE "public"."pw_service_pause_record" ADD CONSTRAINT "public"."CONSTRAINT_E5D" UNIQUE NULLS DISTINCT ("pause_request_id");           
ALTER TABLE "public"."pw_order_settlement" ADD CONSTRAINT "public"."CONSTRAINT_220D" UNIQUE NULLS DISTINCT ("order_id");      
ALTER TABLE "public"."pw_trade_payment" ADD CONSTRAINT "public"."CONSTRAINT_7A9B6" UNIQUE NULLS DISTINCT ("user_id", "request_no");           
ALTER TABLE "public"."pw_product_sku" ADD CONSTRAINT "public"."CONSTRAINT_31F" UNIQUE NULLS DISTINCT ("sku_code");            
ALTER TABLE "public"."pw_member_level" ADD CONSTRAINT "public"."CONSTRAINT_CDA7" UNIQUE NULLS DISTINCT ("level_no");          
ALTER TABLE "public"."pw_player_account_transaction" ADD CONSTRAINT "public"."CONSTRAINT_8D0" UNIQUE NULLS DISTINCT ("transaction_no");       
ALTER TABLE "public"."pw_service_member_transfer" ADD CONSTRAINT "public"."CONSTRAINT_2CB3" UNIQUE NULLS DISTINCT ("from_order_member_id");   
ALTER TABLE "public"."pw_wallet_account" ADD CONSTRAINT "public"."CONSTRAINT_C11" UNIQUE NULLS DISTINCT ("owner_type", "owner_id");           
ALTER TABLE "public"."pw_sku_level_price" ADD CONSTRAINT "public"."CONSTRAINT_5470C" UNIQUE NULLS DISTINCT ("sku_id", "player_level_id");     
ALTER TABLE "public"."pw_service_pause_record" ADD CONSTRAINT "public"."CONSTRAINT_E5D8" UNIQUE NULLS DISTINCT ("resume_request_id");         
ALTER TABLE "public"."pw_service_level_price" ADD CONSTRAINT "public"."CONSTRAINT_277" UNIQUE NULLS DISTINCT ("service_id", "player_level_id", "unit_type");  
ALTER TABLE "public"."pw_trade_payment" ADD CONSTRAINT "public"."CONSTRAINT_7A9" UNIQUE NULLS DISTINCT ("payment_no");        
ALTER TABLE "public"."pw_service_penalty_ledger" ADD CONSTRAINT "public"."CONSTRAINT_5E6" UNIQUE NULLS DISTINCT ("ledger_no");
ALTER TABLE "public"."pw_recharge_order" ADD CONSTRAINT "public"."CONSTRAINT_8BC" UNIQUE NULLS DISTINCT ("recharge_no");      
ALTER TABLE "public"."pw_player_game" ADD CONSTRAINT "public"."CONSTRAINT_AC" UNIQUE NULLS DISTINCT ("player_id", "game_id"); 
ALTER TABLE "public"."pw_trade_order" ADD CONSTRAINT "public"."CONSTRAINT_145" UNIQUE NULLS DISTINCT ("order_no");            
ALTER TABLE "public"."pw_customer_game_rank" ADD CONSTRAINT "public"."CONSTRAINT_262" UNIQUE NULLS DISTINCT ("profile_id", "rank_system_id"); 
ALTER TABLE "public"."pw_dispatch_task" ADD CONSTRAINT "public"."CONSTRAINT_C7EE" UNIQUE NULLS DISTINCT ("task_no");          
ALTER TABLE "public"."pw_game_position" ADD CONSTRAINT "public"."CONSTRAINT_1F" UNIQUE NULLS DISTINCT ("game_id", "position_code");           
ALTER TABLE "public"."pw_after_sale" ADD CONSTRAINT "public"."CONSTRAINT_89B" UNIQUE NULLS DISTINCT ("after_sale_no");        
ALTER TABLE "public"."pw_player_game_position" ADD CONSTRAINT "public"."CONSTRAINT_DC" UNIQUE NULLS DISTINCT ("player_game_id", "position_id");               
ALTER TABLE "public"."pw_product" ADD CONSTRAINT "public"."CONSTRAINT_46" UNIQUE NULLS DISTINCT ("product_code");             
ALTER TABLE "public"."sys_role" ADD CONSTRAINT "public"."CONSTRAINT_74A6" UNIQUE NULLS DISTINCT ("code");     
ALTER TABLE "public"."pw_dispatch_candidate" ADD CONSTRAINT "public"."CONSTRAINT_E924" UNIQUE NULLS DISTINCT ("task_id", "player_id");        
ALTER TABLE "public"."pw_player_earning" ADD CONSTRAINT "public"."CONSTRAINT_12E" UNIQUE NULLS DISTINCT ("earning_no");       
ALTER TABLE "public"."pw_user_member" ADD CONSTRAINT "public"."CONSTRAINT_76D" UNIQUE NULLS DISTINCT ("user_id");             
ALTER TABLE "public"."pw_game_rank_system" ADD CONSTRAINT "public"."CONSTRAINT_A20" UNIQUE NULLS DISTINCT ("game_id", "system_code");         
ALTER TABLE "public"."pw_recharge_order" ADD CONSTRAINT "public"."CONSTRAINT_8BC6" UNIQUE NULLS DISTINCT ("user_id", "request_no");           
ALTER TABLE "public"."pw_service_member_transfer" ADD CONSTRAINT "public"."CONSTRAINT_2CB3E" UNIQUE NULLS DISTINCT ("to_order_member_id");    
ALTER TABLE "public"."sys_menu" ADD CONSTRAINT "public"."CONSTRAINT_74A44" UNIQUE NULLS DISTINCT ("name");    
ALTER TABLE "public"."pw_product_category" ADD CONSTRAINT "public"."CONSTRAINT_E994" UNIQUE NULLS DISTINCT ("category_code"); 
ALTER TABLE "public"."pw_game_server" ADD CONSTRAINT "public"."CONSTRAINT_8B20" UNIQUE NULLS DISTINCT ("game_id", "server_code");             
ALTER TABLE "public"."pw_game_rank" ADD CONSTRAINT "public"."CONSTRAINT_76F3" UNIQUE NULLS DISTINCT ("rank_system_id", "rank_code");          
ALTER TABLE "public"."pw_wallet_transaction" ADD CONSTRAINT "public"."CONSTRAINT_E14" UNIQUE NULLS DISTINCT ("transaction_no");               
ALTER TABLE "public"."pw_commission_rule" ADD CONSTRAINT "public"."CONSTRAINT_6D3" UNIQUE NULLS DISTINCT ("rule_code");       
ALTER TABLE "public"."pw_player_tag" ADD CONSTRAINT "public"."CONSTRAINT_AAB" UNIQUE NULLS DISTINCT ("tag_code");             
ALTER TABLE "public"."pw_service_liability" ADD CONSTRAINT "public"."CONSTRAINT_518" UNIQUE NULLS DISTINCT ("liability_no");  
ALTER TABLE "public"."pw_fulfillment" ADD CONSTRAINT "public"."CONSTRAINT_756" UNIQUE NULLS DISTINCT ("order_member_id");     
ALTER TABLE "public"."pw_customer_game_profile" ADD CONSTRAINT "public"."CONSTRAINT_EA5" UNIQUE NULLS DISTINCT ("user_id", "game_id", "game_account");        
ALTER TABLE "public"."pw_service_member_transfer" ADD CONSTRAINT "public"."CONSTRAINT_2CB" UNIQUE NULLS DISTINCT ("exception_request_id");    
ALTER TABLE "public"."sys_user" ADD CONSTRAINT "public"."CONSTRAINT_74" UNIQUE NULLS DISTINCT ("username");   
ALTER TABLE "public"."pw_member_level" ADD CONSTRAINT "public"."CONSTRAINT_CDA" UNIQUE NULLS DISTINCT ("level_code");         
ALTER TABLE "public"."pw_player_profile_draft" ADD CONSTRAINT "public"."CONSTRAINT_902" UNIQUE NULLS DISTINCT ("player_id");  
ALTER TABLE "public"."pw_trade_payment" ADD CONSTRAINT "public"."CONSTRAINT_7A9B" UNIQUE NULLS DISTINCT ("order_id");         
ALTER TABLE "public"."pw_order_settlement" ADD CONSTRAINT "public"."CONSTRAINT_220" UNIQUE NULLS DISTINCT ("settlement_no");  
ALTER TABLE "public"."pw_game" ADD CONSTRAINT "public"."CONSTRAINT_F5" UNIQUE NULLS DISTINCT ("game_code");   
ALTER TABLE "public"."pw_player_account" ADD CONSTRAINT "public"."CONSTRAINT_E619" UNIQUE NULLS DISTINCT ("player_id");       
ALTER TABLE "public"."pw_platform_ledger" ADD CONSTRAINT "public"."CONSTRAINT_8968" UNIQUE NULLS DISTINCT ("ledger_no");      
