<template>
  <view class="page tab-page">
    <template v-if="mode.isPlayerMode">
      <view class="player-head"><view class="eyebrow">陪玩师工作台</view><view class="title">{{ auth.user?.nickName || '陪玩师' }}，准备好接单了吗？</view><view class="muted">今日服务状态和派单邀请都在这里</view></view>
      <view class="card status-card"><view><view class="label">当前状态</view><view class="work-status">{{ workbench.workStatus || 'OFFLINE' }}</view></view><button size="mini" @click="toggleStatus">{{ workbench.workStatus==='AVAILABLE'?'暂停接单':'开始接单' }}</button></view>
      <view class="stats"><view><text>{{ workbench.pendingDispatchCount || 0 }}</text><label>待响应邀请</label></view><view><text>{{ workbench.activeOrderCount || 0 }}</text><label>进行中订单</label></view><view><text>{{ workbench.completedOrderCount || 0 }}</text><label>已完成服务</label></view></view>
      <view class="card"><view class="section-title">快捷处理</view><view class="grid player-grid"><view @click="goPage('/subpackages/player/dispatches')">待抢订单</view><view @click="goPage('/subpackages/player/orders')">服务订单</view><view @click="planned('收益中心')">收益中心</view></view></view>
    </template>
    <template v-else>
      <view class="hero"><view class="seal">凌竞</view><view class="eyebrow">战术陪伴 · 安心撤离</view><view class="title">山河有约，寻同道战友</view><view class="muted">服务履约更透明，接单进度随时可查</view></view>
      <view class="card"><view class="section-title">游戏服务</view><view class="notice">商城公开接口尚未开放。当前版本优先提供订单和陪玩履约闭环。</view></view>
      <view class="card"><view class="section-title">快捷入口</view><view class="grid"><view @click="goTab('/pages/customer/orders')">我的订单</view><view @click="goTab('/pages/discover/index')">找陪玩</view><view @click="planned('在线客服')">联系客服</view></view></view>
    </template>
  </view>
  <FirstVisitNotice :visible="showNotice" @confirm="acceptNotice" @close="showNotice=false" />
</template>
<script setup lang="ts">
import{ref}from'vue';import{onShow}from'@dcloudio/uni-app';import{useAuthStore}from'@/stores/auth';import{useAppModeStore}from'@/stores/app-mode';import{getWorkbench,updateWorkStatus}from'@/api/player';import FirstVisitNotice from '@/components/FirstVisitNotice.vue';import type{RecordData}from'@/types/api';
const NOTICE_KEY='peiwan_service_notice_v1',auth=useAuthStore(),mode=useAppModeStore(),showNotice=ref(false),workbench=ref<RecordData>({});onShow(async()=>{showNotice.value=!uni.getStorageSync(NOTICE_KEY);if(mode.isPlayerMode&&auth.isPlayer)workbench.value=await getWorkbench()});function acceptNotice(){uni.setStorageSync(NOTICE_KEY,true);showNotice.value=false}async function toggleStatus(){await updateWorkStatus(workbench.value.workStatus==='AVAILABLE'?'OFFLINE':'AVAILABLE');workbench.value=await getWorkbench()}const goTab=(url:string)=>{const paths=['/pages/home/index','/pages/customer/orders','/pages/discover/index','/pages/messages/index','/pages/profile/index'];const index=paths.indexOf(url);uni.setStorageSync('peiwan_pending_tab',{index,mode:mode.mode,path:url,at:Date.now()});uni.switchTab({url})};const goPage=(url:string)=>uni.navigateTo({url});const planned=(name:string)=>uni.showToast({title:`${name}将在后续版本开放`,icon:'none'})
</script>
<style scoped>.tab-page{padding-bottom:170rpx}.hero,.player-head{position:relative;min-height:230rpx;padding:50rpx 18rpx 42rpx}.hero .muted,.player-head .muted{margin-top:14rpx}.eyebrow{margin-bottom:14rpx;color:#4f6f62;font-weight:700;letter-spacing:4rpx}.seal{position:absolute;right:12rpx;top:35rpx;width:64rpx;height:64rpx;border:4rpx double #963d31;color:#963d31;display:flex;align-items:center;justify-content:center;font-family:STKaiti,KaiTi,serif;font-weight:800;transform:rotate(5deg)}.section-title{font-family:STKaiti,KaiTi,serif;font-size:32rpx;font-weight:800;margin-bottom:22rpx}.notice{background:rgba(195,211,194,.45);border-left:6rpx solid #557869;color:#365247;padding:24rpx;border-radius:4rpx 16rpx 16rpx 4rpx;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16rpx}.grid view{border:1rpx solid rgba(60,87,73,.18);background:rgba(235,238,225,.72);padding:30rpx 10rpx;text-align:center;border-radius:8rpx 18rpx 8rpx 18rpx}.status-card{display:flex;align-items:center;justify-content:space-between}.label{color:#76837b;font-size:22rpx}.work-status{margin-top:10rpx;color:#315c50;font-size:36rpx;font-weight:800}.status-card button{margin:0;background:#315c50;color:#fff}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:15rpx;margin-bottom:24rpx}.stats view{padding:26rpx 8rpx;border:1rpx solid rgba(54,79,68,.16);border-radius:8rpx 20rpx 8rpx 20rpx;text-align:center;background:rgba(255,253,244,.88)}.stats text{display:block;color:#21332b;font-size:36rpx;font-weight:800}.stats label{display:block;margin-top:9rpx;color:#76837b;font-size:19rpx}.player-grid view{color:#345f53;background:rgba(210,223,207,.62)}</style>
