package com.peiwan.platform.customer;
import com.peiwan.platform.common.*;import com.peiwan.platform.order.OrderService;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController public class CustomerOrderController{private final CustomerOrderService service;private final AuditService audit;private final OrderService orders;public CustomerOrderController(CustomerOrderService s,AuditService a,OrderService orders){service=s;audit=a;this.orders=orders;}
 @PreAuthorize("hasRole('customer')") @PostMapping("/api/customer/orders") public ApiResponse<?> create(Authentication a,@RequestBody CreateOrder b,HttpServletRequest r){if(b.customerGameProfileId()==null&&(blank(b.gameAccount())||blank(b.gameNickname())))throw new IllegalArgumentException("请选择游戏账号或完整填写游戏账号和昵称");if(blank(b.contactName())||b.contactPhone()==null||!b.contactPhone().matches("^1\\d{10}$"))throw new IllegalArgumentException("请填写正确的联系人和11位手机号");long uid=uid(a);long id=orders.create(new OrderService.CreateCommand(uid,b.skuId(),b.quantity(),b.contactName(),b.contactPhone(),b.customerRemark(),b.gameAccount(),b.gameNickname(),b.serverName(),b.rankName(),b.extraRequirement(),b.requestedPlayerId(),b.playerLevelId(),b.customerGameProfileId(),b.serverId(),b.currentRankId(),b.targetRankId()),uid);audit.operation(a,"customer:order:create","ORDER",id,"顾客自助下单",r);return ApiResponse.ok(Map.of("id",id));}
 @PreAuthorize("hasAuthority('customer:order:list')") @GetMapping("/api/customer/orders") public ApiResponse<?> own(Authentication a,@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String status){return ApiResponse.ok(service.ownList(uid(a),current,size,status));}
 @PreAuthorize("hasAuthority('customer:order:list')") @GetMapping("/api/customer/orders/summary") public ApiResponse<?> summary(Authentication a){return ApiResponse.ok(service.ownSummary(uid(a)));}
 @PreAuthorize("hasAuthority('customer:order:detail')") @GetMapping("/api/customer/orders/{id}") public ApiResponse<?> detail(Authentication a,@PathVariable long id){return ApiResponse.ok(service.ownDetail(uid(a),id));}
 @PreAuthorize("hasAuthority('customer:order:confirm')") @PutMapping("/api/customer/orders/{id}/confirm") public ApiResponse<?> confirm(Authentication a,@PathVariable long id,HttpServletRequest r){service.confirm(uid(a),id);audit.operation(a,"customer:order:confirm","ORDER",id,"确认完成",r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('customer:order:cancel')") @PutMapping("/api/customer/orders/{id}/cancel") public ApiResponse<?> cancel(Authentication a,@PathVariable long id,@RequestBody(required=false) Cancel b,HttpServletRequest r){String reason=b==null?"用户取消":b.reason();orders.cancelOwn(uid(a),id,reason);audit.operation(a,"customer:order:cancel","ORDER",id,reason,r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('customer:after-sale:create')") @PostMapping("/api/customer/orders/{id}/after-sale") public ApiResponse<?> afterSale(Authentication a,@PathVariable long id,@RequestBody CustomerOrderService.AfterSaleCommand b,HttpServletRequest r){long aid=service.createAfterSale(uid(a),id,b);audit.operation(a,"customer:after-sale:create","AFTER_SALE",aid,"order="+id,r);return ApiResponse.ok(Map.of("id",aid));}
 @PreAuthorize("hasAuthority('business:after-sale:list') or hasRole('admin')") @GetMapping("/api/business/after-sale/list") public ApiResponse<?> list(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String status){return ApiResponse.ok(service.adminList(current,size,status));}
 @PreAuthorize("hasAuthority('business:after-sale:detail') or hasRole('admin')") @GetMapping("/api/business/after-sale/{id}") public ApiResponse<?> adminDetail(@PathVariable long id){return ApiResponse.ok(service.adminDetail(id));}
 @PreAuthorize("hasAuthority('business:after-sale:handle') or hasRole('admin')") @PutMapping("/api/business/after-sale/{id}/handle") public ApiResponse<?> handle(Authentication a,@PathVariable long id,@RequestBody Handle b,HttpServletRequest r){service.handle(id,b.result(),b.remark(),uid(a));audit.operation(a,"business:after-sale:handle","AFTER_SALE",id,b.result(),r);return ApiResponse.ok();}
 private boolean blank(String value){return value==null||value.isBlank();}private long uid(Authentication a){return(Long)a.getPrincipal();}public record CreateOrder(Long skuId,int quantity,String contactName,String contactPhone,String customerRemark,String gameAccount,String gameNickname,String serverName,String rankName,String extraRequirement,Long requestedPlayerId,Long playerLevelId,Long customerGameProfileId,Long serverId,Long currentRankId,Long targetRankId){}public record Handle(String result,String remark){}public record Cancel(String reason){}
}
