package com.peiwan.platform.customer;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.peiwan.platform.settlement.SettlementService;import com.peiwan.platform.order.OrderMemberService;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.time.format.DateTimeFormatter;import java.util.*;
@Service public class CustomerOrderService{
 private final CustomerOrderDataMapper data;private final OrderMapper orders;private final PlayerMapper players;private final AfterSaleMapper afterSales;private final AfterSaleProofMapper proofs;private final AfterSaleLogMapper logs;private final OrderStatusLogMapper orderLogs;private final SettlementService settlementService;private final OrderMemberService orderMembers;private final com.peiwan.platform.serviceexception.ServiceExceptionService serviceExceptions;
 public CustomerOrderService(CustomerOrderDataMapper data,OrderMapper orders,PlayerMapper players,AfterSaleMapper afterSales,AfterSaleProofMapper proofs,AfterSaleLogMapper logs,OrderStatusLogMapper orderLogs,SettlementService settlementService,OrderMemberService orderMembers,com.peiwan.platform.serviceexception.ServiceExceptionService serviceExceptions){this.data=data;this.orders=orders;this.players=players;this.afterSales=afterSales;this.proofs=proofs;this.logs=logs;this.orderLogs=orderLogs;this.settlementService=settlementService;this.orderMembers=orderMembers;this.serviceExceptions=serviceExceptions;}
 @Scheduled(fixedDelay=60000) @Transactional public void expireDue(){if(!Boolean.TRUE.equals(data.autoCompleteEnabled()))return;for(var row:data.dueOrders())complete(((Number)row.get("id")).longValue(),null,"用户确认超时，系统自动完成");}
 public Map<String,Object> ownList(long userId,int current,int size,String status){expireDue();current=Math.max(1,current);size=Math.min(100,Math.max(1,size));var result=data.ownOrders(new Page<>(current,size),userId,statuses(status));return Map.of("records",result.getRecords().stream().map(this::view).toList(),"current",current,"size",size,"total",result.getTotal());}
 public Map<String,Long> ownSummary(long userId){expireDue();var result=new LinkedHashMap<String,Long>();for(var row:data.ownOrderCounts(userId))result.put(Objects.toString(row.get("order_status")),((Number)row.get("total")).longValue());return result;}
 public Map<String,Object> ownDetail(long uid,long id){expireDue();var row=data.ownDetail(id,uid);if(row==null)throw new IllegalArgumentException("订单不存在或不属于当前用户");var x=new LinkedHashMap<>(view(row));var members=orderMembers.members(id);x.put("memberCount",members.size());x.put("members",members);x.put("items",data.items(id).stream().map(this::itemView).toList());x.put("gameProfile",data.gameProfile(id));var f=data.fulfillment(id);if(f!=null){long fid=((Number)f.get("id")).longValue();var fv=new LinkedHashMap<>(f);fv.put("proofUrls",data.fulfillmentProofs(fid));x.put("fulfillment",fv);}x.put("serviceExceptions",serviceExceptions.orderRequests(id));x.put("afterSale",data.latestAfterSale(id));return x;}
 @Transactional public void confirm(long uid,long orderId){var o=own(orderId,uid);if(!"WAIT_CUSTOMER_CONFIRM".equals(o.orderStatus))throw new IllegalArgumentException("当前订单不能确认完成");if(activeAfterSale(orderId)>0)throw new IllegalArgumentException("订单存在进行中的售后，不能确认完成");complete(orderId,uid,"用户确认服务完成");}
 @Transactional public long createAfterSale(long uid,long orderId,AfterSaleCommand c){var o=own(orderId,uid);if(!Set.of("PENDING_CONFIRM","WAIT_CUSTOMER_CONFIRM").contains(o.orderStatus))throw new IllegalArgumentException("当前订单不能申请售后");if(c.description()==null||c.description().isBlank())throw new IllegalArgumentException("请填写问题说明");if(activeAfterSale(orderId)>0)throw new IllegalArgumentException("该订单已有进行中的售后");var a=new AfterSaleEntity();a.afterSaleNo="AS"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))+UUID.randomUUID().toString().substring(0,5).toUpperCase();a.orderId=orderId;a.customerId=uid;a.reasonType=blank(c.reasonType(),"OTHER");a.description=c.description();a.afterSaleStatus="PENDING";afterSales.insert(a);int i=0;for(String url:c.proofUrls()==null?List.<String>of():c.proofUrls())if(url!=null&&!url.isBlank()){var p=new AfterSaleProofEntity();p.afterSaleId=a.id;p.proofUrl=url;p.sortNo=i++;proofs.insert(p);}String from=o.orderStatus;o.orderStatus="AFTER_SALE";o.updatedAt=LocalDateTime.now();orders.updateById(o);logAfterSale(a.id,"CREATE",null,"PENDING",c.description(),uid);logOrder(orderId,from,"AFTER_SALE",uid,"用户提交售后");return a.id;}
 public Map<String,Object> adminList(int current,int size,String status){current=Math.max(1,current);size=Math.min(100,Math.max(1,size));var result=data.afterSales(new Page<>(current,size),status);return Map.of("records",result.getRecords(),"current",current,"size",size,"total",result.getTotal());}
 public Map<String,Object> adminDetail(long id){var row=data.afterSaleDetail(id);if(row==null)throw new IllegalArgumentException("售后不存在");var x=new LinkedHashMap<>(row);x.put("proofUrls",data.afterSaleProofs(id));x.put("logs",data.afterSaleLogs(id));return x;}
 @Transactional public void handle(long id,String result,String remark,long op){var a=afterSales.selectById(id);if(a==null)throw new IllegalArgumentException("售后不存在");if(!Set.of("PENDING","PROCESSING").contains(a.afterSaleStatus))throw new IllegalArgumentException("售后已处理");if(!Set.of("REJECT","RESERVICE","CLOSE").contains(result))throw new IllegalArgumentException("处理结果无效");var o=orders.selectById(a.orderId);if(o==null)throw new IllegalArgumentException("订单不存在");String from=a.afterSaleStatus;a.afterSaleStatus="CLOSED";a.resultType=result;a.resultRemark=remark;a.handledBy=op;a.handledAt=LocalDateTime.now();a.updatedAt=LocalDateTime.now();afterSales.updateById(a);if("REJECT".equals(result)){o.orderStatus="WAIT_CUSTOMER_CONFIRM";o.updatedAt=LocalDateTime.now();orders.updateById(o);}else if("RESERVICE".equals(result)){o.orderStatus="IN_SERVICE";o.updatedAt=LocalDateTime.now();orders.updateById(o);}else complete(o.id,op,"售后协商关闭并完成订单");logAfterSale(id,"HANDLE",from,"CLOSED",remark,op);}
 private void complete(long orderId,Long op,String reason){var o=orders.selectById(orderId);if(o==null)throw new IllegalArgumentException("订单不存在");var memberIds=orderMembers.activePlayerIds(orderId);o.orderStatus="COMPLETED";o.tradeStatus="COMPLETED";o.completedAt=LocalDateTime.now();if(op!=null)o.customerConfirmedAt=LocalDateTime.now();o.updatedAt=LocalDateTime.now();orders.updateById(o);orderMembers.updateStatuses(orderId,"COMPLETED");settlementService.settleOrder(orderId);for(var playerId:memberIds)if(data.activePlayerOrders(playerId)==0){var p=players.selectById(playerId);if(p!=null){p.workStatus="AVAILABLE";p.orderCount=(p.orderCount==null?0:p.orderCount)+1;p.updatedAt=LocalDateTime.now();players.updateById(p);}}logOrder(orderId,"WAIT_CUSTOMER_CONFIRM","COMPLETED",op,reason);}
 private OrderEntity own(long id,long uid){var o=orders.selectOwned(id,uid);if(o==null)throw new IllegalArgumentException("订单不存在或不属于当前用户");return o;}private long activeAfterSale(long id){return afterSales.selectCount(new QueryWrapper<AfterSaleEntity>().eq("order_id",id).in("after_sale_status","PENDING","PROCESSING"));}
 private void logOrder(long o,String from,String to,Long op,String reason){var l=new OrderStatusLogEntity();l.orderId=o;l.fromStatus=from;l.toStatus=to;l.operatorId=op;l.reason=reason;orderLogs.insert(l);}private void logAfterSale(long id,String action,String from,String to,String remark,Long op){var l=new AfterSaleLogEntity();l.afterSaleId=id;l.action=action;l.fromStatus=from;l.toStatus=to;l.remark=remark;l.operatorId=op;logs.insert(l);}private String blank(String v,String d){return v==null||v.isBlank()?d:v;}
 private List<String> statuses(String status){if(status==null||status.isBlank())return List.of();if("ACTIVE_SERVICE".equals(status))return List.of("ASSIGNED","IN_SERVICE");if("PENDING_CONFIRMATION".equals(status))return List.of("PENDING_CONFIRM","WAIT_CUSTOMER_CONFIRM");return List.of(status);}private Map<String,Object> itemView(Map<String,Object>r){var x=new LinkedHashMap<String,Object>();x.put("productName",r.get("product_name"));x.put("skuName",r.get("sku_name"));x.put("quantity",r.get("quantity"));x.put("unitPrice",r.get("unit_price"));x.put("serviceSnapshot",clobText(r.get("service_snapshot")));return x;}private String clobText(Object value){if(value==null)return null;if(value instanceof java.sql.Clob c)try{return c.getSubString(1,Math.toIntExact(c.length()));}catch(java.sql.SQLException e){throw new IllegalArgumentException("订单服务快照读取失败");}return value.toString();}private Map<String,Object> view(Map<String,Object>r){var x=new LinkedHashMap<String,Object>();String[][]k={{"id","id"},{"orderNo","order_no"},{"orderStatus","order_status"},{"playerName","player_name"},{"productName","product_name"},{"skuName","sku_name"},{"coverUrl","cover_url"},{"gameName","game_name"},{"requiredPlayerCount","required_player_count"},{"memberCount","member_count"},{"payableAmount","payable_amount"},{"customerConfirmDeadline","customer_confirm_deadline"},{"customerConfirmedAt","customer_confirmed_at"},{"createTime","created_at"}};for(var a:k)if(r.containsKey(a[1]))x.put(a[0],r.get(a[1]));return x;}public record AfterSaleCommand(String reasonType,String description,List<String>proofUrls){}
}
