package com.peiwan.platform.customer;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service public class CustomerGameProfileService{private final CustomerGameProfileMapper profiles;private final CustomerGameRankMapper profileRanks;private final GameMapper games;private final GameServerMapper servers;private final GameRankSystemMapper systems;private final GameRankMapper ranks;
 public CustomerGameProfileService(CustomerGameProfileMapper profiles,CustomerGameRankMapper profileRanks,GameMapper games,GameServerMapper servers,GameRankSystemMapper systems,GameRankMapper ranks){this.profiles=profiles;this.profileRanks=profileRanks;this.games=games;this.servers=servers;this.systems=systems;this.ranks=ranks;}
 public List<Map<String,Object>> list(long uid,Long gameId){var q=new QueryWrapper<CustomerGameProfileEntity>().eq("user_id",uid).eq("enabled",true);if(gameId!=null)q.eq("game_id",gameId);q.orderByDesc("is_default").orderByDesc("id");var saved=profiles.selectList(q).stream().map(this::view).toList();if(!saved.isEmpty()||gameId==null)return saved;var recent=profiles.latestOrderProfile(uid,gameId);return recent==null?List.of():List.of(historyView(recent));}
 @Transactional public long save(Long id,long uid,Command c){if(c.gameId()==null||games.selectById(c.gameId())==null)throw new IllegalArgumentException("请选择有效游戏");if(c.gameAccount()==null||c.gameAccount().isBlank()||c.gameNickname()==null||c.gameNickname().isBlank())throw new IllegalArgumentException("游戏账号和昵称不能为空");if(c.serverId()!=null){var server=servers.selectById(c.serverId());if(server==null||!Objects.equals(server.gameId,c.gameId()))throw new IllegalArgumentException("区服与游戏不匹配");}try{var x=id==null?new CustomerGameProfileEntity():required(id,uid);x.userId=uid;x.gameId=c.gameId();x.serverId=c.serverId();x.gameAccount=c.gameAccount().trim();x.gameNickname=c.gameNickname().trim();x.isDefault=c.isDefault();x.enabled=true;x.updatedAt=LocalDateTime.now();if(Boolean.TRUE.equals(c.isDefault()))profiles.update(null,new UpdateWrapper<CustomerGameProfileEntity>().set("is_default",false).eq("user_id",uid).eq("game_id",c.gameId()));if(id==null)profiles.insert(x);else profiles.updateById(x);profileRanks.delete(new QueryWrapper<CustomerGameRankEntity>().eq("profile_id",x.id));for(var item:c.ranks()==null?List.<RankSelection>of():c.ranks()){var system=systems.selectById(item.rankSystemId());var rank=ranks.selectById(item.rankId());if(system==null||rank==null||!Objects.equals(system.gameId,c.gameId())||!Objects.equals(rank.rankSystemId,system.id))throw new IllegalArgumentException("段位与游戏或段位体系不匹配");var relation=new CustomerGameRankEntity();relation.profileId=x.id;relation.rankSystemId=system.id;relation.rankId=rank.id;profileRanks.insert(relation);}return x.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("该游戏账号已保存");}}
 @Transactional public void delete(long id,long uid){required(id,uid);profileRanks.delete(new QueryWrapper<CustomerGameRankEntity>().eq("profile_id",id));profiles.deleteById(id);}
 private CustomerGameProfileEntity required(long id,long uid){var x=profiles.selectOne(new QueryWrapper<CustomerGameProfileEntity>().eq("id",id).eq("user_id",uid));if(x==null)throw new IllegalArgumentException("游戏账号不存在");return x;}
 private Map<String,Object> view(CustomerGameProfileEntity x){var out=new LinkedHashMap<String,Object>();var game=games.selectById(x.gameId);var server=x.serverId==null?null:servers.selectById(x.serverId);out.put("id",x.id);out.put("gameId",x.gameId);out.put("gameName",game==null?"已删除游戏":game.gameName);out.put("serverId",x.serverId);out.put("serverName",server==null?null:server.serverName);out.put("gameAccount",x.gameAccount);out.put("gameNickname",x.gameNickname);out.put("isDefault",x.isDefault);var values=new ArrayList<Map<String,Object>>();for(var rel:profileRanks.selectList(new QueryWrapper<CustomerGameRankEntity>().eq("profile_id",x.id))){var system=systems.selectById(rel.rankSystemId);var rank=ranks.selectById(rel.rankId);if(system!=null&&rank!=null)values.add(Map.of("rankSystemId",system.id,"rankSystemName",system.systemName,"rankId",rank.id,"rankName",rank.rankName));}out.put("ranks",values);return out;}
 private Map<String,Object> historyView(Map<String,Object> row){var out=new LinkedHashMap<String,Object>();out.put("gameId",row.get("game_id"));out.put("gameName",row.get("game_name"));out.put("serverId",row.get("server_id"));out.put("serverName",row.get("server_name"));out.put("gameAccount",row.get("game_account"));out.put("gameNickname",row.get("game_nickname"));out.put("currentRankId",row.get("current_rank_id"));out.put("currentRankName",row.get("current_rank_name")!=null?row.get("current_rank_name"):row.get("rank_name"));out.put("contactName",row.get("contact_name"));out.put("contactPhone",row.get("contact_phone"));out.put("isDefault",true);out.put("history",true);out.put("ranks",List.of());return out;}
 public record Command(Long gameId,Long serverId,String gameAccount,String gameNickname,boolean isDefault,List<RankSelection>ranks){}public record RankSelection(long rankSystemId,long rankId){}
}
