<template>
  <div class="art-full-height" v-loading="loading">
    <ElResult v-if="identityProblem" icon="info" title="暂时无法查看收益" :sub-title="identityProblem"><template #extra><ElButton type="primary" @click="load">重新检查</ElButton></template></ElResult>
    <template v-else>
      <ElRow :gutter="16" class="mb-4">
        <ElCol v-for="item in cards" :key="item.label" :xs="12" :sm="6"><ElCard shadow="never" class="balance-card"><div class="card-label">{{item.label}}</div><div class="card-value">¥ {{money(item.value)}}</div></ElCard></ElCol>
      </ElRow>
      <ElAlert class="mb-4" :closable="false" type="info" show-icon :title="ruleText"/>
      <ElCard shadow="never">
        <div class="toolbar"><ElTabs v-model="tab" @tab-change="loadTable"><ElTabPane label="收入明细" name="earning"/><ElTabPane label="提现记录" name="withdrawal"/></ElTabs><ElButton v-auth="'player:withdraw:create'" type="primary" :disabled="!summary?.canWithdrawToday" @click="openWithdraw">申请提现</ElButton></div>
        <ElTable v-if="tab==='earning'" :data="rows" empty-text="暂无收入明细"><ElTableColumn prop="earningNo" label="收入单号" min-width="190"/><ElTableColumn prop="orderId" label="订单 ID" width="100"/><ElTableColumn prop="orderAmount" label="订单金额" width="120"><template #default="{row}">¥ {{money(row.orderAmount)}}</template></ElTableColumn><ElTableColumn prop="commissionRate" label="平台抽佣" width="110"><template #default="{row}">{{percent(row.commissionRate)}}</template></ElTableColumn><ElTableColumn prop="commissionAmount" label="平台佣金" width="120"><template #default="{row}">¥ {{money(row.commissionAmount)}}</template></ElTableColumn><ElTableColumn prop="playerAmount" label="我的收入" width="120"><template #default="{row}"><span class="income">+ ¥ {{money(row.playerAmount)}}</span></template></ElTableColumn><ElTableColumn label="入账时间" width="180"><template #default="{row}">{{formatDateTime(row.settledAt)}}</template></ElTableColumn></ElTable>
        <ElTable v-else :data="rows" empty-text="暂无提现记录"><ElTableColumn prop="withdrawalNo" label="提现单号" min-width="190"/><ElTableColumn prop="amount" label="提现金额" width="130"><template #default="{row}">¥ {{money(row.amount)}}</template></ElTableColumn><ElTableColumn prop="payoutMethod" label="收款方式" width="110"/><ElTableColumn prop="accountName" label="收款人" width="120"/><ElTableColumn prop="accountNo" label="收款账号" min-width="180"><template #default="{row}">{{mask(row.accountNo)}}</template></ElTableColumn><ElTableColumn label="状态" width="100"><template #default="{row}"><ElTag :type="withdrawType(row.withdrawalStatus)">{{withdrawText(row.withdrawalStatus)}}</ElTag></template></ElTableColumn><ElTableColumn prop="reviewRemark" label="审核说明" min-width="160" show-overflow-tooltip/><ElTableColumn label="申请时间" width="180"><template #default="{row}">{{formatDateTime(row.createdAt)}}</template></ElTableColumn></ElTable>
        <div class="pagination"><ElPagination v-model:current-page="query.current" v-model:page-size="query.size" :total="total" layout="total, prev, pager, next" @change="loadTable"/></div>
      </ElCard>
    </template>
    <ElDialog v-model="visible" title="申请提现" width="520px" destroy-on-close><ElAlert class="mb-4" type="warning" :closable="false" :title="`仅每周一可申请，单次最低 ¥ ${money(summary?.minWithdrawAmount)}`"/><ElForm label-width="90px"><ElFormItem label="提现金额" required><ElInputNumber v-model="form.amount" :min="Number(summary?.minWithdrawAmount||300)" :max="Number(summary?.account?.availableBalance||0)" :precision="2" class="!w-full"/></ElFormItem><ElFormItem label="收款方式" required><ElSelect v-model="form.payoutMethod" class="!w-full"><ElOption label="银行卡" value="BANK"/><ElOption label="支付宝" value="ALIPAY"/><ElOption label="微信" value="WECHAT"/></ElSelect></ElFormItem><ElFormItem label="收款人" required><ElInput v-model="form.accountName" maxlength="64"/></ElFormItem><ElFormItem label="收款账号" required><ElInput v-model="form.accountNo" maxlength="128"/></ElFormItem></ElForm><template #footer><ElButton @click="visible=false">取消</ElButton><ElButton type="primary" :loading="saving" @click="submit">提交审核</ElButton></template></ElDialog>
  </div>
</template>
<script setup lang="ts">
import{fetchPlayerSettlement,fetchPlayerEarnings,fetchPlayerWithdrawals,createPlayerWithdrawal}from'@/api/business-manage';import{HttpError}from'@/utils/http/error';import{formatDateTime}from'@/utils/date'
const loading=ref(false),saving=ref(false),summary=ref<any>(),identityProblem=ref(''),tab=ref('earning'),rows=ref<any[]>([]),total=ref(0),visible=ref(false),query=reactive({current:1,size:20}),form=reactive({amount:300,payoutMethod:'BANK',accountName:'',accountNo:''})
const cards=computed(()=>[{label:'可提现余额',value:summary.value?.account?.availableBalance},{label:'提现冻结',value:summary.value?.account?.frozenBalance},{label:'累计收入',value:summary.value?.account?.totalIncome},{label:'累计提现',value:summary.value?.account?.totalWithdrawn}]);const ruleText=computed(()=>`平台抽佣 ${percent(summary.value?.commissionRate)}，陪玩师实得 ${percent(summary.value?.playerRate)}；每周一可申请提现，单次最低 ¥ ${money(summary.value?.minWithdrawAmount)}。`)
async function load(){loading.value=true;identityProblem.value='';try{summary.value=await fetchPlayerSettlement();await loadTable()}catch(e){if(e instanceof HttpError&&e.message.includes('陪玩师'))identityProblem.value=e.message;else throw e}finally{loading.value=false}}
async function loadTable(){query.current=1;const d=tab.value==='earning'?await fetchPlayerEarnings(query):await fetchPlayerWithdrawals(query);rows.value=d.records;total.value=d.total}
function openWithdraw(){Object.assign(form,{amount:Number(summary.value?.minWithdrawAmount||300),payoutMethod:'BANK',accountName:'',accountNo:''});visible.value=true}
async function submit(){if(!form.accountName.trim()||!form.accountNo.trim())return ElMessage.warning('请完整填写收款信息');saving.value=true;try{await createPlayerWithdrawal(form);ElMessage.success('提现申请已提交，等待后台审核');visible.value=false;tab.value='withdrawal';await load()}finally{saving.value=false}}
const money=(v:any)=>Number(v||0).toFixed(2),percent=(v:any)=>`${(Number(v||0)*100).toFixed(0)}%`,mask=(v:string)=>v&&v.length>8?`${v.slice(0,4)}****${v.slice(-4)}`:v||'-',withdrawText=(s:string)=>({PENDING:'待审核',PAID:'已打款',REJECTED:'已驳回'}[s]||s),withdrawType=(s:string)=>(s==='PAID'?'success':s==='REJECTED'?'danger':'warning') as any
onMounted(load)
</script>
<style scoped>.balance-card{min-height:112px}.card-label{color:var(--el-text-color-secondary);font-size:14px}.card-value{font-size:27px;font-weight:600;margin-top:16px}.toolbar{display:flex;align-items:center;justify-content:space-between}.toolbar :deep(.el-tabs__header){margin-bottom:12px}.pagination{display:flex;justify-content:flex-end;margin-top:18px}.income{color:var(--el-color-success);font-weight:600}</style>
