package com.peiwan.platform.serviceexception;
import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController public class ServiceExceptionController{private final ServiceExceptionService service;private final AuditService audit;public ServiceExceptionController(ServiceExceptionService service,AuditService audit){this.service=service;this.audit=audit;}
 @PreAuthorize("hasAuthority('customer:order:detail')")@PostMapping("/api/customer/orders/{id}/service-exceptions")public ApiResponse<?> customerCreate(Authentication a,@PathVariable long id,@RequestBody ServiceExceptionService.Command b,HttpServletRequest r){long rid=service.createByCustomer(uid(a),id,b);audit.operation(a,"customer:service-exception:create","SERVICE_EXCEPTION",rid,b.requestType(),r);return ApiResponse.ok(Map.of("id",rid));}
 @PreAuthorize("hasAuthority('player:order:detail')")@PostMapping("/api/player/orders/{id}/service-exceptions")public ApiResponse<?> playerCreate(Authentication a,@PathVariable long id,@RequestBody ServiceExceptionService.Command b,HttpServletRequest r){long rid=service.createByPlayer(uid(a),id,b);audit.operation(a,"player:service-exception:create","SERVICE_EXCEPTION",rid,b.requestType(),r);return ApiResponse.ok(Map.of("id",rid));}
 @PreAuthorize("hasAuthority('player:dispatch:list')")@GetMapping("/api/player/service-transfers/pending")public ApiResponse<?> pending(Authentication a){return ApiResponse.ok(service.pendingTransfers(uid(a)));}
 @PreAuthorize("hasAuthority('customer:order:detail') or hasAuthority('player:order:detail')")@GetMapping("/api/service-orders/{id}/transfer-targets")public ApiResponse<?> targets(Authentication a,@PathVariable long id,@RequestParam(required=false)Long sourceOrderMemberId){return ApiResponse.ok(service.eligibleTargets(uid(a),id,sourceOrderMemberId));}
 @PreAuthorize("hasAuthority('player:dispatch:accept')")@PutMapping("/api/player/service-transfers/{id}/respond")public ApiResponse<?> respond(Authentication a,@PathVariable long id,@RequestBody Respond b,HttpServletRequest r){service.respond(uid(a),id,b.action());audit.operation(a,"player:service-transfer:respond","SERVICE_EXCEPTION",id,b.action(),r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:service-exception:list') or hasRole('admin')")@GetMapping("/api/business/service-exceptions")public ApiResponse<?> list(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String status,@RequestParam(required=false)String type){return ApiResponse.ok(service.list(current,size,status,type));}
 @PreAuthorize("hasAuthority('business:service-exception:review') or hasRole('admin')")@PutMapping("/api/business/service-exceptions/{id}/review")public ApiResponse<?> review(Authentication a,@PathVariable long id,@RequestBody Review b,HttpServletRequest r){service.review(id,b.action(),b.remark(),uid(a));audit.operation(a,"business:service-exception:review","SERVICE_EXCEPTION",id,b.action(),r);return ApiResponse.ok();}
 private long uid(Authentication a){return(Long)a.getPrincipal();}public record Review(String action,String remark){}public record Respond(String action){}
}
