package com.peiwan.platform.serviceexception;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;
@Service public class ServiceLiabilityService{
 private static final BigDecimal TRANSFER_RATE=new BigDecimal("0.1600"),ABORT_RATE=new BigDecimal("0.2000");
 private final ServiceLiabilityMapper liabilities;private final ServicePenaltyLedgerMapper ledgers;private final ServiceLiabilityDataMapper data;private final PlayerAccountMapper accounts;private final PlayerAccountTransactionMapper accountTransactions;private final PlatformLedgerMapper platformLedgers;
 public ServiceLiabilityService(ServiceLiabilityMapper liabilities,ServicePenaltyLedgerMapper ledgers,ServiceLiabilityDataMapper data,PlayerAccountMapper accounts,PlayerAccountTransactionMapper accountTransactions,PlatformLedgerMapper platformLedgers){this.liabilities=liabilities;this.ledgers=ledgers;this.data=data;this.accounts=accounts;this.accountTransactions=accountTransactions;this.platformLedgers=platformLedgers;}
 @Transactional public void settleTransferCompensations(long orderId){if(data.liabilityCount(orderId,"TRANSFER_COMPENSATION")>0)return;var links=data.transferLinks(orderId);if(links.isEmpty())return;BigDecimal base=base(orderId),amount=base.multiply(TRANSFER_RATE).setScale(2,RoundingMode.HALF_UP);var previous=new HashMap<Long,Long>();for(var link:links){long from=n(link,"from_order_member_id"),to=n(link,"to_order_member_id");if(previous.put(to,from)!=null)throw new IllegalStateException("转单成员存在多个来源");}for(var link:links){long liableMember=n(link,"from_order_member_id"),root=rootOf(liableMember,previous);long liablePlayer=n(link,"from_player_id");var liability=create(orderId,n(link,"exception_request_id"),"TRANSFER_COMPENSATION",root,liableMember,null,liablePlayer,null,base,TRANSFER_RATE,amount,null,"成功结单：转出成员按基础单价16%承担责任，款项计入平台");debitToPlatform(liability,liablePlayer,"TRANSFER_COMPENSATION",amount,"转单责任扣款，允许形成待偿负余额","SERVICE_TRANSFER_PENALTY","转出成员16%责任扣款");}}
 @Transactional public void settleAbortPenalties(long orderId,long requestId,long operator){if(data.liabilityCount(orderId,"ABORT_PENALTY")>0)return;BigDecimal base=base(orderId),amount=base.multiply(ABORT_RATE).setScale(2,RoundingMode.HALF_UP);for(var member:data.activeMembers(orderId)){long memberId=n(member,"id"),playerId=n(member,"player_id");var liability=create(orderId,requestId,"ABORT_PENALTY",null,memberId,null,playerId,null,base,ABORT_RATE,amount,operator,"炸单审核通过：最终在役成员按基础单价20%承担");var account=lock(playerId);BigDecimal before=money(account.get("available_balance")),after=before.subtract(amount);data.debit(n(account,"id"),amount);accountTx(n(account,"id"),playerId,"OUT","ABORT_PENALTY",liability.liabilityNo,amount,before,after,"炸单责任扣款，允许形成待偿负余额");ledger(liability,playerId,null,"ABORT_PENALTY","OUT",amount,before,after);var platform=new PlatformLedgerEntity();platform.ledgerNo=no("PL");platform.orderId=orderId;platform.businessType="SERVICE_ABORT_PENALTY";platform.direction="IN";platform.amount=amount;platform.remark="最终在役成员炸单责任扣款";platformLedgers.insert(platform);}}
 private ServiceLiabilityEntity create(long orderId,Long requestId,String type,Long rootMember,long liableMember,Long beneficiaryMember,long liablePlayer,Long beneficiaryPlayer,BigDecimal base,BigDecimal rate,BigDecimal amount,Long operator,String remark){var x=new ServiceLiabilityEntity();x.liabilityNo=no("LIA");x.orderId=orderId;x.exceptionRequestId=requestId;x.liabilityType=type;x.rootOrderMemberId=rootMember;x.liableOrderMemberId=liableMember;x.beneficiaryOrderMemberId=beneficiaryMember;x.liablePlayerId=liablePlayer;x.beneficiaryPlayerId=beneficiaryPlayer;x.calculationBase=base;x.rate=rate;x.amount=amount;x.liabilityStatus="SETTLED";x.determinedBy=operator;x.determinedAt=LocalDateTime.now();x.remark=remark;liabilities.insert(x);return x;}
 private void debitToPlatform(ServiceLiabilityEntity liability,long playerId,String type,BigDecimal amount,String accountRemark,String platformType,String platformRemark){var account=lock(playerId);BigDecimal before=money(account.get("available_balance")),after=before.subtract(amount);data.debit(n(account,"id"),amount);accountTx(n(account,"id"),playerId,"OUT",type,liability.liabilityNo,amount,before,after,accountRemark);ledger(liability,playerId,null,type,"OUT",amount,before,after);var platform=new PlatformLedgerEntity();platform.ledgerNo=no("PL");platform.orderId=liability.orderId;platform.businessType=platformType;platform.direction="IN";platform.amount=amount;platform.remark=platformRemark;platformLedgers.insert(platform);}
 private long rootOf(long memberId,Map<Long,Long> previous){long current=memberId;var seen=new HashSet<Long>();while(previous.containsKey(current)){if(!seen.add(current))throw new IllegalStateException("转单链存在循环");current=previous.get(current);}return current;}
 private Map<String,Object> lock(long playerId){ensureAccount(playerId);return data.lockAccount(playerId);}private void ensureAccount(long playerId){if(accounts.selectCount(new QueryWrapper<PlayerAccountEntity>().eq("player_id",playerId))>0)return;try{var a=new PlayerAccountEntity();a.playerId=playerId;a.availableBalance=BigDecimal.ZERO;a.frozenBalance=BigDecimal.ZERO;a.totalIncome=BigDecimal.ZERO;a.totalWithdrawn=BigDecimal.ZERO;a.version=0L;accounts.insert(a);}catch(DuplicateKeyException ignored){}}
 private void accountTx(long accountId,long playerId,String direction,String type,String businessNo,BigDecimal amount,BigDecimal before,BigDecimal after,String remark){var t=new PlayerAccountTransactionEntity();t.transactionNo=no("ST");t.accountId=accountId;t.playerId=playerId;t.balanceType="AVAILABLE";t.direction=direction;t.businessType=type;t.businessNo=businessNo;t.amount=amount;t.balanceBefore=before;t.balanceAfter=after;t.remark=remark;accountTransactions.insert(t);}private void ledger(ServiceLiabilityEntity liability,long playerId,Long counterparty,String type,String direction,BigDecimal amount,BigDecimal before,BigDecimal after){var x=new ServicePenaltyLedgerEntity();x.ledgerNo=no("SPL");x.liabilityId=liability.id;x.orderId=liability.orderId;x.playerId=playerId;x.counterpartyPlayerId=counterparty;x.entryType=type;x.direction=direction;x.amount=amount;x.balanceBefore=before;x.balanceAfter=after;ledgers.insert(x);}private BigDecimal base(long orderId){BigDecimal x=data.baseUnitPrice(orderId);if(x==null||x.signum()<0)throw new IllegalArgumentException("订单基础单价无效，无法计算责任金额");return x.setScale(2,RoundingMode.HALF_UP);}private long n(Map<String,Object>x,String k){return ((Number)x.get(k)).longValue();}private BigDecimal money(Object x){return (BigDecimal)x;}private String no(String p){return p+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))+UUID.randomUUID().toString().replace("-","").substring(0,6).toUpperCase();}
}
