create table pw_order (id bigint generated by default as identity primary key, order_no varchar(40) not null unique, customer_id bigint not null, assigned_player_id bigint, order_status varchar(32) not null, total_amount decimal(12,2) not null, payable_amount decimal(12,2) not null, paid_amount decimal(12,2) not null default 0, contact_name varchar(64), contact_phone varchar(32), customer_remark varchar(1000), cancel_reason varchar(500), paid_at timestamp, assigned_at timestamp, service_started_at timestamp, completed_at timestamp, cancelled_at timestamp, created_by bigint, created_at timestamp not null default current_timestamp, updated_at timestamp not null default current_timestamp);
create index ix_pw_order_customer on pw_order(customer_id);
create index ix_pw_order_status on pw_order(order_status);
create index ix_pw_order_player on pw_order(assigned_player_id);

create table pw_order_item (id bigint generated by default as identity primary key, order_id bigint not null, product_id bigint not null, sku_id bigint not null, product_code varchar(64) not null, product_name varchar(128) not null, sku_code varchar(64) not null, sku_name varchar(128) not null, product_type varchar(32) not null, unit_price decimal(12,2) not null, quantity integer not null, subtotal_amount decimal(12,2) not null, service_snapshot clob, created_at timestamp not null default current_timestamp);
create index ix_pw_order_item_order on pw_order_item(order_id);

create table pw_order_game_profile (id bigint generated by default as identity primary key, order_id bigint not null, game_id bigint not null, game_name varchar(64) not null, game_account varchar(128), game_nickname varchar(128), server_name varchar(128), rank_name varchar(128), extra_requirement varchar(1000), created_at timestamp not null default current_timestamp);
create index ix_pw_order_profile_order on pw_order_game_profile(order_id);

create table pw_order_status_log (id bigint generated by default as identity primary key, order_id bigint not null, from_status varchar(32), to_status varchar(32) not null, operator_id bigint, reason varchar(500), created_at timestamp not null default current_timestamp);
create index ix_pw_order_status_log_order on pw_order_status_log(order_id);

insert into sys_menu(parent_id,type,name,path,component,title,icon,sort_no) select id,'MENU','OrderManage','order-manage','/business/order-manage','订单管理','ri:file-list-3-line',7 from sys_menu where name='Business' and not exists(select 1 from sys_menu where name='OrderManage');
insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no) select p.id,'BUTTON',concat(p.name,a.suffix),a.title,a.mark,a.sort_no from sys_menu p join (
 select 'List' suffix,'查询订单' title,'business:order:list' mark,1 sort_no union all
 select 'Create','创建订单','business:order:create',2 union all
 select 'Status','订单状态流转','business:order:status',3 union all
 select 'Assign','订单派单','business:order:assign',4
) a on 1=1 where p.name='OrderManage' and not exists(select 1 from sys_menu m where m.auth_mark=a.mark);
insert into sys_role_menu(role_id,menu_id) select r.id,m.id from sys_role r cross join sys_menu m where r.code='admin' and not exists(select 1 from sys_role_menu x where x.role_id=r.id and x.menu_id=m.id);

insert into pw_order(order_no,customer_id,order_status,total_amount,payable_amount,paid_amount,contact_name,contact_phone,customer_remark,created_by)
select 'ORD-DEMO-0001',u.id,'WAIT_ASSIGN',k.price,k.price,k.price,u.nickname,u.phone,'三角洲体验订单',u.id from sys_user u join pw_product p on p.product_code='delta-escort-experience' join pw_product_sku k on k.product_id=p.id and k.sku_code='delta-escort-1game' where u.username='admin' and not exists(select 1 from pw_order where order_no='ORD-DEMO-0001');
insert into pw_order_item(order_id,product_id,sku_id,product_code,product_name,sku_code,sku_name,product_type,unit_price,quantity,subtotal_amount,service_snapshot)
select o.id,p.id,k.id,p.product_code,p.product_name,k.sku_code,k.sku_name,p.product_type,k.price,1,k.price,'[{"serviceName":"烽火地带护航","quantity":1,"unitType":"GAME"}]' from pw_order o join pw_product p on p.product_code='delta-escort-experience' join pw_product_sku k on k.product_id=p.id and k.sku_code='delta-escort-1game' where o.order_no='ORD-DEMO-0001' and not exists(select 1 from pw_order_item i where i.order_id=o.id);
insert into pw_order_game_profile(order_id,game_id,game_name,game_account,game_nickname,server_name,extra_requirement) select o.id,g.id,g.game_name,'demo-account','测试玩家','烽火地带','优先保证安全撤离' from pw_order o join pw_game g on g.game_code='delta-force' where o.order_no='ORD-DEMO-0001' and not exists(select 1 from pw_order_game_profile x where x.order_id=o.id);
insert into pw_order_status_log(order_id,from_status,to_status,reason) select id,null,'PENDING_PAYMENT','创建订单' from pw_order o where order_no='ORD-DEMO-0001' and not exists(select 1 from pw_order_status_log x where x.order_id=o.id and x.to_status='PENDING_PAYMENT');
insert into pw_order_status_log(order_id,from_status,to_status,reason) select id,'PENDING_PAYMENT','WAIT_ASSIGN','模拟支付完成' from pw_order o where order_no='ORD-DEMO-0001' and not exists(select 1 from pw_order_status_log x where x.order_id=o.id and x.to_status='WAIT_ASSIGN');
