create table pw_dispatch_rule (id bigint generated by default as identity primary key, rule_name varchar(64) not null, grab_minutes integer not null default 10, max_candidates integer not null default 10, allow_busy boolean not null default false, max_active_orders integer not null default 1, allow_reoffer_after_reject boolean not null default false, enabled boolean not null default true, updated_at timestamp not null default current_timestamp);
insert into pw_dispatch_rule(rule_name,grab_minutes,max_candidates,allow_busy,max_active_orders,allow_reoffer_after_reject,enabled) select '默认派单规则',10,10,false,1,false,true where not exists(select 1 from pw_dispatch_rule);

create table pw_dispatch_task (id bigint generated by default as identity primary key, task_no varchar(40) not null unique, order_id bigint not null, dispatch_mode varchar(16) not null, task_status varchar(24) not null, target_player_id bigint, accepted_player_id bigint, attempt_no integer not null default 1, candidate_count integer not null default 0, deadline_at timestamp not null, created_by bigint, created_at timestamp not null default current_timestamp, accepted_at timestamp, cancelled_at timestamp, updated_at timestamp not null default current_timestamp);
create index ix_pw_dispatch_task_order on pw_dispatch_task(order_id);
create index ix_pw_dispatch_task_status on pw_dispatch_task(task_status);

create table pw_dispatch_candidate (id bigint generated by default as identity primary key, task_id bigint not null, player_id bigint not null, match_score decimal(8,2) not null default 0, active_order_count integer not null default 0, candidate_status varchar(24) not null default 'PENDING', notified boolean not null default false, responded_at timestamp, reject_reason varchar(500), created_at timestamp not null default current_timestamp, unique(task_id,player_id));
create index ix_pw_dispatch_candidate_task on pw_dispatch_candidate(task_id);

create table pw_dispatch_action_log (id bigint generated by default as identity primary key, task_id bigint not null, order_id bigint not null, player_id bigint, action_type varchar(24) not null, from_status varchar(24), to_status varchar(24), operator_id bigint, reason varchar(500), created_at timestamp not null default current_timestamp);
create index ix_pw_dispatch_action_task on pw_dispatch_action_log(task_id);

insert into sys_menu(parent_id,type,name,path,component,title,icon,sort_no) select id,'MENU','DispatchManage','dispatch-manage','/business/dispatch-manage','派单任务','ri:route-line',8 from sys_menu where name='Business' and not exists(select 1 from sys_menu where name='DispatchManage');
insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no) select p.id,'BUTTON',concat(p.name,a.suffix),a.title,a.mark,a.sort_no from sys_menu p join (
 select 'List' suffix,'查询派单任务' title,'business:dispatch:list' mark,1 sort_no union all
 select 'Create','发起或重新派单','business:dispatch:create',2 union all
 select 'Respond','模拟接受或拒绝','business:dispatch:respond',3 union all
 select 'Cancel','取消派单任务','business:dispatch:cancel',4
) a on 1=1 where p.name='DispatchManage' and not exists(select 1 from sys_menu m where m.auth_mark=a.mark);
insert into sys_role_menu(role_id,menu_id) select r.id,m.id from sys_role r cross join sys_menu m where r.code='admin' and not exists(select 1 from sys_role_menu x where x.role_id=r.id and x.menu_id=m.id);
