-- 为超级管理员准备可直接体验工作台的陪玩师身份；已有绑定时复用原档案。
insert into pw_player(player_no,user_id,nickname,real_name,gender,phone,introduction,audit_status,work_status,enabled,audit_remark,approved_at,rating_score,rating_count,order_count,max_active_orders,sort_no,remark,created_by,updated_by)
select 'DEMO-ADMIN-PLAYER',u.id,'凌竞队长','平台管理员','UNKNOWN','19000000999','三角洲行动与无畏契约双游陪玩师，用于工作台和履约流程演示。','APPROVED','BUSY',true,'演示数据自动审核通过',current_timestamp,4.98,128,256,3,0,'V15 超级管理员演示陪玩师',u.id,u.id
from sys_user u where u.username='admin' and not exists(select 1 from pw_player p where p.user_id=u.id);
update pw_player set max_active_orders=3,audit_status='APPROVED',enabled=true where user_id=(select id from sys_user where username='admin');

insert into pw_player_game(player_id,game_id,game_nickname,server_name,rank_name,experience_years,introduction,is_primary,audit_status,enabled)
select p.id,g.id,'LingJing-Delta','国服','烽火地带黑鹰',3,'熟悉烽火护航、撤离路线和全面战场指挥',true,'APPROVED',true from pw_player p join sys_user u on u.id=p.user_id cross join pw_game g where u.username='admin' and g.game_code='delta-force' and not exists(select 1 from pw_player_game x where x.player_id=p.id and x.game_id=g.id);
insert into pw_player_game(player_id,game_id,game_nickname,server_name,rank_name,experience_years,introduction,is_primary,audit_status,enabled)
select p.id,g.id,'LingJing-V','国服','神话',4,'主玩控场和先锋，支持排位与道具教学',false,'APPROVED',true from pw_player p join sys_user u on u.id=p.user_id cross join pw_game g where u.username='admin' and g.game_code='valorant' and not exists(select 1 from pw_player_game x where x.player_id=p.id and x.game_id=g.id);
insert into pw_player_tag_rel(player_id,tag_id) select p.id,t.id from pw_player p join sys_user u on u.id=p.user_id cross join pw_player_tag t where u.username='admin' and t.tag_code in('aim-strong','good-command','patient') and not exists(select 1 from pw_player_tag_rel x where x.player_id=p.id and x.tag_id=t.id);

-- 已接单：用于测试“开始服务”。
insert into pw_order(order_no,customer_id,assigned_player_id,order_status,total_amount,payable_amount,paid_amount,contact_name,contact_phone,customer_remark,paid_at,assigned_at,created_by)
select 'ORD-ADMIN-DEMO-ASSIGNED',u.id,p.id,'ASSIGNED',99,99,99,u.nickname,u.phone,'演示：等待陪玩师开始服务',current_timestamp,current_timestamp,u.id from sys_user u join pw_player p on p.user_id=u.id where u.username='admin' and not exists(select 1 from pw_order where order_no='ORD-ADMIN-DEMO-ASSIGNED');
insert into pw_order_item(order_id,product_id,sku_id,product_code,product_name,sku_code,sku_name,product_type,unit_price,quantity,subtotal_amount,service_snapshot)
select o.id,p.id,k.id,p.product_code,p.product_name,k.sku_code,k.sku_name,p.product_type,99,1,99,'[{"serviceName":"烽火地带护航","quantity":1,"unitType":"GAME"}]' from pw_order o join pw_product p on p.product_code='delta-escort-experience' join pw_product_sku k on k.sku_code='delta-escort-1game' where o.order_no='ORD-ADMIN-DEMO-ASSIGNED';
insert into pw_order_game_profile(order_id,game_id,game_name,game_account,game_nickname,server_name,rank_name,extra_requirement) select o.id,g.id,g.game_name,'admin-demo-delta','演示客户A','烽火地带','钻石','安全撤离并讲解路线' from pw_order o join pw_game g on g.game_code='delta-force' where o.order_no='ORD-ADMIN-DEMO-ASSIGNED';
insert into pw_order_status_log(order_id,from_status,to_status,operator_id,reason) select o.id,'WAIT_ASSIGN','ASSIGNED',u.id,'V15 演示派单完成' from pw_order o join sys_user u on u.username='admin' where o.order_no='ORD-ADMIN-DEMO-ASSIGNED';

-- 服务中：用于测试“提交完成凭证”。
insert into pw_order(order_no,customer_id,assigned_player_id,order_status,total_amount,payable_amount,paid_amount,contact_name,contact_phone,customer_remark,paid_at,assigned_at,service_started_at,created_by)
select 'ORD-ADMIN-DEMO-SERVICE',u.id,p.id,'IN_SERVICE',116,116,116,u.nickname,u.phone,'演示：无畏契约排位服务中',current_timestamp,current_timestamp,current_timestamp,u.id from sys_user u join pw_player p on p.user_id=u.id where u.username='admin' and not exists(select 1 from pw_order where order_no='ORD-ADMIN-DEMO-SERVICE');
insert into pw_order_item(order_id,product_id,sku_id,product_code,product_name,sku_code,sku_name,product_type,unit_price,quantity,subtotal_amount,service_snapshot)
select o.id,p.id,k.id,p.product_code,p.product_name,k.sku_code,k.sku_name,p.product_type,58,2,116,'[{"serviceName":"无畏契约排位陪玩","quantity":2,"unitType":"HOUR"}]' from pw_order o join pw_product p on p.product_code='valorant-ranked-hour' join pw_product_sku k on k.sku_code='valorant-ranked-1h' where o.order_no='ORD-ADMIN-DEMO-SERVICE';
insert into pw_order_game_profile(order_id,game_id,game_name,game_account,game_nickname,server_name,rank_name,extra_requirement) select o.id,g.id,g.game_name,'admin-demo-valorant','演示客户B','国服','钻石','主玩烟位，沟通教学' from pw_order o join pw_game g on g.game_code='valorant' where o.order_no='ORD-ADMIN-DEMO-SERVICE';
insert into pw_fulfillment(order_id,player_id,fulfillment_status) select o.id,o.assigned_player_id,'IN_SERVICE' from pw_order o where o.order_no='ORD-ADMIN-DEMO-SERVICE';
insert into pw_order_status_log(order_id,from_status,to_status,operator_id,reason) select o.id,'ASSIGNED','IN_SERVICE',u.id,'V15 演示开始服务' from pw_order o join sys_user u on u.username='admin' where o.order_no='ORD-ADMIN-DEMO-SERVICE';

-- 待响应派单：用于测试接受或拒绝。
insert into pw_order(order_no,customer_id,order_status,total_amount,payable_amount,paid_amount,contact_name,contact_phone,customer_remark,paid_at,created_by)
select 'ORD-ADMIN-DEMO-DISPATCH',u.id,'WAIT_ASSIGN',58,58,58,u.nickname,u.phone,'演示：待响应抢单任务',current_timestamp,u.id from sys_user u where u.username='admin' and not exists(select 1 from pw_order where order_no='ORD-ADMIN-DEMO-DISPATCH');
insert into pw_order_item(order_id,product_id,sku_id,product_code,product_name,sku_code,sku_name,product_type,unit_price,quantity,subtotal_amount,service_snapshot) select o.id,p.id,k.id,p.product_code,p.product_name,k.sku_code,k.sku_name,p.product_type,58,1,58,'[{"serviceName":"无畏契约排位陪玩","quantity":1,"unitType":"HOUR"}]' from pw_order o join pw_product p on p.product_code='valorant-ranked-hour' join pw_product_sku k on k.sku_code='valorant-ranked-1h' where o.order_no='ORD-ADMIN-DEMO-DISPATCH';
insert into pw_order_game_profile(order_id,game_id,game_name,game_account,game_nickname,server_name,rank_name,extra_requirement) select o.id,g.id,g.game_name,'dispatch-demo','演示客户C','国服','铂金','希望沟通积极' from pw_order o join pw_game g on g.game_code='valorant' where o.order_no='ORD-ADMIN-DEMO-DISPATCH';
insert into pw_dispatch_task(task_no,order_id,dispatch_mode,task_status,target_player_id,attempt_no,candidate_count,deadline_at,created_by) select 'DSP-ADMIN-DEMO',o.id,'DIRECT','DISPATCHING',p.id,1,1,timestamp '2099-12-31 23:59:59',u.id from pw_order o join sys_user u on u.username='admin' join pw_player p on p.user_id=u.id where o.order_no='ORD-ADMIN-DEMO-DISPATCH' and not exists(select 1 from pw_dispatch_task where task_no='DSP-ADMIN-DEMO');
insert into pw_dispatch_candidate(task_id,player_id,match_score,active_order_count,candidate_status,notified) select t.id,p.id,99,2,'PENDING',true from pw_dispatch_task t join sys_user u on u.username='admin' join pw_player p on p.user_id=u.id where t.task_no='DSP-ADMIN-DEMO';
insert into pw_dispatch_action_log(task_id,order_id,player_id,action_type,from_status,to_status,operator_id,reason) select t.id,t.order_id,t.target_player_id,'CREATE',null,'DISPATCHING',u.id,'V15 演示指定派单' from pw_dispatch_task t join sys_user u on u.username='admin' where t.task_no='DSP-ADMIN-DEMO';
