create table pw_order_payment (
  id bigint generated by default as identity primary key,
  payment_no varchar(48) not null unique,
  request_no varchar(64) not null,
  order_id bigint not null unique,
  user_id bigint not null,
  payment_status varchar(20) not null,
  payable_amount decimal(14,2) not null,
  cash_amount decimal(14,2) not null default 0,
  bonus_amount decimal(14,2) not null default 0,
  refunded_cash_amount decimal(14,2) not null default 0,
  refunded_bonus_amount decimal(14,2) not null default 0,
  paid_at timestamp,
  refunded_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(user_id,request_no)
);
create index ix_pw_order_payment_user on pw_order_payment(user_id,id);

insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no)
select p.id,'BUTTON','CustomerOrdersPay','余额支付','customer:order:pay',5 from sys_menu p
where p.name='CustomerOrders' and not exists(select 1 from sys_menu where auth_mark='customer:order:pay');
insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no)
select p.id,'BUTTON','CustomerOrdersCancel','取消订单','customer:order:cancel',6 from sys_menu p
where p.name='CustomerOrders' and not exists(select 1 from sys_menu where auth_mark='customer:order:cancel');
insert into sys_role_menu(role_id,menu_id)
select r.id,m.id from sys_role r cross join sys_menu m
where r.code in('customer','admin') and m.auth_mark in('customer:order:pay','customer:order:cancel')
and not exists(select 1 from sys_role_menu x where x.role_id=r.id and x.menu_id=m.id);
