create table pw_player_profile_draft (
  id bigint generated by default as identity primary key,
  player_id bigint not null unique,
  profile_data clob not null,
  draft_status varchar(16) not null default 'DRAFT',
  review_remark varchar(500),
  submitted_at timestamp,
  reviewed_by bigint,
  reviewed_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index ix_pw_player_profile_draft_status on pw_player_profile_draft(draft_status, submitted_at);
