create table pw_player_level (
  id bigint generated by default as identity primary key,
  level_code varchar(32) not null unique,
  level_name varchar(64) not null,
  description varchar(255),
  sort_no integer not null default 0,
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

alter table pw_player_game add column price_level_id bigint;
alter table pw_product add column pricing_mode varchar(32) not null default 'FIXED_SKU';
update pw_product set pricing_mode=case when product_type='SERVICE' then 'PLAYER_LEVEL' else 'FIXED_SKU' end;

create table pw_sku_level_price (
  id bigint generated by default as identity primary key,
  sku_id bigint not null,
  player_level_id bigint not null,
  price decimal(12,2) not null,
  market_price decimal(12,2),
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(sku_id,player_level_id)
);
create index ix_pw_sku_level_price_sku on pw_sku_level_price(sku_id);
create index ix_pw_sku_level_price_level on pw_sku_level_price(player_level_id);

alter table pw_order add column requested_player_id bigint;
alter table pw_order add column requested_player_level_id bigint;
alter table pw_order add column player_level_code varchar(32);
alter table pw_order add column player_level_name varchar(64);
alter table pw_order add column pricing_mode varchar(32) not null default 'FIXED_SKU';
alter table pw_order_item add column pricing_rule_id bigint;

insert into pw_player_level(level_code,level_name,description,sort_no,enabled)
select 'STARTER','新锐','平台认证基础等级',1,true where not exists(select 1 from pw_player_level where level_code='STARTER');
insert into pw_player_level(level_code,level_name,description,sort_no,enabled)
select 'PRO','进阶','经验丰富的进阶陪玩师',2,true where not exists(select 1 from pw_player_level where level_code='PRO');
insert into pw_player_level(level_code,level_name,description,sort_no,enabled)
select 'MASTER','大神','高水平认证陪玩师',3,true where not exists(select 1 from pw_player_level where level_code='MASTER');

update pw_player_game set price_level_id=(select id from pw_player_level where level_code='PRO') where price_level_id is null;

insert into pw_sku_level_price(sku_id,player_level_id,price,market_price,enabled)
select k.id,l.id,
  case l.level_code when 'STARTER' then k.price*0.80 when 'MASTER' then k.price*1.50 else k.price end,
  k.market_price,true
from pw_product_sku k
join pw_product p on p.id=k.product_id and p.product_type='SERVICE'
cross join pw_player_level l
where not exists(select 1 from pw_sku_level_price x where x.sku_id=k.id and x.player_level_id=l.id);
