alter table pw_player_level rename to pw_player_level_legacy;
alter table pw_sku_level_price rename to pw_sku_level_price_legacy;
drop index ix_pw_sku_level_price_sku;
drop index ix_pw_sku_level_price_level;

create table pw_player_level (
  id bigint generated by default as identity primary key,
  game_id bigint not null,
  level_code varchar(32) not null,
  level_name varchar(64) not null,
  description varchar(255),
  sort_no integer not null default 0,
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(game_id,level_code)
);
create index ix_pw_player_level_game on pw_player_level(game_id);

insert into pw_player_level(game_id,level_code,level_name,description,sort_no,enabled,created_at,updated_at)
select g.id,l.level_code,l.level_name,l.description,l.sort_no,l.enabled,l.created_at,l.updated_at
from pw_game g cross join pw_player_level_legacy l;

update pw_player_game pg set price_level_id=(
  select n.id from pw_player_level n join pw_player_level_legacy o on o.level_code=n.level_code
  where n.game_id=pg.game_id and o.id=pg.price_level_id
);

update pw_order o set requested_player_level_id=(
  select n.id from pw_order_game_profile gp
  join pw_player_level_legacy old_level on old_level.id=o.requested_player_level_id
  join pw_player_level n on n.game_id=gp.game_id and n.level_code=old_level.level_code
  where gp.order_id=o.id
) where o.requested_player_level_id is not null and exists(select 1 from pw_order_game_profile gp where gp.order_id=o.id);

create table pw_sku_level_price (
  id bigint generated by default as identity primary key,
  sku_id bigint not null,
  player_level_id bigint not null,
  price decimal(12,2) not null,
  market_price decimal(12,2),
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(sku_id,player_level_id)
);
create index ix_pw_sku_level_price_sku on pw_sku_level_price(sku_id);
create index ix_pw_sku_level_price_level on pw_sku_level_price(player_level_id);

insert into pw_sku_level_price(sku_id,player_level_id,price,market_price,enabled,created_at,updated_at)
select old_price.sku_id,new_level.id,old_price.price,old_price.market_price,old_price.enabled,old_price.created_at,old_price.updated_at
from pw_sku_level_price_legacy old_price
join pw_player_level_legacy old_level on old_level.id=old_price.player_level_id
join pw_product_sku sku on sku.id=old_price.sku_id
join pw_product product on product.id=sku.product_id
join pw_player_level new_level on new_level.game_id=product.game_id and new_level.level_code=old_level.level_code;

drop table pw_sku_level_price_legacy;
drop table pw_player_level_legacy;
