create table pw_game_server (
  id bigint generated by default as identity primary key,
  game_id bigint not null,
  server_code varchar(64) not null,
  server_name varchar(64) not null,
  sort_no integer not null default 0,
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(game_id,server_code)
);

create table pw_game_rank_system (
  id bigint generated by default as identity primary key,
  game_id bigint not null,
  system_code varchar(64) not null,
  system_name varchar(64) not null,
  description varchar(255),
  sort_no integer not null default 0,
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(game_id,system_code)
);

create table pw_game_rank (
  id bigint generated by default as identity primary key,
  rank_system_id bigint not null,
  rank_code varchar(64) not null,
  rank_name varchar(64) not null,
  tier_no integer not null default 0,
  sort_no integer not null default 0,
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(rank_system_id,rank_code)
);

create table pw_customer_game_profile (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  game_id bigint not null,
  server_id bigint,
  game_account varchar(128) not null,
  game_nickname varchar(128) not null,
  is_default boolean not null default false,
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(user_id,game_id,game_account)
);

create table pw_customer_game_rank (
  id bigint generated by default as identity primary key,
  profile_id bigint not null,
  rank_system_id bigint not null,
  rank_id bigint not null,
  updated_at timestamp not null default current_timestamp,
  unique(profile_id,rank_system_id)
);

create index ix_pw_game_server_game on pw_game_server(game_id);
create index ix_pw_game_rank_system_game on pw_game_rank_system(game_id);
create index ix_pw_game_rank_system on pw_game_rank(rank_system_id);
create index ix_pw_customer_game_profile_user on pw_customer_game_profile(user_id,game_id);
create index ix_pw_customer_game_rank_profile on pw_customer_game_rank(profile_id);

alter table pw_player_game add column server_id bigint;
alter table pw_player_game add column rank_id bigint;
alter table pw_order_game_profile add column customer_game_profile_id bigint;
alter table pw_order_game_profile add column server_id bigint;
alter table pw_order_game_profile add column current_rank_id bigint;
alter table pw_order_game_profile add column target_rank_id bigint;
alter table pw_order_game_profile add column current_rank_name varchar(128);
alter table pw_order_game_profile add column target_rank_name varchar(128);
update pw_order_game_profile set current_rank_name=rank_name where rank_name is not null;

insert into pw_game_server(game_id,server_code,server_name,sort_no,enabled)
select id,'CN','国服',1,true from pw_game;

insert into pw_game_rank_system(game_id,system_code,system_name,description,sort_no,enabled)
select id,'DEFAULT','综合段位','该游戏默认段位体系',1,true from pw_game;

insert into pw_game_rank(rank_system_id,rank_code,rank_name,tier_no,sort_no,enabled)
select s.id,r.rank_code,r.rank_name,r.tier_no,r.tier_no,true
from pw_game_rank_system s cross join (
  select 'BRONZE' rank_code,'青铜' rank_name,1 tier_no union all
  select 'SILVER','白银',2 union all
  select 'GOLD','黄金',3 union all
  select 'PLATINUM','铂金',4 union all
  select 'DIAMOND','钻石',5 union all
  select 'MASTER','大师',6 union all
  select 'TOP','巅峰',7
) r;
