alter table sys_role add column built_in boolean not null default false;
alter table sys_menu add column keep_alive boolean not null default false;
alter table sys_menu add column created_at timestamp not null default current_timestamp;
alter table sys_menu add column updated_at timestamp not null default current_timestamp;

create index ix_sys_menu_parent on sys_menu(parent_id);
create index ix_sys_user_role_role on sys_user_role(role_id);
create index ix_sys_role_menu_menu on sys_role_menu(menu_id);

create table sys_login_log (
  id bigint generated by default as identity primary key,
  username varchar(64), success boolean not null,
  ip_address varchar(64), user_agent varchar(512), message varchar(255),
  created_at timestamp not null default current_timestamp
);

create table sys_operation_log (
  id bigint generated by default as identity primary key,
  operator_id bigint, operation varchar(128) not null,
  target_type varchar(64) not null, target_id varchar(64),
  detail varchar(1000), ip_address varchar(64),
  created_at timestamp not null default current_timestamp
);

update sys_role set built_in=true where code='admin';
update sys_menu set auth_mark='system:user:create' where name='UserAdd';
update sys_menu set auth_mark='system:user:update' where name='UserEdit';
update sys_menu set auth_mark='system:user:delete' where name='UserDelete';
update sys_menu set auth_mark='system:role:create' where name='RoleAdd';
update sys_menu set auth_mark='system:role:update' where name='RoleEdit';
update sys_menu set auth_mark='system:role:delete' where name='RoleDelete';
update sys_menu set auth_mark='system:role:assign' where name='RoleAssign';
update sys_menu set auth_mark='system:menu:create' where name='MenuAdd';
update sys_menu set auth_mark='system:menu:update' where name='MenuEdit';
update sys_menu set auth_mark='system:menu:delete' where name='MenuDelete';

create unique index ux_sys_menu_auth_mark on sys_menu(auth_mark);

insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no)
select id,'BUTTON','UserStatus','启用/禁用用户','system:user:status',4 from sys_menu where name='User';
insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no)
select id,'BUTTON','UserResetPassword','重置密码','system:user:reset-password',5 from sys_menu where name='User';
insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no)
select id,'BUTTON','UserAssignRole','分配角色','system:user:assign-role',6 from sys_menu where name='User';
insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no)
select id,'BUTTON','RoleStatus','启用/禁用角色','system:role:status',5 from sys_menu where name='Role';
