create table pw_service_level_price (
  id bigint generated by default as identity primary key,
  service_id bigint not null,
  player_level_id bigint not null,
  unit_type varchar(16) not null,
  price decimal(12,2) not null,
  market_price decimal(12,2),
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(service_id, player_level_id, unit_type)
);

create index ix_pw_service_level_price_service on pw_service_level_price(service_id);
create index ix_pw_service_level_price_level on pw_service_level_price(player_level_id);

-- Existing SKU level prices are full-spec prices. Normalize them back to one hour/game/order.
insert into pw_service_level_price(service_id,player_level_id,unit_type,price,market_price,enabled)
select ps.service_id,x.player_level_id,k.unit_type,
  round(min(x.price / nullif(k.unit_count,0)),2),
  round(min(x.market_price / nullif(k.unit_count,0)),2),true
from pw_product p
join pw_product_service ps on ps.product_id=p.id
join pw_product_sku k on k.product_id=p.id and k.enabled=true
join pw_sku_level_price x on x.sku_id=k.id and x.enabled=true
where p.product_type='SERVICE'
group by ps.service_id,x.player_level_id,k.unit_type;

-- Preserve a usable fallback for service/level combinations that had no explicit SKU-level row.
insert into pw_service_level_price(service_id,player_level_id,unit_type,price,market_price,enabled)
select ps.service_id,l.id,k.unit_type,
  round(min(k.price / nullif(k.unit_count,0)),2),
  round(min(k.market_price / nullif(k.unit_count,0)),2),true
from pw_product p
join pw_product_service ps on ps.product_id=p.id
join pw_product_sku k on k.product_id=p.id and k.enabled=true
join pw_player_level l on l.game_id=p.game_id and l.enabled=true
where p.product_type='SERVICE'
  and not exists (
    select 1 from pw_service_level_price sp
    where sp.service_id=ps.service_id and sp.player_level_id=l.id and sp.unit_type=k.unit_type
  )
group by ps.service_id,l.id,k.unit_type;
