create table pw_order_member (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  player_id bigint not null,
  member_status varchar(24) not null default 'ACCEPTED',
  join_source varchar(24) not null default 'LEGACY',
  dispatch_task_id bigint,
  joined_at timestamp not null default current_timestamp,
  service_started_at timestamp,
  completed_at timestamp,
  cancelled_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(order_id, player_id)
);

create index ix_pw_order_member_order on pw_order_member(order_id, member_status);
create index ix_pw_order_member_player on pw_order_member(player_id, member_status);

-- Keep every historical single-player order available through the new member model.
insert into pw_order_member(order_id,player_id,member_status,join_source,joined_at,service_started_at,completed_at,cancelled_at)
select id,assigned_player_id,
  case
    when order_status='COMPLETED' then 'COMPLETED'
    when order_status='CANCELLED' then 'CANCELLED'
    when order_status in('IN_SERVICE','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE') then 'IN_SERVICE'
    else 'ACCEPTED'
  end,
  'LEGACY',coalesce(assigned_at,created_at),service_started_at,completed_at,cancelled_at
from pw_order o
where assigned_player_id is not null
  and not exists(select 1 from pw_order_member m where m.order_id=o.id and m.player_id=o.assigned_player_id);
