-- Split the former service-specific order aggregate into a generic trade header and
-- a player-service branch. Existing ids are retained so all historical business
-- tables continue to reference the same order identifier.
create table pw_trade_order (
  id bigint generated by default as identity primary key,
  order_no varchar(40) not null unique,
  customer_id bigint not null,
  business_type varchar(32) not null,
  trade_status varchar(32) not null,
  title varchar(128),
  total_amount decimal(14,2) not null,
  discount_amount decimal(14,2) not null default 0,
  payable_amount decimal(14,2) not null,
  paid_amount decimal(14,2) not null default 0,
  refunded_amount decimal(14,2) not null default 0,
  payment_status varchar(24) not null default 'UNPAID',
  refund_status varchar(24) not null default 'NONE',
  customer_remark varchar(1000),
  cancel_reason varchar(500),
  paid_at timestamp,
  completed_at timestamp,
  cancelled_at timestamp,
  created_by bigint,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index ix_pw_trade_order_customer on pw_trade_order(customer_id,business_type,id);
create index ix_pw_trade_order_status on pw_trade_order(business_type,trade_status,id);

create table pw_service_order (
  order_id bigint primary key,
  requested_player_id bigint,
  requested_player_level_id bigint,
  player_level_code varchar(32),
  player_level_name varchar(64),
  required_player_count integer not null default 1,
  pricing_mode varchar(32) not null default 'FIXED_SKU',
  price_type varchar(20) not null default 'PER_PLAYER',
  base_unit_price decimal(14,2),
  contact_name varchar(64),
  contact_phone varchar(32),
  service_status varchar(32) not null,
  assigned_at timestamp,
  service_started_at timestamp,
  completion_submitted_at timestamp,
  customer_confirm_deadline timestamp,
  customer_confirmed_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index ix_pw_service_order_status on pw_service_order(service_status,order_id);
create index ix_pw_service_order_requested_player on pw_service_order(requested_player_id,order_id);

insert into pw_trade_order(
  id,order_no,customer_id,business_type,trade_status,title,total_amount,discount_amount,
  payable_amount,paid_amount,refunded_amount,payment_status,refund_status,customer_remark,
  cancel_reason,paid_at,completed_at,cancelled_at,created_by,created_at,updated_at
)
select o.id,o.order_no,o.customer_id,'PLAYER_SERVICE',
  case when o.order_status='PENDING_PAYMENT' then 'PENDING_PAYMENT'
       when o.order_status='COMPLETED' then 'COMPLETED'
       when o.order_status='CANCELLED' then 'CANCELLED'
       else 'PROCESSING' end,
  (select i.product_name from pw_order_item i where i.order_id=o.id order by i.id limit 1),
  o.total_amount,0,o.payable_amount,
  coalesce((select p.payable_amount from pw_order_payment p where p.order_id=o.id),o.paid_amount),
  case when exists(select 1 from pw_order_payment p where p.order_id=o.id and p.payment_status='REFUNDED')
       then coalesce((select p.payable_amount from pw_order_payment p where p.order_id=o.id),0) else 0 end,
  coalesce((select p.payment_status from pw_order_payment p where p.order_id=o.id),
    case when o.order_status='PENDING_PAYMENT' then 'UNPAID' else 'PAID' end),
  case when exists(select 1 from pw_order_payment p where p.order_id=o.id and p.payment_status='REFUNDED') then 'FULL' else 'NONE' end,
  o.customer_remark,o.cancel_reason,o.paid_at,o.completed_at,o.cancelled_at,o.created_by,o.created_at,o.updated_at
from pw_order o;

insert into pw_service_order(
  order_id,requested_player_id,requested_player_level_id,player_level_code,player_level_name,
  required_player_count,pricing_mode,price_type,base_unit_price,contact_name,contact_phone,
  service_status,assigned_at,service_started_at,completion_submitted_at,
  customer_confirm_deadline,customer_confirmed_at,created_at,updated_at
)
select id,requested_player_id,requested_player_level_id,player_level_code,player_level_name,
  required_player_count,pricing_mode,sku_price_type,base_unit_price,contact_name,contact_phone,
  order_status,assigned_at,service_started_at,completion_submitted_at,
  customer_confirm_deadline,customer_confirmed_at,created_at,updated_at
from pw_order;

-- Recharge is a separate business branch but participates in the same trade-order
-- statistics. Its legacy primary key is retained inside pw_recharge_order.
alter table pw_recharge_order add column trade_order_id bigint;

insert into pw_trade_order(
  order_no,customer_id,business_type,trade_status,title,total_amount,discount_amount,
  payable_amount,paid_amount,refunded_amount,payment_status,refund_status,paid_at,
  completed_at,created_by,created_at,updated_at
)
select r.recharge_no,r.user_id,'WALLET_RECHARGE',
  case when r.recharge_status='PAID' then 'COMPLETED' else r.recharge_status end,
  p.plan_name,r.recharge_amount,0,r.recharge_amount,
  case when r.recharge_status='PAID' then r.recharge_amount else 0 end,
  0,case when r.recharge_status='PAID' then 'PAID' else 'UNPAID' end,'NONE',
  r.paid_at,case when r.recharge_status='PAID' then r.paid_at else null end,
  r.user_id,r.created_at,r.updated_at
from pw_recharge_order r join pw_recharge_plan p on p.id=r.plan_id;

update pw_recharge_order r set trade_order_id=(select t.id from pw_trade_order t where t.order_no=r.recharge_no);
create unique index uk_pw_recharge_trade_order on pw_recharge_order(trade_order_id);

create table pw_trade_payment (
  id bigint generated by default as identity primary key,
  payment_no varchar(48) not null unique,
  request_no varchar(64) not null,
  order_id bigint not null unique,
  user_id bigint not null,
  payment_channel varchar(24) not null,
  payment_status varchar(24) not null,
  payable_amount decimal(14,2) not null,
  cash_amount decimal(14,2) not null default 0,
  bonus_amount decimal(14,2) not null default 0,
  refunded_cash_amount decimal(14,2) not null default 0,
  refunded_bonus_amount decimal(14,2) not null default 0,
  paid_at timestamp,
  refunded_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(user_id,request_no)
);

insert into pw_trade_payment(id,payment_no,request_no,order_id,user_id,payment_channel,payment_status,payable_amount,cash_amount,bonus_amount,refunded_cash_amount,refunded_bonus_amount,paid_at,refunded_at,created_at,updated_at)
select id,payment_no,request_no,order_id,user_id,payment_channel,payment_status,payable_amount,cash_amount,bonus_amount,refunded_cash_amount,refunded_bonus_amount,paid_at,refunded_at,created_at,updated_at from pw_order_payment;

insert into pw_trade_payment(payment_no,request_no,order_id,user_id,payment_channel,payment_status,payable_amount,cash_amount,bonus_amount,refunded_cash_amount,refunded_bonus_amount,paid_at,created_at,updated_at)
select concat('RCP',r.recharge_no),r.request_no,r.trade_order_id,r.user_id,'MOCK_RECHARGE','PAID',r.recharge_amount,r.recharge_amount,0,0,0,r.paid_at,r.created_at,r.updated_at from pw_recharge_order r;

create index ix_pw_trade_payment_user on pw_trade_payment(user_id,id);
drop table pw_order_payment;

-- One settlement header per trade order, with extensible distribution details.
create table pw_order_settlement (
  id bigint generated by default as identity primary key,
  settlement_no varchar(48) not null unique,
  order_id bigint not null unique,
  order_amount decimal(14,2) not null,
  platform_amount decimal(14,2) not null,
  distributable_amount decimal(14,2) not null,
  settlement_status varchar(24) not null,
  settled_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table pw_order_settlement_detail (
  id bigint generated by default as identity primary key,
  settlement_id bigint not null,
  order_id bigint not null,
  order_member_id bigint,
  player_id bigint,
  detail_type varchar(32) not null,
  amount decimal(14,2) not null,
  calculation_base decimal(14,2),
  rate decimal(8,4),
  remark varchar(500),
  created_at timestamp not null default current_timestamp
);

create unique index uk_pw_settlement_member_type on pw_order_settlement_detail(settlement_id,order_member_id,detail_type);
create index ix_pw_settlement_detail_order on pw_order_settlement_detail(order_id,id);

create table pw_platform_ledger (
  id bigint generated by default as identity primary key,
  ledger_no varchar(48) not null unique,
  order_id bigint,
  settlement_detail_id bigint,
  business_type varchar(32) not null,
  direction varchar(8) not null,
  amount decimal(14,2) not null,
  remark varchar(500),
  created_at timestamp not null default current_timestamp
);
create index ix_pw_platform_ledger_order on pw_platform_ledger(order_id,id);

-- Replace the V20 one-row-per-order earning constraint with a member-scoped link.
create table pw_player_earning_v42 (
  id bigint generated by default as identity primary key,
  earning_no varchar(48) not null unique,
  order_id bigint not null,
  order_member_id bigint,
  settlement_detail_id bigint,
  player_id bigint not null,
  order_amount decimal(14,2) not null,
  commission_rate decimal(6,4) not null,
  commission_amount decimal(14,2) not null,
  player_amount decimal(14,2) not null,
  earning_status varchar(20) not null,
  settled_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

insert into pw_player_earning_v42(
  id,earning_no,order_id,order_member_id,player_id,order_amount,commission_rate,
  commission_amount,player_amount,earning_status,settled_at,created_at,updated_at
)
select e.id,e.earning_no,e.order_id,
  (select min(m.id) from pw_order_member m where m.order_id=e.order_id and m.player_id=e.player_id),
  e.player_id,e.order_amount,e.commission_rate,e.commission_amount,e.player_amount,
  e.earning_status,e.settled_at,e.created_at,e.updated_at
from pw_player_earning e;

drop table pw_player_earning;
alter table pw_player_earning_v42 rename to pw_player_earning;
create unique index uk_pw_player_earning_member on pw_player_earning(order_member_id);
create index ix_pw_player_earning_order on pw_player_earning(order_id,id);

-- All Java reads/writes have moved to pw_trade_order/pw_service_order. Removing
-- the legacy aggregate prevents the former assigned_player_id from becoming a
-- second source of truth again.
drop table pw_order;
