-- Member-scoped fulfillment and audited service exception workflow.

create table pw_fulfillment_v43 (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  order_member_id bigint not null unique,
  player_id bigint not null,
  fulfillment_status varchar(24) not null default 'IN_SERVICE',
  completion_note varchar(1000),
  actual_quantity decimal(10,2),
  submitted_at timestamp,
  reviewed_by bigint,
  reviewed_at timestamp,
  review_remark varchar(500),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

insert into pw_fulfillment_v43(id,order_id,order_member_id,player_id,fulfillment_status,completion_note,actual_quantity,submitted_at,reviewed_by,reviewed_at,review_remark,created_at,updated_at)
select f.id,f.order_id,m.id,f.player_id,f.fulfillment_status,f.completion_note,f.actual_quantity,f.submitted_at,f.reviewed_by,f.reviewed_at,f.review_remark,f.created_at,f.updated_at
from pw_fulfillment f
join pw_order_member m on m.id=(select min(x.id) from pw_order_member x where x.order_id=f.order_id and x.player_id=f.player_id);

insert into pw_fulfillment_v43(order_id,order_member_id,player_id,fulfillment_status,created_at,updated_at)
select m.order_id,m.id,m.player_id,
  case when s.service_status in('PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','COMPLETED') then 'PENDING_REVIEW' else 'IN_SERVICE' end,
  coalesce(m.service_started_at,m.joined_at),current_timestamp
from pw_order_member m join pw_service_order s on s.order_id=m.order_id
where m.member_status in('IN_SERVICE','COMPLETED')
  and not exists(select 1 from pw_fulfillment_v43 f where f.order_member_id=m.id);

drop table pw_fulfillment;
alter table pw_fulfillment_v43 rename to pw_fulfillment;
create index ix_pw_fulfillment_order on pw_fulfillment(order_id,fulfillment_status);
create index ix_pw_fulfillment_player on pw_fulfillment(player_id,fulfillment_status);

create table pw_service_exception_request (
  id bigint generated by default as identity primary key,
  request_no varchar(48) not null unique,
  order_id bigint not null,
  request_type varchar(16) not null,
  source_order_member_id bigint,
  target_player_id bigint,
  applicant_type varchar(16) not null,
  applicant_user_id bigint not null,
  reason varchar(1000) not null,
  proof_urls clob,
  request_status varchar(32) not null,
  review_remark varchar(1000),
  reviewed_by bigint,
  reviewed_at timestamp,
  replacement_order_member_id bigint,
  resolved_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);
create index ix_pw_service_exception_order on pw_service_exception_request(order_id,request_status,id);
create index ix_pw_service_exception_target on pw_service_exception_request(target_player_id,request_status,id);

create table pw_service_member_transfer (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  exception_request_id bigint not null unique,
  from_order_member_id bigint not null unique,
  to_order_member_id bigint not null unique,
  transferred_at timestamp not null default current_timestamp,
  created_at timestamp not null default current_timestamp
);
create index ix_pw_service_transfer_order on pw_service_member_transfer(order_id,id);

insert into sys_menu(parent_id,type,name,path,component,title,icon,sort_no)
select id,'MENU','ServiceExceptionManage','service-exception-manage','/business/service-exception-manage','转单炸单审核','ri:swap-box-line',11
from sys_menu where name='Business' and not exists(select 1 from sys_menu where name='ServiceExceptionManage');

insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no)
select p.id,'BUTTON',concat('ServiceException',a.suffix),a.title,a.mark,a.sort_no
from sys_menu p join (
  select 'List' suffix,'查询异常申请' title,'business:service-exception:list' mark,1 sort_no
  union all select 'Review','审核异常申请','business:service-exception:review',2
) a on 1=1 where p.name='ServiceExceptionManage'
and not exists(select 1 from sys_menu m where m.auth_mark=a.mark);

insert into sys_role_menu(role_id,menu_id)
select r.id,m.id from sys_role r cross join sys_menu m
where r.code='admin' and (m.name='ServiceExceptionManage' or m.auth_mark like 'business:service-exception:%')
and not exists(select 1 from sys_role_menu x where x.role_id=r.id and x.menu_id=m.id);
