-- Immutable liability decisions and account movements for successful transfers
-- and approved service aborts. Both rates use the service-order base unit price.

create table pw_service_liability (
  id bigint generated by default as identity primary key,
  liability_no varchar(48) not null unique,
  order_id bigint not null,
  exception_request_id bigint,
  liability_type varchar(32) not null,
  root_order_member_id bigint,
  liable_order_member_id bigint not null,
  beneficiary_order_member_id bigint,
  liable_player_id bigint not null,
  beneficiary_player_id bigint,
  calculation_base decimal(14,2) not null,
  rate decimal(8,4) not null,
  amount decimal(14,2) not null,
  liability_status varchar(24) not null,
  determined_by bigint,
  determined_at timestamp not null default current_timestamp,
  remark varchar(500),
  created_at timestamp not null default current_timestamp
);
create unique index uk_pw_service_liability_member on pw_service_liability(order_id,liability_type,liable_order_member_id);
create index ix_pw_service_liability_order on pw_service_liability(order_id,id);

create table pw_service_penalty_ledger (
  id bigint generated by default as identity primary key,
  ledger_no varchar(48) not null unique,
  liability_id bigint not null,
  order_id bigint not null,
  player_id bigint not null,
  counterparty_player_id bigint,
  entry_type varchar(32) not null,
  direction varchar(8) not null,
  amount decimal(14,2) not null,
  balance_before decimal(14,2) not null,
  balance_after decimal(14,2) not null,
  created_at timestamp not null default current_timestamp
);
create unique index uk_pw_service_penalty_entry on pw_service_penalty_ledger(liability_id,player_id,direction);
create index ix_pw_service_penalty_order on pw_service_penalty_ledger(order_id,id);
