alter table pw_service_item add column usage_type varchar(32) not null default 'STANDALONE';

create table pw_sku_commitment (
  id bigint generated by default as identity primary key,
  sku_id bigint not null,
  rule_type varchar(32) not null,
  title varchar(128) not null,
  target_value decimal(18,2),
  target_unit varchar(32),
  description varchar(1000),
  failure_action varchar(500),
  enabled boolean not null default true,
  sort_no integer not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);
create index ix_pw_sku_commitment_sku on pw_sku_commitment(sku_id);

create table pw_order_commitment (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  order_item_id bigint not null,
  source_commitment_id bigint,
  rule_type varchar(32) not null,
  title varchar(128) not null,
  target_value decimal(18,2),
  target_unit varchar(32),
  description varchar(1000),
  failure_action varchar(500),
  sort_no integer not null default 0,
  created_at timestamp not null default current_timestamp
);
create index ix_pw_order_commitment_order on pw_order_commitment(order_id);
create index ix_pw_order_commitment_item on pw_order_commitment(order_item_id);
