-- Audited pause/resume workflow for player service orders only.

create table pw_service_pause_record (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  pause_request_id bigint not null unique,
  resume_request_id bigint unique,
  pause_reason varchar(1000) not null,
  resume_reason varchar(1000),
  paused_at timestamp not null,
  resumed_at timestamp,
  paused_by bigint not null,
  resumed_by bigint,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);
create index ix_pw_service_pause_order on pw_service_pause_record(order_id,paused_at,id);

update sys_menu set title='服务变更审核' where name='ServiceExceptionManage';

