create table pw_player_application (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  real_name varchar(64) not null,
  phone varchar(32) not null,
  address varchar(500) not null,
  application_status varchar(16) not null default 'PENDING',
  follow_up_remark varchar(500),
  handled_by bigint,
  handled_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index ix_pw_player_application_user on pw_player_application(user_id,application_status);
create index ix_pw_player_application_status on pw_player_application(application_status,created_at);

