insert into pw_game(game_code,game_name,platform_type,description,sort_no,enabled)
select 'delta-force','三角洲行动','PC','战术射击与大战场陪玩',1,true where not exists(select 1 from pw_game where game_code='delta-force');
insert into pw_game(game_code,game_name,platform_type,description,sort_no,enabled)
select 'valorant','无畏契约','PC','竞技射击、排位上分与娱乐陪玩',2,true where not exists(select 1 from pw_game where game_code='valorant');

insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'assault','突击',1,true from pw_game where game_code='delta-force' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='assault');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'support','支援',2,true from pw_game where game_code='delta-force' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='support');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'engineer','工程',3,true from pw_game where game_code='delta-force' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='engineer');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'recon','侦察',4,true from pw_game where game_code='delta-force' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='recon');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'operator','烽火地带',5,true from pw_game where game_code='delta-force' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='operator');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'warfare','全面战场',6,true from pw_game where game_code='delta-force' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='warfare');

insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'duelist','决斗',1,true from pw_game where game_code='valorant' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='duelist');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'initiator','先锋',2,true from pw_game where game_code='valorant' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='initiator');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'controller','控场',3,true from pw_game where game_code='valorant' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='controller');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'sentinel','哨卫',4,true from pw_game where game_code='valorant' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='sentinel');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'ranked','排位上分',5,true from pw_game where game_code='valorant' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='ranked');
insert into pw_game_position(game_id,position_code,position_name,sort_no,enabled) select id,'casual','娱乐匹配',6,true from pw_game where game_code='valorant' and not exists(select 1 from pw_game_position p where p.game_id=pw_game.id and p.position_code='casual');

insert into pw_player_tag(tag_code,tag_name,tag_color,tag_group,sort_no,enabled) select 'aim-strong','枪法在线','#F56C6C','SKILL',1,true where not exists(select 1 from pw_player_tag where tag_code='aim-strong');
insert into pw_player_tag(tag_code,tag_name,tag_color,tag_group,sort_no,enabled) select 'good-command','指挥清晰','#409EFF','STYLE',2,true where not exists(select 1 from pw_player_tag where tag_code='good-command');
insert into pw_player_tag(tag_code,tag_name,tag_color,tag_group,sort_no,enabled) select 'patient','耐心教学','#67C23A','STYLE',3,true where not exists(select 1 from pw_player_tag where tag_code='patient');
insert into pw_player_tag(tag_code,tag_name,tag_color,tag_group,sort_no,enabled) select 'funny','氛围活跃','#E6A23C','STYLE',4,true where not exists(select 1 from pw_player_tag where tag_code='funny');
insert into pw_player_tag(tag_code,tag_name,tag_color,tag_group,sort_no,enabled) select 'late-night','深夜在线','#909399','TIME',5,true where not exists(select 1 from pw_player_tag where tag_code='late-night');

insert into pw_player(player_no,nickname,gender,phone,introduction,audit_status,work_status,enabled,audit_remark,approved_at,rating_score,rating_count,order_count,sort_no,remark)
select 'DEMO-PW-001','北极星','MALE','19000000001','三角洲行动全面战场指挥，熟悉地图轮转与载具配合。','APPROVED','AVAILABLE',true,'演示数据：审核通过',current_timestamp,4.92,86,128,1,'演示账号' where not exists(select 1 from pw_player where player_no='DEMO-PW-001');
insert into pw_player(player_no,nickname,gender,phone,introduction,audit_status,work_status,enabled,audit_remark,approved_at,rating_score,rating_count,order_count,sort_no,remark)
select 'DEMO-PW-002','小熊突击手','FEMALE','19000000002','烽火地带跑图与物资规划，节奏稳定，支持新手教学。','APPROVED','BUSY',true,'演示数据：审核通过',current_timestamp,4.88,54,79,2,'演示账号' where not exists(select 1 from pw_player where player_no='DEMO-PW-002');
insert into pw_player(player_no,nickname,gender,phone,introduction,audit_status,work_status,enabled,audit_remark,approved_at,rating_score,rating_count,order_count,sort_no,remark)
select 'DEMO-PW-003','夜航','MALE','19000000003','无畏契约主玩控场与先锋，擅长报点、道具教学。','APPROVED','AVAILABLE',true,'演示数据：审核通过',current_timestamp,4.96,112,167,3,'演示账号' where not exists(select 1 from pw_player where player_no='DEMO-PW-003');
insert into pw_player(player_no,nickname,gender,phone,introduction,audit_status,work_status,enabled,audit_remark,approved_at,rating_score,rating_count,order_count,sort_no,remark)
select 'DEMO-PW-004','糖果枪手','FEMALE','19000000004','无畏契约娱乐陪玩，主玩决斗，氛围轻松。','APPROVED','OFFLINE',true,'演示数据：审核通过',current_timestamp,4.85,41,63,4,'演示账号' where not exists(select 1 from pw_player where player_no='DEMO-PW-004');
insert into pw_player(player_no,nickname,gender,phone,introduction,audit_status,work_status,enabled,audit_remark,rating_score,rating_count,order_count,sort_no,remark)
select 'DEMO-PW-005','灰鸽','UNKNOWN','19000000005','三角洲行动与无畏契约双端陪玩，资料待审核。','PENDING','OFFLINE',true,'等待审核',0,0,0,5,'演示账号' where not exists(select 1 from pw_player where player_no='DEMO-PW-005');

insert into pw_player_game(player_id,game_id,game_nickname,server_name,rank_name,experience_years,introduction,is_primary,audit_status,enabled) select p.id,g.id,'北极星Delta','国服','全面战场王牌',2,'主打大战场指挥与团队协作',true,'APPROVED',true from pw_player p cross join pw_game g where p.player_no='DEMO-PW-001' and g.game_code='delta-force' and not exists(select 1 from pw_player_game x where x.player_id=p.id and x.game_id=g.id);
insert into pw_player_game(player_id,game_id,game_nickname,server_name,rank_name,experience_years,introduction,is_primary,audit_status,enabled) select p.id,g.id,'小熊冲锋','国服','烽火地带钻石',1,'熟悉物资点与撤离路线',true,'APPROVED',true from pw_player p cross join pw_game g where p.player_no='DEMO-PW-002' and g.game_code='delta-force' and not exists(select 1 from pw_player_game x where x.player_id=p.id and x.game_id=g.id);
insert into pw_player_game(player_id,game_id,game_nickname,server_name,rank_name,experience_years,introduction,is_primary,audit_status,enabled) select p.id,g.id,'NightSail','国服','神话',3,'道具配合与排位上分',true,'APPROVED',true from pw_player p cross join pw_game g where p.player_no='DEMO-PW-003' and g.game_code='valorant' and not exists(select 1 from pw_player_game x where x.player_id=p.id and x.game_id=g.id);
insert into pw_player_game(player_id,game_id,game_nickname,server_name,rank_name,experience_years,introduction,is_primary,audit_status,enabled) select p.id,g.id,'CandyAim','国服','超凡',2,'娱乐匹配与决斗位',true,'APPROVED',true from pw_player p cross join pw_game g where p.player_no='DEMO-PW-004' and g.game_code='valorant' and not exists(select 1 from pw_player_game x where x.player_id=p.id and x.game_id=g.id);
insert into pw_player_game(player_id,game_id,game_nickname,server_name,rank_name,experience_years,introduction,is_primary,audit_status,enabled) select p.id,g.id,'GreyPigeon','国服','钻石',1,'待审核的双游资料',true,'PENDING',true from pw_player p cross join pw_game g where p.player_no='DEMO-PW-005' and g.game_code='delta-force' and not exists(select 1 from pw_player_game x where x.player_id=p.id and x.game_id=g.id);
insert into pw_player_game(player_id,game_id,game_nickname,server_name,rank_name,experience_years,introduction,is_primary,audit_status,enabled) select p.id,g.id,'GreyValorant','国服','铂金',1,'待审核的副游戏资料',false,'PENDING',true from pw_player p cross join pw_game g where p.player_no='DEMO-PW-005' and g.game_code='valorant' and not exists(select 1 from pw_player_game x where x.player_id=p.id and x.game_id=g.id);

insert into pw_player_tag_rel(player_id,tag_id) select p.id,t.id from pw_player p cross join pw_player_tag t where p.player_no='DEMO-PW-001' and t.tag_code in('good-command','aim-strong') and not exists(select 1 from pw_player_tag_rel x where x.player_id=p.id and x.tag_id=t.id);
insert into pw_player_tag_rel(player_id,tag_id) select p.id,t.id from pw_player p cross join pw_player_tag t where p.player_no='DEMO-PW-002' and t.tag_code in('patient','funny') and not exists(select 1 from pw_player_tag_rel x where x.player_id=p.id and x.tag_id=t.id);
insert into pw_player_tag_rel(player_id,tag_id) select p.id,t.id from pw_player p cross join pw_player_tag t where p.player_no='DEMO-PW-003' and t.tag_code in('aim-strong','good-command','late-night') and not exists(select 1 from pw_player_tag_rel x where x.player_id=p.id and x.tag_id=t.id);
insert into pw_player_tag_rel(player_id,tag_id) select p.id,t.id from pw_player p cross join pw_player_tag t where p.player_no='DEMO-PW-004' and t.tag_code in('funny','late-night') and not exists(select 1 from pw_player_tag_rel x where x.player_id=p.id and x.tag_id=t.id);

insert into pw_player_game_position(player_game_id,position_id,is_primary) select pg.id,pos.id,true from pw_player_game pg join pw_player p on p.id=pg.player_id join pw_game_position pos on pos.game_id=pg.game_id where p.player_no='DEMO-PW-001' and pos.position_code='warfare' and not exists(select 1 from pw_player_game_position x where x.player_game_id=pg.id and x.position_id=pos.id);
insert into pw_player_game_position(player_game_id,position_id,is_primary) select pg.id,pos.id,false from pw_player_game pg join pw_player p on p.id=pg.player_id join pw_game_position pos on pos.game_id=pg.game_id where p.player_no='DEMO-PW-001' and pos.position_code='assault' and not exists(select 1 from pw_player_game_position x where x.player_game_id=pg.id and x.position_id=pos.id);
insert into pw_player_game_position(player_game_id,position_id,is_primary) select pg.id,pos.id,true from pw_player_game pg join pw_player p on p.id=pg.player_id join pw_game_position pos on pos.game_id=pg.game_id where p.player_no='DEMO-PW-002' and pos.position_code='operator' and not exists(select 1 from pw_player_game_position x where x.player_game_id=pg.id and x.position_id=pos.id);
insert into pw_player_game_position(player_game_id,position_id,is_primary) select pg.id,pos.id,true from pw_player_game pg join pw_player p on p.id=pg.player_id join pw_game_position pos on pos.game_id=pg.game_id where p.player_no='DEMO-PW-003' and pos.position_code='controller' and not exists(select 1 from pw_player_game_position x where x.player_game_id=pg.id and x.position_id=pos.id);
insert into pw_player_game_position(player_game_id,position_id,is_primary) select pg.id,pos.id,false from pw_player_game pg join pw_player p on p.id=pg.player_id join pw_game_position pos on pos.game_id=pg.game_id where p.player_no='DEMO-PW-003' and pos.position_code='initiator' and not exists(select 1 from pw_player_game_position x where x.player_game_id=pg.id and x.position_id=pos.id);
insert into pw_player_game_position(player_game_id,position_id,is_primary) select pg.id,pos.id,true from pw_player_game pg join pw_player p on p.id=pg.player_id join pw_game_position pos on pos.game_id=pg.game_id where p.player_no='DEMO-PW-004' and pos.position_code='duelist' and not exists(select 1 from pw_player_game_position x where x.player_game_id=pg.id and x.position_id=pos.id);
