create table pw_product (id bigint generated by default as identity primary key, game_id bigint not null, category_id bigint not null, product_code varchar(64) not null unique, product_name varchar(128) not null, subtitle varchar(255), description varchar(2000), cover_url varchar(512), product_type varchar(32) not null default 'SERVICE', status varchar(32) not null default 'DRAFT', sort_no integer not null default 0, created_at timestamp not null default current_timestamp, updated_at timestamp not null default current_timestamp);
create index ix_pw_product_game on pw_product(game_id);
create index ix_pw_product_category on pw_product(category_id);

create table pw_product_service (product_id bigint not null, service_id bigint not null, primary key(product_id,service_id));
create index ix_pw_product_service_service on pw_product_service(service_id);

create table pw_product_sku (id bigint generated by default as identity primary key, product_id bigint not null, sku_code varchar(64) not null unique, sku_name varchar(128) not null, price decimal(12,2) not null, unit_type varchar(32) not null, unit_count decimal(10,2) not null default 1, min_quantity integer not null default 1, max_quantity integer, stock_mode varchar(16) not null default 'UNLIMITED', stock_quantity integer, service_minutes integer, enabled boolean not null default true, sort_no integer not null default 0, created_at timestamp not null default current_timestamp, updated_at timestamp not null default current_timestamp);
create index ix_pw_product_sku_product on pw_product_sku(product_id);

insert into sys_menu(parent_id,type,name,path,component,title,icon,sort_no) select id,'MENU','ProductManage','product-manage','/business/product-manage','商品管理','ri:shopping-bag-3-line',6 from sys_menu where name='Business' and not exists(select 1 from sys_menu where name='ProductManage');
insert into sys_menu(parent_id,type,name,title,auth_mark,sort_no) select p.id,'BUTTON',concat(p.name,a.suffix),a.title,a.mark,a.sort_no from sys_menu p join (
 select 'List' suffix,'查询商品' title,'business:product:list' mark,1 sort_no union all
 select 'Create','新增商品','business:product:create',2 union all
 select 'Update','编辑商品','business:product:update',3 union all
 select 'Status','商品上下架','business:product:status',4 union all
 select 'Delete','删除商品','business:product:delete',5
) a on 1=1 where p.name='ProductManage' and not exists(select 1 from sys_menu m where m.auth_mark=a.mark);
insert into sys_role_menu(role_id,menu_id) select r.id,m.id from sys_role r cross join sys_menu m where r.code='admin' and not exists(select 1 from sys_role_menu x where x.role_id=r.id and x.menu_id=m.id);

insert into pw_product(game_id,category_id,product_code,product_name,subtitle,description,product_type,status,sort_no)
select g.id,c.id,'delta-escort-experience','烽火地带护航体验','1 局护航，熟悉撤离流程','适合初次体验护航服务的用户','SERVICE','ON_SALE',1 from pw_game g join pw_product_category c on c.category_code='delta-single' where g.game_code='delta-force' and not exists(select 1 from pw_product where product_code='delta-escort-experience');
insert into pw_product_service(product_id,service_id) select p.id,s.id from pw_product p join pw_service_item s on s.service_code='delta-escort' where p.product_code='delta-escort-experience' and not exists(select 1 from pw_product_service x where x.product_id=p.id and x.service_id=s.id);
insert into pw_product_sku(product_id,sku_code,sku_name,price,unit_type,unit_count,min_quantity,max_quantity,stock_mode,service_minutes,enabled,sort_no) select id,'delta-escort-1game','单局体验',99.00,'GAME',1,1,10,'UNLIMITED',60,true,1 from pw_product where product_code='delta-escort-experience' and not exists(select 1 from pw_product_sku where sku_code='delta-escort-1game');

insert into pw_product(game_id,category_id,product_code,product_name,subtitle,description,product_type,status,sort_no)
select g.id,c.id,'valorant-ranked-hour','无畏契约排位陪玩','按小时计费，可连续下单','双排或组队排位陪玩服务','SERVICE','ON_SALE',2 from pw_game g join pw_product_category c on c.category_code='valorant-ranked' where g.game_code='valorant' and not exists(select 1 from pw_product where product_code='valorant-ranked-hour');
insert into pw_product_service(product_id,service_id) select p.id,s.id from pw_product p join pw_service_item s on s.service_code='valorant-ranked' where p.product_code='valorant-ranked-hour' and not exists(select 1 from pw_product_service x where x.product_id=p.id and x.service_id=s.id);
insert into pw_product_sku(product_id,sku_code,sku_name,price,unit_type,unit_count,min_quantity,max_quantity,stock_mode,service_minutes,enabled,sort_no) select id,'valorant-ranked-1h','排位陪玩 1 小时',58.00,'HOUR',1,1,8,'UNLIMITED',60,true,1 from pw_product where product_code='valorant-ranked-hour' and not exists(select 1 from pw_product_sku where sku_code='valorant-ranked-1h');
