<template>
  <div class="art-full-height">
    <ElCard class="mb-3"><ElForm inline><ElFormItem label="申请类型"><ElSelect v-model="query.type" clearable class="!w-36"><ElOption label="转单" value="TRANSFER"/><ElOption label="炸单" value="ABORT"/></ElSelect></ElFormItem><ElFormItem label="状态"><ElSelect v-model="query.status" clearable class="!w-40"><ElOption label="待审核" value="PENDING"/><ElOption label="待接替人确认" value="WAIT_TARGET"/><ElOption label="已完成" value="RESOLVED"/><ElOption label="已驳回" value="REJECTED"/></ElSelect></ElFormItem><ElButton type="primary" @click="load">查询</ElButton></ElForm></ElCard>
    <ElCard><ElTable v-loading="loading" :data="rows"><ElTableColumn prop="request_no" label="申请单号" min-width="190"/><ElTableColumn prop="order_no" label="订单号" min-width="190"/><ElTableColumn label="类型" width="85"><template #default="{row}"><ElTag :type="row.request_type==='ABORT'?'danger':'warning'">{{row.request_type==='ABORT'?'炸单':'转单'}}</ElTag></template></ElTableColumn><ElTableColumn prop="applicant_name" label="申请人" width="110"/><ElTableColumn prop="source_player_name" label="转出成员" width="110"/><ElTableColumn prop="target_player_name" label="接替成员" width="110"/><ElTableColumn prop="reason" label="原因" min-width="180" show-overflow-tooltip/><ElTableColumn label="责任金额" width="125"><template #default="{row}"><span v-if="row.liability_amount!=null">¥{{row.liability_amount}}（{{Number(row.liability_rate)*100}}%）</span><span v-else>-</span></template></ElTableColumn><ElTableColumn prop="liability_base" label="计费基数" width="100"/><ElTableColumn label="状态" width="120"><template #default="{row}">{{statusText(row.request_status)}}</template></ElTableColumn><ElTableColumn label="操作" width="150"><template #default="{row}"><template v-if="row.request_status==='PENDING'"><ElButton link type="success" @click="review(row,'APPROVE')">通过</ElButton><ElButton link type="danger" @click="review(row,'REJECT')">驳回</ElButton></template><span v-else>-</span></template></ElTableColumn></ElTable><div class="flex justify-end mt-4"><ElPagination v-model:current-page="query.current" :page-size="query.size" :total="total" @change="load" layout="total,prev,pager,next"/></div></ElCard>
  </div>
</template>
<script setup lang="ts">
import{fetchServiceExceptions,reviewServiceException}from'@/api/business-manage';const loading=ref(false),rows=ref<any[]>([]),total=ref(0),query=reactive({current:1,size:20,status:'PENDING',type:''});async function load(){loading.value=true;try{const d=await fetchServiceExceptions(query);rows.value=d.records;total.value=d.total}finally{loading.value=false}}async function review(row:any,action:string){let remark='';if(action==='REJECT')remark=await ElMessageBox.prompt('请输入驳回原因','驳回申请',{inputValidator:v=>Boolean(v)||'请输入驳回原因'}).then(x=>x.value);else await ElMessageBox.confirm(row.request_type==='TRANSFER'?'通过后将等待目标陪玩师确认接替，是否继续？':'通过炸单后将终止服务并按取消流程退款，是否继续？','审核确认',{type:'warning'});await reviewServiceException(row.id,action,remark);ElMessage.success('审核完成');load()}const statusText=(s:string)=>({PENDING:'待审核',WAIT_TARGET:'待接替人确认',RESOLVED:'已完成',APPROVED:'炸单已通过',REJECTED:'审核驳回',TARGET_REJECTED:'接替人拒绝'}[s]||s);onMounted(load)
</script>
