package com.peiwan.platform.dispatch;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;import java.time.format.DateTimeFormatter;import java.util.*;

@Service public class DispatchService{
  private final DispatchDataMapper data;private final OrderMapper orders;private final DispatchTaskMapper tasks;private final DispatchCandidateMapper candidates;private final DispatchActionLogMapper actionLogs;private final PlayerMapper players;private final OrderStatusLogMapper orderLogs;public DispatchService(DispatchDataMapper data,OrderMapper orders,DispatchTaskMapper tasks,DispatchCandidateMapper candidates,DispatchActionLogMapper actionLogs,PlayerMapper players,OrderStatusLogMapper orderLogs){this.data=data;this.orders=orders;this.tasks=tasks;this.candidates=candidates;this.actionLogs=actionLogs;this.players=players;this.orderLogs=orderLogs;}
  @Transactional public Map<String,Object> list(int current,int size,String taskNo,String status,String mode){expireDue();current=Math.max(1,current);size=Math.min(200,Math.max(1,size));var result=data.tasks(new Page<>(current,size),Objects.toString(taskNo,""),status,mode);return Map.of("records",result.getRecords().stream().map(this::taskView).toList(),"current",current,"size",size,"total",result.getTotal());}
  @Transactional public Map<String,Object> detail(long id){expireDue();var task=taskView(requireTask(id));task.put("candidates",data.candidates(id).stream().map(this::candidateView).toList());task.put("logs",data.logs(id).stream().map(this::logView).toList());return task;}
  public List<Map<String,Object>> eligible(long orderId){var order=requireOrder(orderId);if(!"WAIT_ASSIGN".equals(order.get("order_status")))throw new IllegalArgumentException("只有待派单订单可以筛选候选人");return eligibleRows(orderId,rule()).stream().map(this::candidatePreview).toList();}

  @Transactional public long create(long orderId,String mode,Long targetPlayerId,long operator){expireDue();if(!Set.of("DIRECT","GRAB").contains(mode))throw new IllegalArgumentException("派单模式无效");var order=requireOrder(orderId);if(!"WAIT_ASSIGN".equals(order.get("order_status")))throw new IllegalArgumentException("只有待派单订单可以发起派单");if(tasks.selectCount(new QueryWrapper<DispatchTaskEntity>().eq("order_id",orderId).eq("task_status","DISPATCHING"))>0)throw new IllegalArgumentException("该订单已有进行中的派单任务");var rule=rule();var rows=eligibleRows(orderId,rule);if("DIRECT".equals(mode)){if(targetPlayerId==null)throw new IllegalArgumentException("指定派单必须选择陪玩师");rows=rows.stream().filter(x->Objects.equals(((Number)x.get("id")).longValue(),targetPlayerId)).toList();if(rows.isEmpty())throw new IllegalArgumentException("所选陪玩师当前不符合接单条件");}if(rows.isEmpty())throw new IllegalArgumentException("没有符合条件的陪玩师");int attempt=Math.toIntExact(tasks.selectCount(new QueryWrapper<DispatchTaskEntity>().eq("order_id",orderId)))+1;var task=new DispatchTaskEntity();task.taskNo=taskNo();task.orderId=orderId;task.dispatchMode=mode;task.taskStatus="DISPATCHING";task.targetPlayerId=targetPlayerId;task.attemptNo=attempt;task.candidateCount=rows.size();task.deadlineAt=LocalDateTime.now().plusMinutes(((Number)rule.get("grab_minutes")).intValue());task.createdBy=operator;tasks.insert(task);for(var row:rows){var c=new DispatchCandidateEntity();c.taskId=task.id;c.playerId=((Number)row.get("id")).longValue();c.matchScore=java.math.BigDecimal.valueOf(((Number)row.get("match_score")).doubleValue());c.activeOrderCount=((Number)row.get("active_count")).intValue();c.candidateStatus="PENDING";c.notified=true;candidates.insert(c);}log(task.id,orderId,targetPlayerId,"CREATE",null,"DISPATCHING",operator,"DIRECT".equals(mode)?"指定派单":"发布抢单");return task.id;}
  @Transactional public void respond(long taskId,long playerId,String action,String reason,long operator){expireDue();var task=requireTask(taskId);if(!"DISPATCHING".equals(task.get("task_status")))throw new IllegalArgumentException("派单任务已结束");var candidate=candidates.selectOne(new QueryWrapper<DispatchCandidateEntity>().eq("task_id",taskId).eq("player_id",playerId));if(candidate==null)throw new IllegalArgumentException("陪玩师不在候选列表中");if(!"PENDING".equals(candidate.candidateStatus))throw new IllegalArgumentException("该候选人已经响应");long orderId=((Number)task.get("order_id")).longValue();if("REJECT".equals(action)){if(data.rejectCandidate(candidate.id,reason)==0)throw new IllegalArgumentException("该候选人已经响应");log(taskId,orderId,playerId,"REJECT","PENDING","REJECTED",operator,reason);if(candidates.selectCount(new QueryWrapper<DispatchCandidateEntity>().eq("task_id",taskId).eq("candidate_status","PENDING"))==0&&data.rejectTask(taskId)>0)log(taskId,orderId,null,"CLOSE","DISPATCHING","REJECTED",operator,"所有候选人均已拒绝");return;}if(!"ACCEPT".equals(action))throw new IllegalArgumentException("响应类型无效");if(data.acceptTask(taskId,playerId)==0)throw new IllegalArgumentException("任务已被其他陪玩师接单或已经超时");if(data.assignOrder(orderId,playerId)==0)throw new IllegalArgumentException("订单状态已变化，接单失败");data.closeCandidates(taskId,playerId);var p=players.selectById(playerId);if(p!=null){p.workStatus="BUSY";p.updatedAt=LocalDateTime.now();players.updateById(p);}log(taskId,orderId,playerId,"ACCEPT","PENDING","ACCEPTED",operator,reason);var ol=new OrderStatusLogEntity();ol.orderId=orderId;ol.fromStatus="WAIT_ASSIGN";ol.toStatus="ASSIGNED";ol.operatorId=operator;ol.reason="派单任务"+task.get("task_no")+"接单成功";orderLogs.insert(ol);}
  @Transactional public void cancel(long taskId,String reason,long operator){expireDue();var task=requireTask(taskId);if(data.cancelTask(taskId)==0)throw new IllegalArgumentException("只有派单中的任务可以取消");data.cancelCandidates(taskId);log(taskId,((Number)task.get("order_id")).longValue(),null,"CANCEL","DISPATCHING","CANCELLED",operator,reason);}

  private List<Map<String,Object>> eligibleRows(long orderId,Map<String,Object> rule){Long gameId=data.orderGame(orderId);if(gameId==null)throw new IllegalArgumentException("订单缺少游戏资料");boolean allowBusy=Boolean.TRUE.equals(rule.get("allow_busy"));int platformMax=((Number)rule.get("max_active_orders")).intValue(),limit=((Number)rule.get("max_candidates")).intValue();var rows=data.eligible(gameId,allowBusy,platformMax,limit);for(var x:rows){double rating=((Number)x.get("rating_score")).doubleValue(),active=((Number)x.get("active_count")).doubleValue(),primary=Boolean.TRUE.equals(x.get("is_primary"))?5:0;x.put("effective_max_orders",Math.min(((Number)x.get("max_active_orders")).intValue(),platformMax));x.put("match_score",Math.max(0,rating*20+primary-active*15));}rows.sort((a,b)->Double.compare(((Number)b.get("match_score")).doubleValue(),((Number)a.get("match_score")).doubleValue()));return rows;}
  private void expireDue(){for(var t:data.dueTasks()){long id=((Number)t.get("id")).longValue(),order=((Number)t.get("order_id")).longValue();if(data.expireTask(id)>0){data.timeoutCandidates(id);log(id,order,null,"EXPIRE","DISPATCHING","EXPIRED",null,"接单时间已截止");}}}
  private Map<String,Object> rule(){var x=data.enabledRule();if(x==null)throw new IllegalArgumentException("未配置启用的派单规则");return x;}private Map<String,Object> requireTask(long id){var x=data.task(id);if(x==null)throw new IllegalArgumentException("派单任务不存在");return x;}private Map<String,Object> requireOrder(long id){var o=orders.selectById(id);if(o==null)throw new IllegalArgumentException("订单不存在");var x=new HashMap<String,Object>();x.put("id",o.id);x.put("order_status",o.orderStatus);return x;}
  private void log(long task,long order,Long player,String action,String from,String to,Long operator,String reason){var l=new DispatchActionLogEntity();l.taskId=task;l.orderId=order;l.playerId=player;l.actionType=action;l.fromStatus=from;l.toStatus=to;l.operatorId=operator;l.reason=reason;actionLogs.insert(l);}private String taskNo(){return "DSP"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))+UUID.randomUUID().toString().replace("-","").substring(0,5).toUpperCase();}
  private Map<String,Object> taskView(Map<String,Object>r){return view(r,new String[][]{{"id","id"},{"taskNo","task_no"},{"orderId","order_id"},{"orderNo","order_no"},{"orderStatus","order_status"},{"dispatchMode","dispatch_mode"},{"taskStatus","task_status"},{"targetPlayerId","target_player_id"},{"acceptedPlayerId","accepted_player_id"},{"acceptedPlayerName","accepted_player_name"},{"attemptNo","attempt_no"},{"candidateCount","candidate_count"},{"deadlineAt","deadline_at"},{"createTime","created_at"},{"acceptedAt","accepted_at"}});}private Map<String,Object> candidateView(Map<String,Object>r){return view(r,new String[][]{{"id","id"},{"playerId","player_id"},{"playerNo","player_no"},{"playerName","nickname"},{"workStatus","work_status"},{"ratingScore","rating_score"},{"matchScore","match_score"},{"activeOrderCount","active_order_count"},{"candidateStatus","candidate_status"},{"notified","notified"},{"respondedAt","responded_at"},{"rejectReason","reject_reason"}});}private Map<String,Object> candidatePreview(Map<String,Object>r){return view(r,new String[][]{{"playerId","id"},{"playerNo","player_no"},{"playerName","nickname"},{"workStatus","work_status"},{"ratingScore","rating_score"},{"matchScore","match_score"},{"activeOrderCount","active_count"},{"primaryGame","is_primary"}});}private Map<String,Object> logView(Map<String,Object>r){return view(r,new String[][]{{"id","id"},{"playerId","player_id"},{"playerName","player_name"},{"actionType","action_type"},{"fromStatus","from_status"},{"toStatus","to_status"},{"operatorName","operator_name"},{"reason","reason"},{"createTime","created_at"}});}private Map<String,Object> view(Map<String,Object>r,String[][]keys){var x=new LinkedHashMap<String,Object>();for(var k:keys)if(r.containsKey(k[1]))x.put(k[0],r.get(k[1]));return x;}
}
