package com.peiwan.platform.dispatch;
import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController @RequestMapping("/api/business/dispatch") public class DispatchController{private final DispatchService service;private final AuditService audit;public DispatchController(DispatchService s,AuditService a){service=s;audit=a;}
@PreAuthorize("hasAuthority('business:dispatch:list') or hasRole('admin')") @GetMapping("/list") public ApiResponse<?> list(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String taskNo,@RequestParam(required=false)String taskStatus,@RequestParam(required=false)String dispatchMode){return ApiResponse.ok(service.list(current,size,taskNo,taskStatus,dispatchMode));}
@PreAuthorize("hasAuthority('business:dispatch:list') or hasRole('admin')") @GetMapping("/{id}") public ApiResponse<?> detail(@PathVariable long id){return ApiResponse.ok(service.detail(id));}
@PreAuthorize("hasAuthority('business:dispatch:create') or hasRole('admin')") @GetMapping("/eligible/{orderId}") public ApiResponse<?> eligible(@PathVariable long orderId){return ApiResponse.ok(service.eligible(orderId));}
@PreAuthorize("hasAuthority('business:dispatch:create') or hasRole('admin')") @PostMapping public ApiResponse<?> create(Authentication a,@RequestBody Create b,HttpServletRequest r){long id=service.create(b.orderId(),b.dispatchMode(),b.targetPlayerId(),uid(a));audit.operation(a,"business:dispatch:create","DISPATCH",id,b.dispatchMode(),r);return ApiResponse.ok(Map.of("id",id));}
@PreAuthorize("hasAuthority('business:dispatch-rule:view') or hasRole('admin')") @GetMapping("/rule") public ApiResponse<?> rule(){return ApiResponse.ok(service.adminRule());}
@PreAuthorize("hasAuthority('business:dispatch-rule:update') or hasRole('admin')") @PutMapping("/rule") public ApiResponse<?> rule(Authentication a,@RequestBody DispatchService.RuleCommand b,HttpServletRequest r){service.updateRule(b);audit.operation(a,"business:dispatch-rule:update","DISPATCH_RULE",null,b.ruleName(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:dispatch:respond') or hasRole('admin')") @PutMapping("/{id}/respond") public ApiResponse<?> respond(Authentication a,@PathVariable long id,@RequestBody Respond b,HttpServletRequest r){service.respond(id,b.playerId(),b.action(),b.reason(),uid(a));audit.operation(a,"business:dispatch:respond","DISPATCH",id,b.action()+":"+b.playerId(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:dispatch:cancel') or hasRole('admin')") @PutMapping("/{id}/cancel") public ApiResponse<?> cancel(Authentication a,@PathVariable long id,@RequestBody Cancel b,HttpServletRequest r){service.cancel(id,b.reason(),uid(a));audit.operation(a,"business:dispatch:cancel","DISPATCH",id,b.reason(),r);return ApiResponse.ok();}
private long uid(Authentication a){return(Long)a.getPrincipal();}public record Create(long orderId,String dispatchMode,Long targetPlayerId){}public record Respond(long playerId,String action,String reason){}public record Cancel(String reason){}
}
