package com.peiwan.platform.order;
import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController @RequestMapping("/api/business/order") public class OrderController{private final OrderService service;private final AuditService audit;public OrderController(OrderService s,AuditService a){service=s;audit=a;}
@PreAuthorize("hasAuthority('business:order:list') or hasRole('admin')") @GetMapping("/list") public ApiResponse<?> list(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String orderNo,@RequestParam(required=false)String customerName,@RequestParam(required=false)String orderStatus){return ApiResponse.ok(service.list(current,size,orderNo,customerName,orderStatus));}
@PreAuthorize("hasAuthority('business:order:list') or hasRole('admin')") @GetMapping("/{id}") public ApiResponse<?> detail(@PathVariable long id){return ApiResponse.ok(service.detail(id));}
@PreAuthorize("hasAuthority('business:order:create') or hasRole('admin')") @GetMapping("/customer-options") public ApiResponse<?> customers(){return ApiResponse.ok(service.customers());}
@PreAuthorize("hasAuthority('business:order:create') or hasRole('admin')") @GetMapping("/create-options") public ApiResponse<?> createOptions(@RequestParam long customerId,@RequestParam long gameId){return ApiResponse.ok(service.createOptions(customerId,gameId));}
@PreAuthorize("hasAuthority('business:order:assign') or hasRole('admin')") @GetMapping("/player-options") public ApiResponse<?> players(){return ApiResponse.ok(service.players());}
@PreAuthorize("hasAuthority('business:order:create') or hasRole('admin')") @PostMapping public ApiResponse<?> create(Authentication a,@RequestBody OrderService.CreateCommand b,HttpServletRequest r){long id=service.create(b,userId(a));audit.operation(a,"business:order:create","ORDER",id,"创建订单",r);return ApiResponse.ok(Map.of("id",id));}
@PreAuthorize("hasAuthority('business:order:status') or hasRole('admin')") @PostMapping("/{id}/pay") public ApiResponse<?> pay(Authentication a,@PathVariable long id,@RequestBody Pay b,HttpServletRequest r){service.confirmPayment(id,b.paymentChannel(),userId(a));audit.operation(a,"business:order:status","ORDER",id,"后台确认收款",r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:order:status') or hasRole('admin')") @PutMapping("/{id}/status") public ApiResponse<?> status(Authentication a,@PathVariable long id,@RequestBody Status b,HttpServletRequest r){service.changeStatus(id,b.status(),b.reason(),userId(a));audit.operation(a,"business:order:status","ORDER",id,b.status(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:order:assign') or hasRole('admin')") @PutMapping("/{id}/assign") public ApiResponse<?> assign(Authentication a,@PathVariable long id,@RequestBody Assign b,HttpServletRequest r){service.assign(id,b.playerId(),b.reason(),userId(a));audit.operation(a,"business:order:assign","ORDER",id,"player="+b.playerId(),r);return ApiResponse.ok();}
private long userId(Authentication a){return (Long)a.getPrincipal();}public record Status(String status,String reason){}public record Assign(long playerId,String reason){}public record Pay(String paymentChannel){}
}
