<template>
  <div class="art-full-height">
    <ElCard shadow="never" class="mb-4"><div class="header"><div><div class="title">结算管理</div><div class="subtitle">提现审核、抽佣规则和财务报表</div></div><div><ElButton v-auth="'business:settlement:rule'" @click="openRule">抽佣规则</ElButton><ElDropdown v-auth="'business:settlement:export'" class="ml-3" @command="exportReport"><ElButton type="primary">导出报表<ElIcon class="ml-1"><ArrowDown/></ElIcon></ElButton><template #dropdown><ElDropdownMenu><ElDropdownItem command="earning">收入明细报表</ElDropdownItem><ElDropdownItem command="withdrawal">提现审核报表</ElDropdownItem></ElDropdownMenu></template></ElDropdown></div></div></ElCard>
    <ElCard shadow="never"><ElForm inline><ElFormItem label="提现状态"><ElSelect v-model="query.status" clearable class="!w-40"><ElOption label="待审核" value="PENDING"/><ElOption label="已打款" value="PAID"/><ElOption label="已驳回" value="REJECTED"/></ElSelect></ElFormItem><ElFormItem><ElButton type="primary" @click="search">查询</ElButton><ElButton @click="reset">重置</ElButton></ElFormItem></ElForm>
      <ElTable v-loading="loading" :data="rows" empty-text="暂无提现申请"><ElTableColumn prop="withdrawal_no" label="提现单号" min-width="190"/><ElTableColumn prop="player_no" label="陪玩师编号" width="140"/><ElTableColumn prop="nickname" label="陪玩师" width="120"/><ElTableColumn prop="amount" label="提现金额" width="120"><template #default="{row}"><strong>¥ {{money(row.amount)}}</strong></template></ElTableColumn><ElTableColumn prop="payout_method" label="收款方式" width="100"><template #default="{row}">{{methodText(row.payout_method)}}</template></ElTableColumn><ElTableColumn prop="account_name" label="收款人" width="120"/><ElTableColumn prop="account_no" label="收款账号" min-width="170"/><ElTableColumn label="状态" width="100"><template #default="{row}"><ElTag :type="statusType(row.withdrawal_status)">{{statusText(row.withdrawal_status)}}</ElTag></template></ElTableColumn><ElTableColumn prop="created_at" label="申请时间" width="180"/><ElTableColumn prop="review_remark" label="审核说明" min-width="160" show-overflow-tooltip/><ElTableColumn label="操作" width="150" fixed="right"><template #default="{row}"><template v-if="row.withdrawal_status==='PENDING'"><ElButton v-auth="'business:settlement:audit'" link type="success" @click="audit(row,'APPROVE')">通过</ElButton><ElButton v-auth="'business:settlement:audit'" link type="danger" @click="audit(row,'REJECT')">驳回</ElButton></template><span v-else class="muted">已处理</span></template></ElTableColumn></ElTable>
      <div class="pagination"><ElPagination v-model:current-page="query.current" v-model:page-size="query.size" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></div>
    </ElCard>
    <ElDialog v-model="ruleVisible" title="抽佣与提现规则" width="520px"><ElAlert class="mb-4" type="warning" :closable="false" title="新规则只影响后续完成的订单和新提交的提现申请，历史收入不会重新计算。"/><ElForm label-width="120px"><ElFormItem label="平台抽佣比例" required><ElInputNumber v-model="ruleForm.ratePercent" :min="0" :max="99" :precision="2"/><span class="suffix">%</span></ElFormItem><ElFormItem label="陪玩师实得"><strong>{{(100-ruleForm.ratePercent).toFixed(2)}}%</strong></ElFormItem><ElFormItem label="最低提现金额" required><ElInputNumber v-model="ruleForm.minWithdrawAmount" :min="0.01" :precision="2"/><span class="suffix">元</span></ElFormItem><ElFormItem label="允许提现日" required><ElSelect v-model="ruleForm.withdrawWeekday" class="!w-48"><ElOption v-for="d in weekdays" :key="d.value" :label="d.label" :value="d.value"/></ElSelect></ElFormItem></ElForm><template #footer><ElButton @click="ruleVisible=false">取消</ElButton><ElButton type="primary" :loading="savingRule" @click="saveRule">保存规则</ElButton></template></ElDialog>
  </div>
</template>
<script setup lang="ts">
import{ArrowDown}from'@element-plus/icons-vue';import{saveAs}from'file-saver';import{fetchSettlementWithdrawals,auditSettlementWithdrawal,fetchSettlementRule,updateSettlementRule,downloadSettlementReport}from'@/api/business-manage'
const loading=ref(false),rows=ref<any[]>([]),total=ref(0),ruleVisible=ref(false),savingRule=ref(false),query=reactive({current:1,size:20,status:'PENDING'}),ruleForm=reactive({ratePercent:28,minWithdrawAmount:300,withdrawWeekday:1}),weekdays=[{label:'周一',value:1},{label:'周二',value:2},{label:'周三',value:3},{label:'周四',value:4},{label:'周五',value:5},{label:'周六',value:6},{label:'周日',value:7}]
async function load(){loading.value=true;try{const d=await fetchSettlementWithdrawals(query);rows.value=d.records;total.value=d.total}finally{loading.value=false}}function search(){query.current=1;load()}function reset(){query.status='';query.current=1;load()}
async function audit(row:any,action:string){let remark='';if(action==='REJECT')remark=await ElMessageBox.prompt('请输入驳回原因','驳回提现',{inputValidator:v=>Boolean(v)||'请输入驳回原因'}).then(x=>x.value);else await ElMessageBox.confirm(`确认已向 ${row.account_name} 打款 ¥ ${money(row.amount)} 吗？通过后将从冻结余额扣除。`,'审核通过',{type:'warning'});await auditSettlementWithdrawal(row.id,action,remark);ElMessage.success(action==='APPROVE'?'审核通过，已标记打款':'已驳回并退回余额');load()}
async function openRule(){const r=await fetchSettlementRule();Object.assign(ruleForm,{ratePercent:Number(r.commission_rate??r.commissionRate)*100,minWithdrawAmount:Number(r.min_withdraw_amount??r.minWithdrawAmount),withdrawWeekday:Number(r.withdraw_weekday??r.withdrawWeekday)});ruleVisible.value=true}async function saveRule(){savingRule.value=true;try{await updateSettlementRule({commissionRate:ruleForm.ratePercent/100,minWithdrawAmount:ruleForm.minWithdrawAmount,withdrawWeekday:ruleForm.withdrawWeekday});ElMessage.success('结算规则已更新');ruleVisible.value=false}finally{savingRule.value=false}}
async function exportReport(type:'earning'|'withdrawal'){const blob=await downloadSettlementReport(type);saveAs(blob,`${type==='earning'?'收入明细':'提现审核'}-${new Date().toISOString().slice(0,10)}.csv`);ElMessage.success('报表已导出')}
const money=(v:any)=>Number(v||0).toFixed(2),statusText=(s:string)=>({PENDING:'待审核',PAID:'已打款',REJECTED:'已驳回'}[s]||s),statusType=(s:string)=>(s==='PAID'?'success':s==='REJECTED'?'danger':'warning') as any,methodText=(s:string)=>({BANK:'银行卡',ALIPAY:'支付宝',WECHAT:'微信'}[s]||s)
onMounted(load)
</script>
<style scoped>.header{display:flex;align-items:center;justify-content:space-between}.title{font-size:18px;font-weight:600}.subtitle,.muted{color:var(--el-text-color-secondary);font-size:13px;margin-top:5px}.pagination{display:flex;justify-content:flex-end;margin-top:18px}.suffix{margin-left:10px;color:var(--el-text-color-secondary)}</style>
