package com.peiwan.platform.settlement;
import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.time.LocalDate;
@RestController public class SettlementController{private final SettlementService service;private final AuditService audit;public SettlementController(SettlementService service,AuditService audit){this.service=service;this.audit=audit;}
 @PreAuthorize("hasAuthority('player:settlement:view')") @GetMapping("/api/player/settlement") public ApiResponse<?> summary(Authentication a){return ApiResponse.ok(service.summary(uid(a)));}
 @PreAuthorize("hasAuthority('player:settlement:view')") @GetMapping("/api/player/settlement/earnings") public ApiResponse<?> earnings(Authentication a,@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(service.earnings(uid(a),current,size));}
 @PreAuthorize("hasAuthority('player:settlement:view')") @GetMapping("/api/player/withdrawals") public ApiResponse<?> ownWithdrawals(Authentication a,@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(service.ownWithdrawals(uid(a),current,size));}
 @PreAuthorize("hasAuthority('player:withdraw:create')") @PostMapping("/api/player/withdrawals") public ApiResponse<?> withdraw(Authentication a,@RequestBody SettlementService.WithdrawCommand b,HttpServletRequest r){long id=service.withdraw(uid(a),b);audit.operation(a,"player:withdraw:create","WITHDRAWAL",id,"amount="+b.amount(),r);return ApiResponse.ok(java.util.Map.of("id",id));}
 @PreAuthorize("hasAuthority('business:settlement:list')") @GetMapping("/api/business/settlement/withdrawals") public ApiResponse<?> list(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String status){return ApiResponse.ok(service.adminList(current,size,status));}
 @PreAuthorize("hasAuthority('business:settlement:audit')") @PutMapping("/api/business/settlement/withdrawals/{id}/audit") public ApiResponse<?> audit(Authentication a,@PathVariable long id,@RequestBody AuditCommand b,HttpServletRequest r){service.audit(id,b.action(),b.remark(),uid(a));audit.operation(a,"business:settlement:audit","WITHDRAWAL",id,b.action(),r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:settlement:rule')") @GetMapping("/api/business/settlement/rule") public ApiResponse<?> rule(){return ApiResponse.ok(service.adminRule());}
 @PreAuthorize("hasAuthority('business:settlement:rule')") @PutMapping("/api/business/settlement/rule") public ApiResponse<?> rule(Authentication a,@RequestBody SettlementService.RuleCommand b,HttpServletRequest r){service.updateRule(b);audit.operation(a,"business:settlement:rule","COMMISSION_RULE",null,b.commissionRate().toPlainString(),r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:settlement:export')") @GetMapping("/api/business/settlement/export") public ResponseEntity<byte[]> export(@RequestParam String type){String name=("withdrawal".equals(type)?"withdrawals-":"earnings-")+LocalDate.now()+".csv";return ResponseEntity.ok().contentType(new MediaType("text","csv",java.nio.charset.StandardCharsets.UTF_8)).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename="+name).body(service.export(type));}
 private long uid(Authentication a){return(Long)a.getPrincipal();}public record AuditCommand(String action,String remark){}
}
