<template>
  <view class="detail-page">
    <view class="status-hero" :class="statusTone"><view class="status-icon"><image :src="statusIcon" /></view><view><view class="status-title">{{ statusText }}</view><text>{{ statusDescription }}</text></view></view>

    <view class="section"><view class="section-title">服务信息</view><view class="service-row"><view class="game-icon"><image src="/static/icons/gamepad.svg"/></view><view><view>{{ game.gameName || detail.productName || '陪玩服务' }}</view><text>{{ firstItem.skuName || firstItem.productName || '默认服务规格' }}</text></view></view><view class="field"><text>区服 / 段位</text><label>{{ [game.serverName,game.rankName].filter(Boolean).join(' · ') || '未填写' }}</label></view><view class="field"><text>游戏昵称</text><label>{{ game.gameNickname || '未填写' }}</label></view><view class="field"><text>服务要求</text><label class="wrap">{{ game.extraRequirement || detail.customerRemark || '无额外要求' }}</label></view></view>

    <view class="section"><view class="section-title">联系与时间</view><view class="field"><text>联系人</text><label>{{ detail.contactName || '未填写' }}</label></view><view class="field"><text>联系电话</text><label>{{ detail.contactPhone || '未填写' }}</label></view><view class="field"><text>接单时间</text><label>{{ formatTime(detail.assignedAt) }}</label></view><view class="field"><text>开始时间</text><label>{{ formatTime(detail.serviceStartedAt) }}</label></view></view>

    <view class="section amount-section"><view class="field"><text>商品金额</text><label>¥{{ money(detail.totalAmount) }}</label></view><view class="field total"><text>订单实付</text><label>¥{{ money(detail.payableAmount) }}</label></view></view>

    <view v-if="showProgress" class="section"><view class="section-title">完成确认进度</view><view class="progress"><view class="step done"><view>✓</view><text>陪玩提交</text></view><view class="line" :class="{ done: isReviewed }"/><view class="step" :class="{ done: isReviewed }"><view>{{ isReviewed?'✓':'2' }}</view><text>平台审核</text></view><view class="line" :class="{ done: detail.orderStatus==='COMPLETED' }"/><view class="step" :class="{ done: detail.orderStatus==='COMPLETED' }"><view>{{ detail.orderStatus==='COMPLETED'?'✓':'3' }}</view><text>顾客确认</text></view></view><view class="progress-tip">{{ statusDescription }}</view></view>

    <view class="section"><view class="section-title">订单信息</view><view class="field"><text>订单编号</text><label selectable>{{ detail.orderNo }}</label></view><view class="field"><text>创建时间</text><label>{{ formatTime(detail.createTime) }}</label></view></view>

    <view class="bottom-actions"><button v-if="detail.orderStatus==='ASSIGNED'" class="primary" @click="start">开始服务</button><button v-else-if="detail.orderStatus==='IN_SERVICE'" class="primary" @click="submit">提交完成</button><button v-else-if="isAbnormal" class="danger" @click="contact">联系客服处理</button><button v-else class="outline" @click="contact">联系平台客服</button></view>
  </view>
</template>

<script setup lang="ts">
import{computed,ref}from'vue';import{onLoad}from'@dcloudio/uni-app';import{getPlayerOrder,startOrder}from'@/api/player';import type{RecordData}from'@/types/api';const id=ref(0),detail=ref<RecordData>({});const game=computed(()=>(detail.value.gameProfile||{})as RecordData);const firstItem=computed(()=>((detail.value.items as RecordData[]||[])[0]||{}));const statuses:Record<string,{text:string;desc:string;tone:string;icon:string}>={ASSIGNED:{text:'待开始服务',desc:'请核对服务信息，确认后开始服务',tone:'waiting',icon:'/static/icons/hourglass.svg'},IN_SERVICE:{text:'服务进行中',desc:'服务完成后请及时上传履约凭证',tone:'working',icon:'/static/icons/gamepad.svg'},PENDING_CONFIRM:{text:'平台审核中',desc:'完成凭证已提交，正在等待平台审核',tone:'review',icon:'/static/icons/hourglass.svg'},WAIT_CUSTOMER_CONFIRM:{text:'等待顾客确认',desc:'平台已审核通过，等待顾客确认服务完成',tone:'review',icon:'/static/icons/check.svg'},COMPLETED:{text:'服务已完成',desc:'本次陪玩服务已经完成',tone:'done',icon:'/static/icons/check.svg'},CANCELLED:{text:'订单已取消',desc:'订单存在异常或已被取消',tone:'abnormal',icon:'/static/icons/alert.svg'},AFTER_SALE:{text:'售后处理中',desc:'平台正在处理本订单的售后问题',tone:'abnormal',icon:'/static/icons/after-sale.svg'}};const meta=computed(()=>statuses[String(detail.value.orderStatus)]||{text:String(detail.value.orderStatus||'订单详情'),desc:'查看订单服务信息',tone:'waiting',icon:'/static/icons/orders-active.svg'});const statusText=computed(()=>meta.value.text),statusDescription=computed(()=>meta.value.desc),statusTone=computed(()=>meta.value.tone),statusIcon=computed(()=>meta.value.icon),showProgress=computed(()=>['PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','COMPLETED'].includes(String(detail.value.orderStatus))),isReviewed=computed(()=>['WAIT_CUSTOMER_CONFIRM','COMPLETED'].includes(String(detail.value.orderStatus))),isAbnormal=computed(()=>['CANCELLED','AFTER_SALE'].includes(String(detail.value.orderStatus)));onLoad(async q=>{id.value=Number(q?.id);await load()});async function load(){detail.value=await getPlayerOrder(id.value)}function formatTime(value:unknown){return value?String(value).replace('T',' ').slice(0,16):'--'}function money(value:unknown){return Number(value||0).toFixed(2)}function submit(){uni.navigateTo({url:`/subpackages/player/submit?id=${id.value}`})}function start(){uni.showModal({title:'开始服务',content:'确认已核对游戏资料与服务要求？',confirmText:'确认开始',success:async result=>{if(result.confirm){await startOrder(id.value);uni.showToast({title:'服务已开始'});await load()}}})}function contact(){uni.showModal({title:'联系平台客服',content:`请保留订单 ${detail.value.orderNo||''} 的相关凭证并联系平台管理员处理。`,showCancel:false,confirmText:'我知道了'})}
</script>

<style scoped lang="scss">
.detail-page{min-height:100vh;padding:24rpx 24rpx 180rpx;background:#f5f6fa}.status-hero{padding:34rpx;border-radius:25rpx;display:flex;align-items:center;gap:22rpx;color:#fff}.status-hero.waiting{background:linear-gradient(110deg,#7659ef,#947cf4)}.status-hero.working{background:linear-gradient(110deg,#159d9a,#35bcb4)}.status-hero.review{background:linear-gradient(110deg,#dc8733,#f0a64f)}.status-hero.done{background:linear-gradient(110deg,#617083,#8593a4)}.status-hero.abnormal{background:linear-gradient(110deg,#d94e6b,#ec7890)}.status-icon{width:76rpx;height:76rpx;border-radius:22rpx;display:flex;align-items:center;justify-content:center;background:rgba(255,255,255,.9)}.status-icon image{width:49rpx;height:49rpx}.status-title{font-size:34rpx;font-weight:800}.status-hero text{display:block;margin-top:9rpx;color:rgba(255,255,255,.75);font-size:21rpx}.section{margin-top:22rpx;padding:27rpx;border-radius:24rpx;background:#fff}.section-title{margin-bottom:20rpx;font-size:28rpx;font-weight:800}.service-row{display:flex;align-items:center;gap:17rpx;margin-bottom:15rpx;padding-bottom:22rpx;border-bottom:1rpx solid #eee}.game-icon{width:70rpx;height:70rpx;border-radius:19rpx;display:flex;align-items:center;justify-content:center;background:#f0edff}.game-icon image{width:44rpx;height:44rpx}.service-row>view:last-child view{font-weight:700}.service-row text{display:block;margin-top:7rpx;color:#9296a4;font-size:21rpx}.field{min-height:74rpx;display:flex;align-items:center;justify-content:space-between;gap:30rpx;border-bottom:1rpx solid #f1f2f4}.field:last-child{border:0}.field text{flex:none;color:#9196a4;font-size:22rpx}.field label{color:#454956;font-size:22rpx;text-align:right}.field label.wrap{padding:15rpx 0;line-height:1.5}.amount-section .field label{font-weight:700}.amount-section .total label{color:#eb5c83;font-size:29rpx}.progress{padding:20rpx 5rpx;display:flex;align-items:flex-start}.step{width:105rpx;text-align:center;color:#b1b5c0}.step view{width:45rpx;height:45rpx;margin:auto;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#fff;background:#c9ccd4;font-size:20rpx}.step text{display:block;margin-top:10rpx;font-size:19rpx}.step.done{color:#7357ef}.step.done view{background:#7357ef}.line{flex:1;height:4rpx;margin-top:21rpx;background:#e3e4e9}.line.done{background:#7357ef}.progress-tip{padding:16rpx;border-radius:14rpx;color:#866b3e;background:#fff7e9;font-size:20rpx;text-align:center}.bottom-actions{position:fixed;z-index:20;left:0;right:0;bottom:0;padding:20rpx 24rpx calc(20rpx + env(safe-area-inset-bottom));background:#fff;box-shadow:0 -8rpx 30rpx rgba(38,40,55,.08)}.bottom-actions button{height:84rpx;line-height:84rpx;border-radius:18rpx}.outline{color:#7357ef;background:#fff;border:2rpx solid #7357ef}.danger{color:#fff;background:#dc5a70}
</style>
