package com.peiwan.platform.system;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.stereotype.Repository;import java.util.*;
@Repository public class RbacRepository{
 private final SystemUserMapper users;private final SystemRoleMapper roleMapper;private final SystemMenuMapper menuMapper;private final SystemAccessMapper access;
 public RbacRepository(SystemUserMapper users,SystemRoleMapper roleMapper,SystemMenuMapper menuMapper,SystemAccessMapper access){this.users=users;this.roleMapper=roleMapper;this.menuMapper=menuMapper;this.access=access;}
 public Optional<Map<String,Object>> userByName(String name){return Optional.ofNullable(users.selectOne(new QueryWrapper<SystemUserEntity>().eq("username",name))).map(this::userMap);}public Optional<Map<String,Object>> user(long id){return Optional.ofNullable(users.selectById(id)).map(this::userMap);}public Optional<Map<String,Object>> role(long id){return Optional.ofNullable(roleMapper.selectById(id)).map(this::roleMap);}public Optional<Map<String,Object>> menu(long id){return Optional.ofNullable(menuMapper.selectById(id)).map(this::menuMap);}
 public boolean userEnabled(long id){return user(id).map(x->Boolean.TRUE.equals(x.get("enabled"))).orElse(false);}public List<String> roles(long id){return access.roleCodes(id);}public List<Long> roleIds(long id){return access.roleIds(id);}public List<String> buttons(long id){return access.buttonCodes(id);}public List<Map<String,Object>> menus(long id){return access.userMenus(id);}public List<Map<String,Object>> allMenus(){return menuMapper.selectList(new QueryWrapper<SystemMenuEntity>().orderByAsc("sort_no","id")).stream().map(this::menuMap).toList();}public boolean hasRole(long uid,String code){return roles(uid).contains(code);}public long enabledAdminCount(){return access.enabledAdminCount();}public boolean isEnabledAdmin(long uid){return userEnabled(uid)&&hasRole(uid,"admin");}
 private Map<String,Object> userMap(SystemUserEntity e){var m=new LinkedHashMap<String,Object>();m.put("id",e.id);m.put("username",e.username);m.put("password",e.password);m.put("nickname",e.nickname);m.put("email",e.email);m.put("phone",e.phone);m.put("gender",e.gender);m.put("avatar",e.avatar);m.put("enabled",e.enabled);m.put("created_at",e.createdAt);m.put("updated_at",e.updatedAt);return m;}private Map<String,Object> roleMap(SystemRoleEntity e){var m=new LinkedHashMap<String,Object>();m.put("id",e.id);m.put("name",e.name);m.put("code",e.code);m.put("description",e.description);m.put("enabled",e.enabled);m.put("built_in",e.builtIn);m.put("created_at",e.createdAt);return m;}private Map<String,Object> menuMap(SystemMenuEntity e){var m=new LinkedHashMap<String,Object>();m.put("id",e.id);m.put("parent_id",e.parentId);m.put("type",e.type);m.put("name",e.name);m.put("path",e.path);m.put("component",e.component);m.put("title",e.title);m.put("icon",e.icon);m.put("auth_mark",e.authMark);m.put("sort_no",e.sortNo);m.put("hidden",e.hidden);m.put("enabled",e.enabled);m.put("keep_alive",e.keepAlive);m.put("created_at",e.createdAt);m.put("updated_at",e.updatedAt);return m;}
}
