package com.peiwan.platform.persistence.mapper;import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.apache.ibatis.annotations.*;import java.util.*;
public interface DispatchDataMapper{
 @Select("<script>select d.*,t.order_no,s.service_status order_status,p.nickname accepted_player_name from pw_dispatch_task d join pw_trade_order t on t.id=d.order_id join pw_service_order s on s.order_id=t.id left join pw_player p on p.id=d.accepted_player_id where d.task_no like concat('%',#{taskNo},'%') <if test='status != null and status != &quot;&quot;'>and d.task_status=#{status}</if><if test='mode != null and mode != &quot;&quot;'>and d.dispatch_mode=#{mode}</if> order by d.id desc</script>") IPage<Map<String,Object>> tasks(Page<Map<String,Object>> page,@Param("taskNo")String taskNo,@Param("status")String status,@Param("mode")String mode);
 @Select("select d.*,t.order_no,s.service_status order_status,p.nickname accepted_player_name from pw_dispatch_task d join pw_trade_order t on t.id=d.order_id join pw_service_order s on s.order_id=t.id left join pw_player p on p.id=d.accepted_player_id where d.id=#{id}") Map<String,Object> task(long id);
 @Select("select c.*,p.player_no,p.nickname,p.work_status,p.rating_score from pw_dispatch_candidate c join pw_player p on p.id=c.player_id where c.task_id=#{id} order by c.match_score desc,c.id") List<Map<String,Object>> candidates(long id);
 @Select("select l.*,p.nickname player_name,u.username operator_name from pw_dispatch_action_log l left join pw_player p on p.id=l.player_id left join sys_user u on u.id=l.operator_id where l.task_id=#{id} order by l.id") List<Map<String,Object>> logs(long id);
 @Select("select * from pw_dispatch_rule where enabled=true order by id limit 1") Map<String,Object> enabledRule();
 @Select("select game_id from pw_order_game_profile where order_id=#{id}") Long orderGame(long id);
 @Select("select requested_player_id,requested_player_level_id from pw_service_order where order_id=#{id}") Map<String,Object> orderRequirement(long id);
 @Select("<script>select p.id,p.player_no,p.nickname,p.work_status,p.rating_score,p.max_active_orders,pg.is_primary,(select count(*) from pw_order_member m join pw_service_order o on o.order_id=m.order_id where m.player_id=p.id and m.member_status in('ACCEPTED','IN_SERVICE') and o.service_status in('WAIT_ASSIGN','ASSIGNED','IN_SERVICE','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE')) active_count from pw_player p join pw_player_game pg on pg.player_id=p.id and pg.game_id=#{gameId} and pg.enabled=true and pg.audit_status='APPROVED' where p.enabled=true and p.audit_status='APPROVED' and not exists(select 1 from pw_order_member om where om.order_id=#{orderId} and om.player_id=p.id) <if test='levelId != null'>and pg.price_level_id=#{levelId}</if><if test='requestedPlayerId != null'>and p.id=#{requestedPlayerId}</if><if test='!allowBusy'>and p.work_status='AVAILABLE'</if> and (select count(*) from pw_order_member m join pw_service_order o on o.order_id=m.order_id where m.player_id=p.id and m.member_status in('ACCEPTED','IN_SERVICE') and o.service_status in('WAIT_ASSIGN','ASSIGNED','IN_SERVICE','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE'))&lt;least(p.max_active_orders,#{platformMax}) order by p.rating_score desc,pg.is_primary desc,p.sort_no limit #{candidateLimit}</script>") List<Map<String,Object>> eligible(@Param("orderId")long orderId,@Param("gameId")long gameId,@Param("levelId")Long levelId,@Param("requestedPlayerId")Long requestedPlayerId,@Param("allowBusy")boolean allowBusy,@Param("platformMax")int platformMax,@Param("candidateLimit")int candidateLimit);
 @Update("update pw_dispatch_candidate set candidate_status='REJECTED',reject_reason=#{reason},responded_at=current_timestamp where id=#{id} and candidate_status='PENDING'") int rejectCandidate(long id,String reason);
 @Update("update pw_dispatch_task set task_status='REJECTED',updated_at=current_timestamp where id=#{id} and task_status='DISPATCHING' and accepted_player_id is null") int rejectTask(long id);
 @Update("update pw_dispatch_candidate set candidate_status='ACCEPTED',responded_at=current_timestamp where id=#{id} and candidate_status='PENDING'") int acceptCandidate(long id);
 @Update("update pw_dispatch_task set accepted_player_id=coalesce(accepted_player_id,#{playerId}),accepted_at=coalesce(accepted_at,current_timestamp),updated_at=current_timestamp where id=#{id} and task_status='DISPATCHING' and deadline_at>current_timestamp") int recordAcceptedPlayer(long id,long playerId);
 @Update("update pw_dispatch_task set task_status='ACCEPTED',updated_at=current_timestamp where id=#{id} and task_status='DISPATCHING'") int completeTask(long id);
 @Update("update pw_dispatch_task set task_status='PARTIAL',updated_at=current_timestamp where id=#{id} and task_status='DISPATCHING' and not exists(select 1 from pw_dispatch_candidate c where c.task_id=#{id} and c.candidate_status='PENDING')") int markPartialIfExhausted(long id);
 @Update("update pw_dispatch_candidate set candidate_status=case when player_id=#{playerId} then 'ACCEPTED' else 'CLOSED' end,responded_at=case when player_id=#{playerId} then current_timestamp else responded_at end where task_id=#{taskId} and candidate_status='PENDING'") int closeCandidates(long taskId,long playerId);
 @Select("select count(*) from pw_order_member where order_id=#{orderId} and player_id=#{playerId}") int orderMemberExists(long orderId,long playerId);
 @Update("update pw_dispatch_task set task_status='CANCELLED',cancelled_at=current_timestamp,updated_at=current_timestamp where id=#{id} and task_status='DISPATCHING'") int cancelTask(long id);
 @Update("update pw_dispatch_candidate set candidate_status='CLOSED' where task_id=#{id} and candidate_status='PENDING'") int cancelCandidates(long id);
 @Select("select * from pw_dispatch_task where task_status='DISPATCHING' and deadline_at<=current_timestamp") List<Map<String,Object>> dueTasks();
 @Update("update pw_dispatch_task set task_status='EXPIRED',updated_at=current_timestamp where id=#{id} and task_status='DISPATCHING'") int expireTask(long id);
 @Update("update pw_dispatch_candidate set candidate_status='TIMEOUT' where task_id=#{id} and candidate_status='PENDING'") int timeoutCandidates(long id);
}
