package com.peiwan.platform.persistence.mapper;import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.apache.ibatis.annotations.*;import java.util.*;
public interface FulfillmentDataMapper{
 @Select("<script>select f.*,t.order_no,s.service_status order_status,p.nickname player_name,p.player_no,i.product_name from pw_fulfillment f join pw_trade_order t on t.id=f.order_id join pw_service_order s on s.order_id=t.id join pw_player p on p.id=f.player_id left join pw_order_item i on i.id=(select min(x.id) from pw_order_item x where x.order_id=t.id) where 1=1 <if test='status != null and status != &quot;&quot;'>and f.fulfillment_status=#{status}</if> order by f.id desc</script>") IPage<Map<String,Object>> fulfillments(Page<Map<String,Object>> page,@Param("status")String status);
 @Select("select f.*,t.order_no,s.service_status order_status,p.nickname player_name,p.player_no from pw_fulfillment f join pw_trade_order t on t.id=f.order_id join pw_service_order s on s.order_id=t.id join pw_player p on p.id=f.player_id where f.id=#{id}") Map<String,Object> detail(long id);
 @Select("select customer_confirm_hours from pw_order_rule order by id limit 1") Integer confirmHours();
 @Select("select proof_url from pw_fulfillment_proof where fulfillment_id=#{id} order by sort_no") List<String> proofUrls(long id);
 @Select("select * from pw_fulfillment_audit where fulfillment_id=#{id} order by id") List<Map<String,Object>> audits(long id);
 @Select("select m.* from pw_order_member m where m.order_id=#{orderId} and m.player_id=#{playerId} and m.member_status in('ACCEPTED','IN_SERVICE')") Map<String,Object> activeMember(long orderId,long playerId);
 @Select("select count(*) from pw_order_member where order_id=#{orderId} and member_status in('ACCEPTED','IN_SERVICE')") int activeMemberCount(long orderId);
 @Select("select count(*) from pw_fulfillment f join pw_order_member m on m.id=f.order_member_id where f.order_id=#{orderId} and m.member_status in('ACCEPTED','IN_SERVICE') and f.fulfillment_status in('PENDING_REVIEW','COMPLETED')") int submittedCount(long orderId);
 @Select("select count(*) from pw_fulfillment f join pw_order_member m on m.id=f.order_member_id where f.order_id=#{orderId} and m.member_status in('ACCEPTED','IN_SERVICE') and f.fulfillment_status='COMPLETED'") int approvedCount(long orderId);
 @Update("update pw_order_member set member_status='IN_SERVICE',service_started_at=coalesce(service_started_at,current_timestamp),updated_at=current_timestamp where id=#{memberId} and member_status='ACCEPTED'") int startMember(long memberId);
}
