package com.peiwan.platform.persistence.mapper;import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.apache.ibatis.annotations.*;import java.util.*;
public interface OrderDataMapper{
 @Select("<script>select t.*,s.service_status order_status,s.requested_player_id,s.requested_player_level_id,s.player_level_code,s.player_level_name,s.pricing_mode,s.required_player_count,s.price_type sku_price_type,s.base_unit_price,s.contact_name,s.contact_phone,s.assigned_at,s.service_started_at,s.completion_submitted_at,s.customer_confirm_deadline,s.customer_confirmed_at,u.username customer_username,u.nickname customer_nickname,(select count(*) from pw_order_member m where m.order_id=t.id and m.member_status in('ACCEPTED','IN_SERVICE','COMPLETED')) member_count,(select product_name from pw_order_item i where i.order_id=t.id order by i.id limit 1) product_name from pw_trade_order t join pw_service_order s on s.order_id=t.id join sys_user u on u.id=t.customer_id where t.business_type='PLAYER_SERVICE' and t.order_no like concat('%',#{orderNo},'%') and (u.username like concat('%',#{customer},'%') or u.nickname like concat('%',#{customer},'%')) <if test='status != null and status != &quot;&quot;'>and s.service_status=#{status}</if> order by t.id desc</script>") IPage<Map<String,Object>> orders(Page<Map<String,Object>> page,@Param("orderNo")String orderNo,@Param("customer")String customer,@Param("status")String status);
 @Select("select t.*,s.service_status order_status,s.requested_player_id,s.requested_player_level_id,s.player_level_code,s.player_level_name,s.pricing_mode,s.required_player_count,s.price_type sku_price_type,s.base_unit_price,s.contact_name,s.contact_phone,s.assigned_at,s.service_started_at,s.completion_submitted_at,s.customer_confirm_deadline,s.customer_confirmed_at,u.username customer_username,u.nickname customer_nickname,(select count(*) from pw_order_member m where m.order_id=t.id and m.member_status in('ACCEPTED','IN_SERVICE','COMPLETED')) member_count from pw_trade_order t join pw_service_order s on s.order_id=t.id join sys_user u on u.id=t.customer_id where t.id=#{id} and t.business_type='PLAYER_SERVICE'") Map<String,Object> orderDetail(long id);
 @Select("select l.*,u.username operator_name from pw_order_status_log l left join sys_user u on u.id=l.operator_id where l.order_id=#{id} order by l.id") List<Map<String,Object>> statusLogs(long id);
 @Select("select id,username,nickname,phone from sys_user where enabled=true order by id") List<Map<String,Object>> customers();
 @Select("select id,player_no,nickname from pw_player where enabled=true and audit_status='APPROVED' order by sort_no,id") List<Map<String,Object>> players();
 @Select("select id,level_code,level_name,sort_no from pw_player_level where game_id=#{gameId} and enabled=true order by sort_no,id") List<Map<String,Object>> playerLevels(long gameId);
 @Select("select p.id,p.player_no,p.nickname,p.work_status,p.rating_score,pg.price_level_id,l.level_name from pw_player p join pw_player_game pg on pg.player_id=p.id and pg.game_id=#{gameId} and pg.enabled=true and pg.audit_status='APPROVED' left join pw_player_level l on l.id=pg.price_level_id where p.enabled=true and p.audit_status='APPROVED' order by case when p.work_status='AVAILABLE' then 0 else 1 end,p.rating_score desc,p.sort_no,p.id") List<Map<String,Object>> createPlayers(long gameId);
 @Select("select * from sys_user where id=#{id} and enabled=true") Map<String,Object> enabledCustomer(long id);
 @Select("select k.*,p.game_id,p.product_code,p.product_name,p.product_type,p.pricing_mode,p.status product_status,g.game_name from pw_product_sku k join pw_product p on p.id=k.product_id join pw_game g on g.id=p.game_id where k.id=#{id}") Map<String,Object> skuSnapshot(long id);
 @Select("select * from pw_player_level where id=#{id}") Map<String,Object> playerLevel(long id);
 @Select("select l.* from pw_player_game pg join pw_player_level l on l.id=pg.price_level_id where pg.player_id=#{playerId} and pg.game_id=#{gameId} and pg.enabled=true and pg.audit_status='APPROVED'") Map<String,Object> playerGameLevel(long playerId,long gameId);
 @Select("select sp.*,sp.price base_unit_price,sp.price*k.unit_count price from pw_product_sku k join pw_product_service ps on ps.product_id=k.product_id join pw_service_level_price sp on sp.service_id=ps.service_id and sp.unit_type=k.unit_type where k.id=#{skuId} and sp.player_level_id=#{levelId}") Map<String,Object> levelPrice(long skuId,long levelId);
 @Select("select case when count(*)>0 then true else false end from pw_player_game where player_id=#{playerId} and game_id=#{gameId} and price_level_id=#{levelId} and enabled=true") boolean playerMatchesLevel(long playerId,long gameId,long levelId);
 @Update("update pw_product_sku set stock_quantity=stock_quantity-#{quantity} where id=#{skuId} and stock_quantity>=#{quantity}") int decrementStock(long skuId,int quantity);
 @Select("select s.service_code,s.service_name,ps.service_quantity quantity,ps.unit_type from pw_product_service ps join pw_service_item s on s.id=ps.service_id where ps.product_id=#{id} order by ps.sort_no") List<Map<String,Object>> serviceSnapshot(long id);
 @Select("select i.sku_id,i.quantity,k.stock_mode from pw_order_item i join pw_product_sku k on k.id=i.sku_id where i.order_id=#{id}") List<Map<String,Object>> stockRows(long id);
 @Update("update pw_product_sku set stock_quantity=stock_quantity+#{quantity} where id=#{skuId}") int restoreStock(long skuId,int quantity);
@Select("select count(*) from pw_order_member m join pw_service_order s on s.order_id=m.order_id where m.player_id=#{id} and m.member_status in('ACCEPTED','IN_SERVICE') and s.service_status in('WAIT_ASSIGN','ASSIGNED','IN_SERVICE','PAUSED','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE')") long activePlayerOrders(long id);
}
