package com.peiwan.platform.persistence.mapper;
import com.peiwan.platform.persistence.entity.OrderEntity;import org.apache.ibatis.annotations.*;
public interface OrderMapper{
 String AGGREGATE="select t.id,t.order_no,t.customer_id,t.trade_status,t.total_amount,t.payable_amount,t.paid_amount,t.customer_remark,t.cancel_reason,t.paid_at,t.completed_at,t.cancelled_at,t.created_by,t.created_at,t.updated_at,s.requested_player_id,s.requested_player_level_id,s.player_level_code,s.player_level_name,s.required_player_count,s.pricing_mode,s.price_type sku_price_type,s.base_unit_price,s.contact_name,s.contact_phone,s.service_status order_status,s.assigned_at,s.service_started_at,s.completion_submitted_at,s.customer_confirm_deadline,s.customer_confirmed_at from pw_trade_order t join pw_service_order s on s.order_id=t.id ";
 @Select(AGGREGATE+"where t.id=#{id} and t.business_type='PLAYER_SERVICE'") OrderEntity selectById(long id);
 @Select(AGGREGATE+"where t.id=#{id} and t.customer_id=#{uid} and t.business_type='PLAYER_SERVICE'") OrderEntity selectOwned(long id,long uid);
 @Update("update pw_trade_order set trade_status=#{tradeStatus},total_amount=#{totalAmount},payable_amount=#{payableAmount},paid_amount=#{paidAmount},customer_remark=#{customerRemark},cancel_reason=#{cancelReason},paid_at=#{paidAt},completed_at=#{completedAt},cancelled_at=#{cancelledAt},updated_at=current_timestamp where id=#{id} and business_type='PLAYER_SERVICE'") int updateTrade(OrderEntity order);
 @Update("update pw_service_order set requested_player_id=#{requestedPlayerId},requested_player_level_id=#{requestedPlayerLevelId},player_level_code=#{playerLevelCode},player_level_name=#{playerLevelName},required_player_count=#{requiredPlayerCount},pricing_mode=#{pricingMode},price_type=#{skuPriceType},base_unit_price=#{baseUnitPrice},contact_name=#{contactName},contact_phone=#{contactPhone},service_status=#{orderStatus},assigned_at=#{assignedAt},service_started_at=#{serviceStartedAt},completion_submitted_at=#{completionSubmittedAt},customer_confirm_deadline=#{customerConfirmDeadline},customer_confirmed_at=#{customerConfirmedAt},updated_at=current_timestamp where order_id=#{id}") int updateService(OrderEntity order);
 default int updateById(OrderEntity order){return updateTrade(order)+updateService(order);}
}
