package com.peiwan.platform.persistence.mapper;import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.apache.ibatis.annotations.*;import java.util.*;
public interface PlayerPortalDataMapper{
 @Select("select count(*) from pw_dispatch_candidate c join pw_dispatch_task t on t.id=c.task_id where c.player_id=#{id} and c.candidate_status='PENDING' and t.task_status='DISPATCHING' and t.deadline_at>current_timestamp") long pendingDispatchCount(long id);
 @Select("select count(*) from pw_order where assigned_player_id=#{id} and order_status in('ASSIGNED','IN_SERVICE')") long activeOrderCount(long id);
 @Select("select count(*) from pw_order where assigned_player_id=#{id} and order_status='COMPLETED'") long completedOrderCount(long id);
 @Select("select t.id task_id,t.task_no,t.dispatch_mode,t.deadline_at,o.id order_id,o.order_no,o.order_status,i.product_name,i.sku_name,g.game_name,g.server_name,g.rank_name,g.extra_requirement from pw_dispatch_candidate c join pw_dispatch_task t on t.id=c.task_id join pw_order o on o.id=t.order_id left join pw_order_item i on i.id=(select min(x.id) from pw_order_item x where x.order_id=o.id) left join pw_order_game_profile g on g.order_id=o.id where c.player_id=#{id} and c.candidate_status='PENDING' and t.task_status='DISPATCHING' and t.deadline_at>current_timestamp order by t.deadline_at") List<Map<String,Object>> pendingDispatches(long id);
 @Select("select id from pw_player where id=#{id} for update") Long lockPlayer(long id);
 @Select("select max_active_orders from pw_dispatch_rule where enabled=true order by id limit 1") Integer platformMaxOrders();
 @Select("select count(*) from pw_order where assigned_player_id=#{id} and order_status in('ASSIGNED','IN_SERVICE','PENDING_CONFIRM')") long capacityOrderCount(long id);
 @Select("<script>select o.id,o.order_no,o.order_status,o.assigned_at,o.service_started_at,o.completed_at,i.product_name,i.sku_name,g.game_name,g.server_name,g.rank_name from pw_order o left join pw_order_item i on i.id=(select min(x.id) from pw_order_item x where x.order_id=o.id) left join pw_order_game_profile g on g.order_id=o.id where o.assigned_player_id=#{playerId}<if test='status != null and status != &quot;&quot;'> and o.order_status=#{status}</if> order by o.id desc</script>") IPage<Map<String,Object>> ownOrders(Page<Map<String,Object>> page,@Param("playerId")long playerId,@Param("status")String status);
}
