package com.peiwan.platform.persistence.mapper;
import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.apache.ibatis.annotations.*;import java.util.*;
public interface PlayerDetailMapper{
 @Select("select u.id,u.username,u.nickname,u.phone from sys_user u left join pw_player p on p.user_id=u.id where u.enabled=true and (p.id is null or p.id=#{playerId}) order by u.id") List<Map<String,Object>> userOptions(long playerId);
 @Select("<script>select p.*,g.game_name primary_game from pw_player p left join pw_player_game pg on pg.player_id=p.id and pg.is_primary=true left join pw_game g on g.id=pg.game_id where (p.player_no like concat('%',#{keyword},'%') or p.nickname like concat('%',#{keyword},'%') or coalesce(p.phone,'') like concat('%',#{keyword},'%')) <if test='auditStatus != null and auditStatus != &quot;&quot;'>and p.audit_status=#{auditStatus}</if> <if test='workStatus != null and workStatus != &quot;&quot;'>and p.work_status=#{workStatus}</if> <if test='enabled != null'>and p.enabled=#{enabled}</if> order by p.sort_no,p.id desc</script>") IPage<Map<String,Object>> players(Page<Map<String,Object>> page,@Param("keyword")String keyword,@Param("auditStatus")String auditStatus,@Param("workStatus")String workStatus,@Param("enabled")Boolean enabled);
 @Select("<script>select p.*,g.game_name primary_game,pg.game_id,pg.game_nickname,pg.rank_name player_rank_name,pg.price_level_id,l.level_code,l.level_name,lp.price*k.unit_count service_price from pw_player p join pw_player_game pg on pg.player_id=p.id and pg.game_id=#{gameId} and pg.enabled=true and pg.audit_status='APPROVED' join pw_game g on g.id=pg.game_id and g.enabled=true left join pw_player_level l on l.id=pg.price_level_id left join pw_product_sku k on k.id=#{skuId} left join pw_product_service ps on ps.product_id=k.product_id left join pw_service_level_price lp on lp.service_id=ps.service_id and lp.unit_type=k.unit_type and lp.player_level_id=pg.price_level_id and lp.enabled=true where p.enabled=true and p.audit_status='APPROVED' and (p.player_no like concat('%',#{keyword},'%') or p.nickname like concat('%',#{keyword},'%') or coalesce(p.introduction,'') like concat('%',#{keyword},'%') or exists(select 1 from pw_player_tag_rel tr join pw_player_tag t on t.id=tr.tag_id where tr.player_id=p.id and t.enabled=true and t.tag_name like concat('%',#{keyword},'%'))) <if test='workStatus != null and workStatus != &quot;&quot;'>and p.work_status=#{workStatus}</if> <if test='levelId != null'>and pg.price_level_id=#{levelId}</if> <if test='tagId != null'>and exists(select 1 from pw_player_tag_rel tr where tr.player_id=p.id and tr.tag_id=#{tagId})</if> <if test='gender != null and gender != &quot;&quot;'>and p.gender=#{gender}</if> <if test='skuId != null'>and lp.id is not null</if> order by case when p.work_status='AVAILABLE' then 0 else 1 end <choose><when test='sort == &quot;PRICE_ASC&quot;'>,lp.price*k.unit_count asc</when><when test='sort == &quot;PRICE_DESC&quot;'>,lp.price*k.unit_count desc</when><when test='sort == &quot;ORDERS&quot;'>,p.order_count desc,p.rating_score desc</when><otherwise>,p.rating_score desc,p.order_count desc</otherwise></choose>,p.sort_no,p.id desc</script>") IPage<Map<String,Object>> customerPlayersByGame(Page<Map<String,Object>> page,@Param("keyword")String keyword,@Param("workStatus")String workStatus,@Param("gameId")long gameId,@Param("levelId")Long levelId,@Param("skuId")Long skuId,@Param("tagId")Long tagId,@Param("gender")String gender,@Param("sort")String sort);
 @Select("select p.*,g.game_name primary_game from pw_player p left join pw_player_game pg on pg.player_id=p.id and pg.is_primary=true left join pw_game g on g.id=pg.game_id where p.id=#{id}") Map<String,Object> playerDetail(long id);
 @Select("select tag_id from pw_player_tag_rel where player_id=#{id} order by tag_id") List<Long> tagIds(long id);
 @Select("select t.id,t.tag_name,t.tag_color,t.tag_group from pw_player_tag_rel r join pw_player_tag t on t.id=r.tag_id where r.player_id=#{id} and t.enabled=true order by t.sort_no,t.id") List<Map<String,Object>> playerTags(long id);
 @Select("select pg.*,g.game_name,l.level_name price_level_name from pw_player_game pg join pw_game g on g.id=pg.game_id left join pw_player_level l on l.id=pg.price_level_id where pg.player_id=#{id} order by pg.is_primary desc,pg.id") List<Map<String,Object>> playerGames(long id);
 @Select("select * from pw_player_media where player_id=#{id} order by sort_no,id") List<Map<String,Object>> media(long id);
 @Select("select a.*,u.username auditor_name from pw_player_audit a left join sys_user u on u.id=a.auditor_id where a.player_id=#{id} order by a.id desc") List<Map<String,Object>> audits(long id);
 @Select("select position_id from pw_player_game_position where player_game_id=#{id} order by position_id") List<Long> positionIds(long id);
 @Select("select position_id from pw_player_game_position where player_game_id=#{id} and is_primary=true limit 1") Long primaryPositionId(long id);
}
