package com.peiwan.platform.persistence.mapper;import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.apache.ibatis.annotations.*;import java.util.*;
public interface PlayerPortalDataMapper{
 @Select("select count(*) from pw_dispatch_candidate c join pw_dispatch_task t on t.id=c.task_id where c.player_id=#{id} and c.candidate_status='PENDING' and t.task_status='DISPATCHING' and t.deadline_at>current_timestamp") long pendingDispatchCount(long id);
@Select("select count(*) from pw_order_member m join pw_service_order s on s.order_id=m.order_id where m.player_id=#{id} and m.member_status in('ACCEPTED','IN_SERVICE') and s.service_status in('WAIT_ASSIGN','ASSIGNED','IN_SERVICE','PAUSED','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE')") long activeOrderCount(long id);
 @Select("select count(*) from pw_order_member m join pw_service_order s on s.order_id=m.order_id where m.player_id=#{id} and m.member_status='COMPLETED' and s.service_status='COMPLETED'") long completedOrderCount(long id);
 @Select("select d.id task_id,d.task_no,d.dispatch_mode,d.deadline_at,t.id order_id,t.order_no,s.service_status order_status,s.required_player_count,(select count(*) from pw_order_member m where m.order_id=t.id and m.member_status in('ACCEPTED','IN_SERVICE','COMPLETED')) member_count,i.product_name,i.sku_name,g.game_name,g.server_name,g.rank_name,g.extra_requirement from pw_dispatch_candidate c join pw_dispatch_task d on d.id=c.task_id join pw_trade_order t on t.id=d.order_id join pw_service_order s on s.order_id=t.id left join pw_order_item i on i.id=(select min(x.id) from pw_order_item x where x.order_id=t.id) left join pw_order_game_profile g on g.order_id=t.id where c.player_id=#{id} and c.candidate_status='PENDING' and d.task_status='DISPATCHING' and d.deadline_at>current_timestamp order by d.deadline_at") List<Map<String,Object>> pendingDispatches(long id);
 @Select("select id from pw_player where id=#{id} for update") Long lockPlayer(long id);
 @Select("select max_active_orders from pw_dispatch_rule where enabled=true order by id limit 1") Integer platformMaxOrders();
 @Select("select count(*) from pw_order_member m join pw_service_order s on s.order_id=m.order_id where m.player_id=#{id} and m.member_status in('ACCEPTED','IN_SERVICE') and s.service_status in('WAIT_ASSIGN','ASSIGNED','IN_SERVICE','PAUSED','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE')") long capacityOrderCount(long id);
 @Select("<script>select t.id,t.order_no,s.service_status order_status,s.required_player_count,(select count(*) from pw_order_member x where x.order_id=t.id and x.member_status in('ACCEPTED','IN_SERVICE','COMPLETED')) member_count,m.member_status,m.joined_at assigned_at,s.service_started_at,t.completed_at,i.product_name,i.sku_name,g.game_name,g.server_name,g.rank_name from pw_order_member m join pw_trade_order t on t.id=m.order_id join pw_service_order s on s.order_id=t.id left join pw_order_item i on i.id=(select min(x.id) from pw_order_item x where x.order_id=t.id) left join pw_order_game_profile g on g.order_id=t.id where m.player_id=#{playerId}<if test='status != null and status != &quot;&quot;'> and s.service_status=#{status}</if> order by t.id desc</script>") IPage<Map<String,Object>> ownOrders(Page<Map<String,Object>> page,@Param("playerId")long playerId,@Param("status")String status);
}
