package com.peiwan.platform.persistence.mapper;import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.apache.ibatis.annotations.*;import java.math.BigDecimal;import java.util.*;
public interface ProductDataMapper{
 @Select("<script>select p.*,g.game_name,c.category_name,(select count(*) from pw_product_sku k where k.product_id=p.id) sku_count,(select min(k.price) from pw_product_sku k where k.product_id=p.id and k.enabled=true) min_price from pw_product p join pw_game g on g.id=p.game_id join pw_product_category c on c.id=p.category_id where p.product_name like concat('%',#{name},'%') <if test='gameId != null'>and p.game_id=#{gameId}</if><if test='categoryId != null'>and p.category_id=#{categoryId}</if><if test='status != null and status != &quot;&quot;'>and p.status=#{status}</if><if test='productType != null and productType != &quot;&quot;'>and p.product_type=#{productType}</if> order by p.sort_no,p.id desc</script>") IPage<Map<String,Object>> products(Page<Map<String,Object>> page,@Param("name")String name,@Param("gameId")Long gameId,@Param("categoryId")Long categoryId,@Param("status")String status,@Param("productType")String productType);
 @Select("select p.*,g.game_name,c.category_name from pw_product p join pw_game g on g.id=p.game_id join pw_product_category c on c.id=p.category_id where p.id=#{id}") Map<String,Object> productDetail(long id);
 @Select("select ps.service_id,ps.service_quantity,ps.unit_type,ps.sort_no,s.service_name,s.service_code from pw_product_service ps join pw_service_item s on s.id=ps.service_id where ps.product_id=#{id} order by ps.sort_no,ps.service_id") List<Map<String,Object>> components(long id);
 @Delete("delete from pw_product_service where product_id=#{id}") int deleteComponents(long id);
 @Insert("insert into pw_product_service(product_id,service_id,service_quantity,unit_type,sort_no) values(#{pid},#{sid},#{quantity},#{unit},#{sort})") int addComponent(long pid,long sid,BigDecimal quantity,String unit,int sort);
 @Select("select count(*) from pw_product_service where product_id=#{id}") long componentCount(long id);
 @Select("select count(*) from pw_product_service ps join pw_service_item s on s.id=ps.service_id where ps.product_id=#{id} and s.enabled=true") long enabledComponentCount(long id);
}
