package com.peiwan.platform.persistence.mapper;
import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.apache.ibatis.annotations.*;import java.util.*;
public interface ServiceExceptionDataMapper{
 @Select("select s.order_id,s.service_status,t.customer_id from pw_service_order s join pw_trade_order t on t.id=s.order_id where s.order_id=#{orderId} for update")Map<String,Object> lockService(long orderId);
 @Select("select * from pw_order_member where id=#{id} and order_id=#{orderId} and member_status in('ACCEPTED','IN_SERVICE')")Map<String,Object> activeMember(long orderId,long id);
 @Select("select m.* from pw_order_member m join pw_player p on p.id=m.player_id where m.order_id=#{orderId} and p.user_id=#{uid} and m.member_status in('ACCEPTED','IN_SERVICE')")Map<String,Object> activeMemberByUser(long orderId,long uid);
 @Select("select id from pw_player where user_id=#{uid} and enabled=true and audit_status='APPROVED'")Long playerId(long uid);
 @Select("select count(*) from pw_service_exception_request where order_id=#{orderId} and request_status in('PENDING','WAIT_TARGET')")int openRequestCount(long orderId);
 @Select("select * from pw_service_exception_request where id=#{id} for update")Map<String,Object> lockRequest(long id);
 @Select("select count(*) from pw_order_member where order_id=#{orderId} and player_id=#{playerId}")int historicalMember(long orderId,long playerId);
 @Select("select count(*) from pw_player p join pw_order_game_profile g on g.order_id=#{orderId} join pw_player_game pg on pg.player_id=p.id and pg.game_id=g.game_id and pg.enabled=true and pg.audit_status='APPROVED' join pw_service_order s on s.order_id=#{orderId} where p.id=#{playerId} and p.enabled=true and p.audit_status='APPROVED' and p.work_status in('AVAILABLE','BUSY') and (s.requested_player_level_id is null or pg.price_level_id=s.requested_player_level_id) and (select count(*) from pw_order_member m join pw_service_order so on so.order_id=m.order_id where m.player_id=p.id and m.member_status in('ACCEPTED','IN_SERVICE') and so.service_status in('WAIT_ASSIGN','ASSIGNED','IN_SERVICE','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE')) < least(p.max_active_orders,coalesce((select max_active_orders from pw_dispatch_rule where enabled=true order by id limit 1),p.max_active_orders))")int eligibleTarget(long orderId,long playerId);
 @Select("select p.id player_id,p.player_no,p.nickname player_name,p.rating_score,p.work_status from pw_player p join pw_order_game_profile g on g.order_id=#{orderId} join pw_player_game pg on pg.player_id=p.id and pg.game_id=g.game_id and pg.enabled=true and pg.audit_status='APPROVED' join pw_service_order s on s.order_id=#{orderId} where p.enabled=true and p.audit_status='APPROVED' and p.work_status in('AVAILABLE','BUSY') and (s.requested_player_level_id is null or pg.price_level_id=s.requested_player_level_id) and not exists(select 1 from pw_order_member om where om.order_id=#{orderId} and om.player_id=p.id) and (select count(*) from pw_order_member m join pw_service_order so on so.order_id=m.order_id where m.player_id=p.id and m.member_status in('ACCEPTED','IN_SERVICE') and so.service_status in('WAIT_ASSIGN','ASSIGNED','IN_SERVICE','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE')) < least(p.max_active_orders,coalesce((select max_active_orders from pw_dispatch_rule where enabled=true order by id limit 1),p.max_active_orders)) order by p.rating_score desc,p.id")List<Map<String,Object>> eligibleTargets(long orderId);
 @Update("update pw_order_member set member_status='TRANSFERRED',cancelled_at=current_timestamp,updated_at=current_timestamp where id=#{id} and member_status in('ACCEPTED','IN_SERVICE')")int transferOut(long id);
 @Update("update pw_fulfillment set fulfillment_status='TRANSFERRED',updated_at=current_timestamp where order_member_id=#{memberId} and fulfillment_status in('IN_SERVICE','REJECTED')")int transferFulfillment(long memberId);
 @Select("select count(*) from pw_order_member m join pw_service_order s on s.order_id=m.order_id where m.player_id=#{playerId} and m.member_status in('ACCEPTED','IN_SERVICE') and s.service_status in('WAIT_ASSIGN','ASSIGNED','IN_SERVICE','PENDING_CONFIRM','WAIT_CUSTOMER_CONFIRM','AFTER_SALE')")long activeOrderCount(long playerId);
 @Select("<script>select r.*,t.order_no,s.service_status,p.nickname source_player_name,tp.nickname target_player_name,u.username applicant_name,ru.username reviewer_name,(select max(l.calculation_base) from pw_service_liability l where l.exception_request_id=r.id) liability_base,(select max(l.rate) from pw_service_liability l where l.exception_request_id=r.id) liability_rate,(select sum(l.amount) from pw_service_liability l where l.exception_request_id=r.id) liability_amount from pw_service_exception_request r join pw_trade_order t on t.id=r.order_id join pw_service_order s on s.order_id=t.id left join pw_order_member m on m.id=r.source_order_member_id left join pw_player p on p.id=m.player_id left join pw_player tp on tp.id=r.target_player_id left join sys_user u on u.id=r.applicant_user_id left join sys_user ru on ru.id=r.reviewed_by where 1=1<if test='status != null and status != &quot;&quot;'> and r.request_status=#{status}</if><if test='type != null and type != &quot;&quot;'> and r.request_type=#{type}</if> order by r.id desc</script>")IPage<Map<String,Object>> requests(Page<Map<String,Object>> page,@Param("status")String status,@Param("type")String type);
 @Select("select r.*,t.order_no,p.nickname source_player_name,tp.nickname target_player_name from pw_service_exception_request r join pw_trade_order t on t.id=r.order_id left join pw_order_member m on m.id=r.source_order_member_id left join pw_player p on p.id=m.player_id left join pw_player tp on tp.id=r.target_player_id where r.target_player_id=#{playerId} and r.request_type='TRANSFER' and r.request_status='WAIT_TARGET' order by r.id")List<Map<String,Object>> pendingTransfers(long playerId);
 @Select("select r.*,p.nickname source_player_name,tp.nickname target_player_name,(select max(l.calculation_base) from pw_service_liability l where l.exception_request_id=r.id) liability_base,(select max(l.rate) from pw_service_liability l where l.exception_request_id=r.id) liability_rate,(select sum(l.amount) from pw_service_liability l where l.exception_request_id=r.id) liability_amount from pw_service_exception_request r left join pw_order_member m on m.id=r.source_order_member_id left join pw_player p on p.id=m.player_id left join pw_player tp on tp.id=r.target_player_id where r.order_id=#{orderId} order by r.id desc")List<Map<String,Object>> orderRequests(long orderId);
}
