package com.peiwan.platform.catalog;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import java.time.LocalDateTime;import java.util.*;
@Service public class CatalogService{
 private static final Set<String> UNITS=Set.of("HOUR","GAME","ORDER");
 private final ProductCategoryMapper categories;private final ServiceItemMapper services;private final GameMapper games;private final CatalogQueryMapper queries;private final ServiceLevelPriceMapper servicePrices;private final PlayerLevelMapper levels;
 public CatalogService(ProductCategoryMapper categories,ServiceItemMapper services,GameMapper games,CatalogQueryMapper queries,ServiceLevelPriceMapper servicePrices,PlayerLevelMapper levels){this.categories=categories;this.services=services;this.games=games;this.queries=queries;this.servicePrices=servicePrices;this.levels=levels;}
 public List<Map<String,Object>> categoryTree(){return tree(queries.categoryRows());}
 public long saveCategory(Long id,CategoryCommand c){required(c.categoryCode(),"分类编码不能为空");required(c.categoryName(),"分类名称不能为空");if(c.gameId()!=null)requireGame(c.gameId());if(c.parentId()!=null){var parent=requireCategory(c.parentId());if(id!=null&&Objects.equals(id,c.parentId()))throw new IllegalArgumentException("不能将自身设为父分类");if(id!=null&&descendants(id).contains(c.parentId()))throw new IllegalArgumentException("不能移动到自己的子分类下");if(!Objects.equals(parent.gameId,c.gameId()))throw new IllegalArgumentException("父子分类必须属于同一游戏");}try{var x=id==null?new ProductCategoryEntity():requireCategory(id);x.gameId=c.gameId();x.parentId=c.parentId();x.categoryCode=c.categoryCode();x.categoryName=c.categoryName();x.iconUrl=c.iconUrl();x.sortNo=c.sortNo();x.enabled=c.enabled();if(id==null)categories.insert(x);else{x.updatedAt=LocalDateTime.now();categories.updateById(x);}return x.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("分类编码已存在");}}
 public void categoryStatus(long id,boolean enabled){var x=requireCategory(id);if(!enabled&&queries.onSaleCategoryProducts(id)>0)throw new IllegalArgumentException("该分类存在上架商品，不能禁用");x.enabled=enabled;x.updatedAt=LocalDateTime.now();categories.updateById(x);}
 public void deleteCategory(long id){requireCategory(id);if(categories.selectCount(new QueryWrapper<ProductCategoryEntity>().eq("parent_id",id))>0)throw new IllegalArgumentException("请先删除子分类");if(queries.categoryProducts(id)>0)throw new IllegalArgumentException("该分类已被商品使用，不能删除");categories.deleteById(id);}
 public Map<String,Object> services(int current,int size,String name,Long gameId,String type,Boolean enabled){current=Math.max(current,1);size=Math.min(Math.max(size,1),200);var result=queries.services(new Page<>(current,size),Objects.toString(name,""),gameId,type,enabled);return Map.of("records",result.getRecords().stream().map(this::serviceView).toList(),"current",current,"size",size,"total",result.getTotal());}
 @org.springframework.transaction.annotation.Transactional public long saveService(Long id,ServiceCommand c){requireGame(c.gameId());required(c.serviceCode(),"服务编码不能为空");required(c.serviceName(),"服务名称不能为空");if(!Set.of("COMPANION","RANKING","TEACHING","ESCORT","MAP_CLEAR","CUSTOM").contains(c.serviceType()))throw new IllegalArgumentException("服务类型无效");validateServicePrices(c.gameId(),c.levelPrices());try{var x=id==null?new ServiceItemEntity():requireService(id);x.gameId=c.gameId();x.serviceCode=c.serviceCode();x.serviceName=c.serviceName();x.serviceType=c.serviceType();x.description=c.description();x.sortNo=c.sortNo();x.enabled=c.enabled();if(id==null)services.insert(x);else{x.updatedAt=LocalDateTime.now();services.updateById(x);}servicePrices.delete(new QueryWrapper<ServiceLevelPriceEntity>().eq("service_id",x.id));for(var p:c.levelPrices()==null?List.<ServiceLevelPriceCommand>of():c.levelPrices()){if(p.price()==null)continue;var row=new ServiceLevelPriceEntity();row.serviceId=x.id;row.playerLevelId=p.playerLevelId();row.unitType=p.unitType();row.price=p.price();row.marketPrice=p.marketPrice();row.enabled=p.enabled();servicePrices.insert(row);}return x.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("服务编码或等级单位价格重复");}}
 public void serviceStatus(long id,boolean enabled){var x=requireService(id);if(!enabled&&queries.onSaleServiceProducts(id)>0)throw new IllegalArgumentException("该服务存在上架商品，不能禁用");x.enabled=enabled;x.updatedAt=LocalDateTime.now();services.updateById(x);}
 public void deleteService(long id){requireService(id);if(queries.serviceProducts(id)>0)throw new IllegalArgumentException("该服务已被商品使用，不能删除");services.deleteById(id);}
 @SuppressWarnings("unchecked") private List<Map<String,Object>> tree(List<Map<String,Object>> rows){var nodes=new LinkedHashMap<Long,Map<String,Object>>();for(var r:rows){long id=((Number)r.get("id")).longValue();var n=categoryView(r);n.put("children",new ArrayList<Map<String,Object>>());nodes.put(id,n);}var roots=new ArrayList<Map<String,Object>>();for(var r:rows){long id=((Number)r.get("id")).longValue();var parent=r.get("parent_id");if(parent==null)roots.add(nodes.get(id));else{var p=nodes.get(((Number)parent).longValue());if(p==null)roots.add(nodes.get(id));else((List<Map<String,Object>>)p.get("children")).add(nodes.get(id));}}return roots;}
 private Map<String,Object> categoryView(Map<String,Object> r){var x=new LinkedHashMap<String,Object>();x.put("id",r.get("id"));x.put("gameId",r.get("game_id"));x.put("gameName",r.get("game_name"));x.put("parentId",r.get("parent_id"));x.put("categoryCode",r.get("category_code"));x.put("categoryName",r.get("category_name"));x.put("iconUrl",r.get("icon_url"));x.put("sortNo",r.get("sort_no"));x.put("enabled",r.get("enabled"));return x;}
 private Map<String,Object> serviceView(Map<String,Object> r){var x=new LinkedHashMap<String,Object>();x.put("id",r.get("id"));x.put("gameId",r.get("game_id"));x.put("gameName",r.get("game_name"));x.put("serviceCode",r.get("service_code"));x.put("serviceName",r.get("service_name"));x.put("serviceType",r.get("service_type"));x.put("description",r.get("description"));x.put("sortNo",r.get("sort_no"));x.put("enabled",r.get("enabled"));x.put("createTime",r.get("created_at"));long id=((Number)r.get("id")).longValue();x.put("levelPrices",servicePrices.selectList(new QueryWrapper<ServiceLevelPriceEntity>().eq("service_id",id).orderByAsc("unit_type","player_level_id")).stream().map(p->Map.of("id",p.id,"playerLevelId",p.playerLevelId,"unitType",p.unitType,"price",p.price,"marketPrice",p.marketPrice==null?"":p.marketPrice,"enabled",p.enabled)).toList());return x;}
 private void validateServicePrices(long gameId,List<ServiceLevelPriceCommand> prices){var keys=new HashSet<String>();for(var p:prices==null?List.<ServiceLevelPriceCommand>of():prices){if(!UNITS.contains(p.unitType()))throw new IllegalArgumentException("服务计价单位无效");var level=levels.selectById(p.playerLevelId());if(level==null||!Objects.equals(level.gameId,gameId))throw new IllegalArgumentException("陪玩等级与基础服务所属游戏不一致");if(p.price()!=null&&p.price().signum()<0)throw new IllegalArgumentException("服务单价不能小于0");if(p.marketPrice()!=null&&p.price()!=null&&p.marketPrice().compareTo(p.price())<0)throw new IllegalArgumentException("划线价不能低于服务单价");if(!keys.add(p.unitType()+":"+p.playerLevelId()))throw new IllegalArgumentException("同一计价单位的等级价格不能重复");}}
 private Set<Long> descendants(long id){var out=new HashSet<Long>();var q=new ArrayDeque<Long>();q.add(id);while(!q.isEmpty())for(var child:categories.selectList(new QueryWrapper<ProductCategoryEntity>().select("id").eq("parent_id",q.remove())))if(out.add(child.id))q.add(child.id);return out;}
 private ProductCategoryEntity requireCategory(long id){var x=categories.selectById(id);if(x==null)throw new IllegalArgumentException("商品分类不存在");return x;}private GameEntity requireGame(long id){var x=games.selectById(id);if(x==null)throw new IllegalArgumentException("游戏不存在");return x;}private ServiceItemEntity requireService(long id){var x=services.selectById(id);if(x==null)throw new IllegalArgumentException("基础服务不存在");return x;}private void required(String v,String m){if(v==null||v.isBlank())throw new IllegalArgumentException(m);}
 public record CategoryCommand(Long gameId,Long parentId,String categoryCode,String categoryName,String iconUrl,int sortNo,boolean enabled){}public record ServiceCommand(long gameId,String serviceCode,String serviceName,String serviceType,String description,int sortNo,boolean enabled,List<ServiceLevelPriceCommand>levelPrices){}public record ServiceLevelPriceCommand(long playerLevelId,String unitType,java.math.BigDecimal price,java.math.BigDecimal marketPrice,boolean enabled){}
}
