package com.peiwan.platform.catalog;
import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController @RequestMapping("/api/business") public class CatalogController{private final CatalogService service;private final AuditService audit;public CatalogController(CatalogService s,AuditService a){service=s;audit=a;}
@PreAuthorize("hasAuthority('business:product-category:list') or hasRole('admin')") @GetMapping("/product-category/tree") public ApiResponse<?> categories(){return ApiResponse.ok(service.categoryTree());}
@PreAuthorize("hasAuthority('business:product-category:create') or hasRole('admin')") @PostMapping("/product-category") public ApiResponse<?> createCategory(Authentication a,@RequestBody CatalogService.CategoryCommand b,HttpServletRequest r){long id=service.saveCategory(null,b);audit.operation(a,"business:product-category:create","PRODUCT_CATEGORY",id,b.categoryName(),r);return ApiResponse.ok(Map.of("id",id));}
@PreAuthorize("hasAuthority('business:product-category:update') or hasRole('admin')") @PutMapping("/product-category/{id}") public ApiResponse<?> updateCategory(Authentication a,@PathVariable long id,@RequestBody CatalogService.CategoryCommand b,HttpServletRequest r){service.saveCategory(id,b);audit.operation(a,"business:product-category:update","PRODUCT_CATEGORY",id,b.categoryName(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:product-category:status') or hasRole('admin')") @PutMapping("/product-category/{id}/status") public ApiResponse<?> categoryStatus(Authentication a,@PathVariable long id,@RequestBody Status b,HttpServletRequest r){service.categoryStatus(id,b.enabled());audit.operation(a,"business:product-category:status","PRODUCT_CATEGORY",id,"enabled="+b.enabled(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:product-category:delete') or hasRole('admin')") @DeleteMapping("/product-category/{id}") public ApiResponse<?> deleteCategory(Authentication a,@PathVariable long id,HttpServletRequest r){service.deleteCategory(id);audit.operation(a,"business:product-category:delete","PRODUCT_CATEGORY",id,"删除分类",r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:service:list') or hasRole('admin')") @GetMapping("/service/list") public ApiResponse<?> services(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String serviceName,@RequestParam(required=false)Long gameId,@RequestParam(required=false)String serviceType,@RequestParam(required=false)Boolean enabled){return ApiResponse.ok(service.services(current,size,serviceName,gameId,serviceType,enabled));}
@PreAuthorize("hasAuthority('business:service:create') or hasRole('admin')") @PostMapping("/service") public ApiResponse<?> createService(Authentication a,@RequestBody CatalogService.ServiceCommand b,HttpServletRequest r){long id=service.saveService(null,b);audit.operation(a,"business:service:create","SERVICE",id,b.serviceName(),r);return ApiResponse.ok(Map.of("id",id));}
@PreAuthorize("hasAuthority('business:service:update') or hasRole('admin')") @PutMapping("/service/{id}") public ApiResponse<?> updateService(Authentication a,@PathVariable long id,@RequestBody CatalogService.ServiceCommand b,HttpServletRequest r){service.saveService(id,b);audit.operation(a,"business:service:update","SERVICE",id,b.serviceName(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:service:status') or hasRole('admin')") @PutMapping("/service/{id}/status") public ApiResponse<?> serviceStatus(Authentication a,@PathVariable long id,@RequestBody Status b,HttpServletRequest r){service.serviceStatus(id,b.enabled());audit.operation(a,"business:service:status","SERVICE",id,"enabled="+b.enabled(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:service:delete') or hasRole('admin')") @DeleteMapping("/service/{id}") public ApiResponse<?> deleteService(Authentication a,@PathVariable long id,HttpServletRequest r){service.deleteService(id);audit.operation(a,"business:service:delete","SERVICE",id,"删除服务",r);return ApiResponse.ok();}
public record Status(boolean enabled){}
}
