package com.peiwan.platform.catalog;
import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController @RequestMapping("/api/business/player-level") public class PlayerLevelController{
 private final ProductService service;private final AuditService audit;public PlayerLevelController(ProductService service,AuditService audit){this.service=service;this.audit=audit;}
 @PreAuthorize("hasAuthority('business:player-level:list') or hasRole('admin')") @GetMapping("/list") public ApiResponse<?> list(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String levelName,@RequestParam(required=false)Long gameId,@RequestParam(required=false)Boolean enabled){return ApiResponse.ok(service.playerLevelList(current,size,levelName,gameId,enabled));}
 @PreAuthorize("hasAuthority('business:player-level:create') or hasRole('admin')") @PostMapping public ApiResponse<?> create(Authentication a,@RequestBody ProductService.PlayerLevelCommand b,HttpServletRequest r){long id=service.savePlayerLevel(null,b);audit.operation(a,"business:player-level:create","PLAYER_LEVEL",id,b.levelName(),r);return ApiResponse.ok(Map.of("id",id));}
 @PreAuthorize("hasAuthority('business:player-level:update') or hasRole('admin')") @PutMapping("/{id}") public ApiResponse<?> update(Authentication a,@PathVariable long id,@RequestBody ProductService.PlayerLevelCommand b,HttpServletRequest r){service.savePlayerLevel(id,b);audit.operation(a,"business:player-level:update","PLAYER_LEVEL",id,b.levelName(),r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:player-level:status') or hasRole('admin')") @PutMapping("/{id}/status") public ApiResponse<?> status(Authentication a,@PathVariable long id,@RequestBody Status b,HttpServletRequest r){service.setPlayerLevelStatus(id,b.enabled());audit.operation(a,"business:player-level:status","PLAYER_LEVEL",id,"enabled="+b.enabled(),r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:player-level:delete') or hasRole('admin')") @DeleteMapping("/{id}") public ApiResponse<?> delete(Authentication a,@PathVariable long id,HttpServletRequest r){service.deletePlayerLevel(id);audit.operation(a,"business:player-level:delete","PLAYER_LEVEL",id,"删除陪玩等级",r);return ApiResponse.ok();}
 public record Status(boolean enabled){}
}
