package com.peiwan.platform.catalog;
import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController @RequestMapping("/api/business/product") public class ProductController{private final ProductService service;private final AuditService audit;public ProductController(ProductService s,AuditService a){service=s;audit=a;}
@PreAuthorize("hasAuthority('business:product:list') or hasRole('admin')") @GetMapping("/list") public ApiResponse<?> list(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String productName,@RequestParam(required=false)Long gameId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)String status,@RequestParam(required=false)String productType){return ApiResponse.ok(service.list(current,size,productName,gameId,categoryId,status,productType));}
@PreAuthorize("hasAuthority('business:product:list') or hasRole('admin')") @GetMapping("/{id}") public ApiResponse<?> detail(@PathVariable long id){return ApiResponse.ok(service.detail(id));}
@PreAuthorize("hasAuthority('business:product:create') or hasRole('admin')") @PostMapping public ApiResponse<?> create(Authentication a,@RequestBody ProductService.ProductCommand b,HttpServletRequest r){long id=service.save(null,b);audit.operation(a,"business:product:create","PRODUCT",id,b.productName(),r);return ApiResponse.ok(Map.of("id",id));}
@PreAuthorize("hasAuthority('business:product:update') or hasRole('admin')") @PutMapping("/{id}") public ApiResponse<?> update(Authentication a,@PathVariable long id,@RequestBody ProductService.ProductCommand b,HttpServletRequest r){service.save(id,b);audit.operation(a,"business:product:update","PRODUCT",id,b.productName(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:product:status') or hasRole('admin')") @PutMapping("/{id}/status") public ApiResponse<?> status(Authentication a,@PathVariable long id,@RequestBody Status b,HttpServletRequest r){service.status(id,b.status());audit.operation(a,"business:product:status","PRODUCT",id,b.status(),r);return ApiResponse.ok();}
@PreAuthorize("hasAuthority('business:product:delete') or hasRole('admin')") @DeleteMapping("/{id}") public ApiResponse<?> delete(Authentication a,@PathVariable long id,HttpServletRequest r){service.delete(id);audit.operation(a,"business:product:delete","PRODUCT",id,"删除商品",r);return ApiResponse.ok();}
public record Status(String status){}
}
