package com.peiwan.platform.catalog;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.LocalDateTime;import java.util.*;
@Service public class ProductService{
 private static final Set<String> UNITS=Set.of("HOUR","GAME","ORDER"),TYPES=Set.of("SERVICE","PACKAGE");
 private final ProductMapper products;private final ProductSkuMapper skus;private final ProductDataMapper data;private final ProductCategoryMapper categories;private final ServiceItemMapper services;private final GameMapper games;
 public ProductService(ProductMapper products,ProductSkuMapper skus,ProductDataMapper data,ProductCategoryMapper categories,ServiceItemMapper services,GameMapper games){this.products=products;this.skus=skus;this.data=data;this.categories=categories;this.services=services;this.games=games;}
 public Map<String,Object> list(int current,int size,String name,Long gameId,Long categoryId,String status,String productType){current=Math.max(1,current);size=Math.min(200,Math.max(1,size));var result=data.products(new Page<>(current,size),Objects.toString(name,""),gameId,categoryId,status,productType);return Map.of("records",result.getRecords().stream().map(this::view).toList(),"current",current,"size",size,"total",result.getTotal());}
 public Map<String,Object> detail(long id){var row=data.productDetail(id);if(row==null)throw new IllegalArgumentException("商品不存在");var p=view(row);var components=data.components(id).stream().map(this::componentView).toList();p.put("components",components);p.put("serviceIds",components.stream().map(x->x.get("serviceId")).toList());p.put("skus",skus.selectList(new QueryWrapper<ProductSkuEntity>().eq("product_id",id).orderByAsc("sort_no","id")).stream().map(this::skuView).toList());return p;}
 public Map<String,Object> customerDetail(long id){var p=detail(id);if(!"ON_SALE".equals(p.get("status")))throw new IllegalArgumentException("商品已下架或不存在");@SuppressWarnings("unchecked") var rows=(List<Map<String,Object>>)p.get("skus");p.put("skus",rows.stream().filter(x->Boolean.TRUE.equals(x.get("enabled"))).toList());return p;}
 @Transactional public long save(Long id,ProductCommand c){validate(c);try{ProductEntity p;if(id==null){p=new ProductEntity();p.status="DRAFT";}else{p=requireProduct(id);if("ON_SALE".equals(p.status))throw new IllegalArgumentException("请先下架商品再编辑");}apply(p,c);if(id==null)products.insert(p);else products.updateById(p);data.deleteComponents(p.id);int order=0;for(var component:normalizedComponents(c))data.addComponent(p.id,component.serviceId(),component.quantity(),component.unitType(),component.sortNo()==null?++order:component.sortNo());replaceSkus(p.id,c.skus());return p.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("商品编码、服务组成或规格编码已存在");}}
 public void status(long id,String status){if(!Set.of("ON_SALE","OFF_SHELF").contains(status))throw new IllegalArgumentException("商品状态无效");var p=requireProduct(id);if("ON_SALE".equals(status))validateSale(id,p);p.status=status;p.updatedAt=LocalDateTime.now();products.updateById(p);}
 @Transactional public void delete(long id){var p=requireProduct(id);if("ON_SALE".equals(p.status))throw new IllegalArgumentException("上架商品不能删除，请先下架");skus.delete(new QueryWrapper<ProductSkuEntity>().eq("product_id",id));data.deleteComponents(id);products.deleteById(id);}
 private void validate(ProductCommand c){required(c.productCode(),"商品编码不能为空");required(c.productName(),"商品名称不能为空");if(!TYPES.contains(c.productType()))throw new IllegalArgumentException("商品类型无效");var components=normalizedComponents(c);if("SERVICE".equals(c.productType())&&components.size()!=1)throw new IllegalArgumentException("单项服务必须选择一个基础服务");if("PACKAGE".equals(c.productType())&&components.size()<2)throw new IllegalArgumentException("平台套餐至少包含两个基础服务");if(c.validityDays()!=null&&c.validityDays()<1)throw new IllegalArgumentException("有效天数必须大于0");if(c.purchaseLimit()!=null&&c.purchaseLimit()<1)throw new IllegalArgumentException("限购数量必须大于0");var category=requireCategory(c.categoryId());if(!Objects.equals(category.gameId,c.gameId()))throw new IllegalArgumentException("商品分类与所属游戏不一致");if(categories.selectCount(new QueryWrapper<ProductCategoryEntity>().eq("parent_id",c.categoryId()))>0)throw new IllegalArgumentException("商品必须选择末级分类");var ids=new HashSet<Long>();for(var component:components){if(!ids.add(component.serviceId()))throw new IllegalArgumentException("套餐服务不能重复");if(component.quantity()==null||component.quantity().signum()<=0)throw new IllegalArgumentException("服务数量必须大于0");if(!UNITS.contains(component.unitType()))throw new IllegalArgumentException("服务计量单位无效");var service=requireService(component.serviceId());if(!Objects.equals(service.gameId,c.gameId()))throw new IllegalArgumentException("基础服务与所属游戏不一致");}if(c.skus()==null||c.skus().isEmpty())throw new IllegalArgumentException("至少添加一个销售规格");var codes=new HashSet<String>();for(var s:c.skus()){required(s.skuCode(),"规格编码不能为空");required(s.skuName(),"规格名称不能为空");if(!codes.add(s.skuCode()))throw new IllegalArgumentException("规格编码不能重复");if(s.price()==null||s.price().signum()<0)throw new IllegalArgumentException("规格价格不能小于0");if(s.marketPrice()!=null&&s.marketPrice().compareTo(s.price())<0)throw new IllegalArgumentException("划线价不能低于销售价");if(!UNITS.contains(s.unitType()))throw new IllegalArgumentException("计价单位无效");if(s.unitCount()==null||s.unitCount().signum()<=0)throw new IllegalArgumentException("单位数量必须大于0");if(s.minQuantity()<1||s.maxQuantity()!=null&&s.maxQuantity()<s.minQuantity())throw new IllegalArgumentException("购买数量范围无效");if(!Set.of("UNLIMITED","LIMITED").contains(s.stockMode()))throw new IllegalArgumentException("库存模式无效");if("LIMITED".equals(s.stockMode())&&(s.stockQuantity()==null||s.stockQuantity()<0))throw new IllegalArgumentException("限量库存不能为空");}}
 private List<ComponentCommand> normalizedComponents(ProductCommand c){if(c.components()!=null&&!c.components().isEmpty())return c.components();if(c.serviceIds()==null)return List.of();return c.serviceIds().stream().map(id->new ComponentCommand(id,BigDecimal.ONE,"ORDER",null)).toList();}
 private void validateSale(long id,ProductEntity p){var game=games.selectById(p.gameId);if(game==null||!Boolean.TRUE.equals(game.enabled))throw new IllegalArgumentException("所属游戏未启用");var category=categories.selectById(p.categoryId);if(category==null||!Boolean.TRUE.equals(category.enabled))throw new IllegalArgumentException("商品分类未启用");long total=data.componentCount(id),enabled=data.enabledComponentCount(id);if(total==0||total!=enabled)throw new IllegalArgumentException("套餐中存在未启用的基础服务");if(skus.selectCount(new QueryWrapper<ProductSkuEntity>().eq("product_id",id).eq("enabled",true))==0)throw new IllegalArgumentException("至少启用一个销售规格");}
 private void replaceSkus(long id,List<SkuCommand> rows){skus.delete(new QueryWrapper<ProductSkuEntity>().eq("product_id",id));for(var s:rows){var x=new ProductSkuEntity();x.productId=id;x.skuCode=s.skuCode();x.skuName=s.skuName();x.price=s.price();x.marketPrice=s.marketPrice();x.unitType=s.unitType();x.unitCount=s.unitCount();x.minQuantity=s.minQuantity();x.maxQuantity=s.maxQuantity();x.stockMode=s.stockMode();x.stockQuantity="LIMITED".equals(s.stockMode())?s.stockQuantity():null;x.serviceMinutes=s.serviceMinutes();x.enabled=s.enabled();x.sortNo=s.sortNo();skus.insert(x);}}
 private void apply(ProductEntity p,ProductCommand c){p.gameId=c.gameId();p.categoryId=c.categoryId();p.productCode=c.productCode();p.productName=c.productName();p.subtitle=c.subtitle();p.description=c.description();p.coverUrl=c.coverUrl();p.productType=c.productType();p.sortNo=c.sortNo();p.validityDays=c.validityDays();p.purchaseLimit=c.purchaseLimit();p.updatedAt=LocalDateTime.now();}
 private ProductEntity requireProduct(long id){var x=products.selectById(id);if(x==null)throw new IllegalArgumentException("商品不存在");return x;}private ProductCategoryEntity requireCategory(long id){var x=categories.selectById(id);if(x==null)throw new IllegalArgumentException("商品分类不存在");return x;}private ServiceItemEntity requireService(long id){var x=services.selectById(id);if(x==null)throw new IllegalArgumentException("基础服务不存在");return x;}private void required(String v,String m){if(v==null||v.isBlank())throw new IllegalArgumentException(m);}
 private Map<String,Object> view(Map<String,Object> r){var x=new LinkedHashMap<String,Object>();for(var e:Map.ofEntries(Map.entry("id","id"),Map.entry("gameId","game_id"),Map.entry("gameName","game_name"),Map.entry("categoryId","category_id"),Map.entry("categoryName","category_name"),Map.entry("productCode","product_code"),Map.entry("productName","product_name"),Map.entry("subtitle","subtitle"),Map.entry("description","description"),Map.entry("coverUrl","cover_url"),Map.entry("productType","product_type"),Map.entry("status","status"),Map.entry("sortNo","sort_no"),Map.entry("validityDays","validity_days"),Map.entry("purchaseLimit","purchase_limit"),Map.entry("skuCount","sku_count"),Map.entry("minPrice","min_price"),Map.entry("createTime","created_at")).entrySet())if(r.containsKey(e.getValue()))x.put(e.getKey(),r.get(e.getValue()));return x;}
 private Map<String,Object> componentView(Map<String,Object> r){var x=new LinkedHashMap<String,Object>();x.put("serviceId",r.get("service_id"));x.put("serviceName",r.get("service_name"));x.put("serviceCode",r.get("service_code"));x.put("quantity",r.get("service_quantity"));x.put("unitType",r.get("unit_type"));x.put("sortNo",r.get("sort_no"));return x;}
 private Map<String,Object> skuView(ProductSkuEntity r){var x=new LinkedHashMap<String,Object>();x.put("id",r.id);x.put("skuCode",r.skuCode);x.put("skuName",r.skuName);x.put("price",r.price);x.put("marketPrice",r.marketPrice);x.put("unitType",r.unitType);x.put("unitCount",r.unitCount);x.put("minQuantity",r.minQuantity);x.put("maxQuantity",r.maxQuantity);x.put("stockMode",r.stockMode);x.put("stockQuantity",r.stockQuantity);x.put("serviceMinutes",r.serviceMinutes);x.put("enabled",r.enabled);x.put("sortNo",r.sortNo);return x;}
 public record ProductCommand(long gameId,long categoryId,String productCode,String productName,String subtitle,String description,String coverUrl,String productType,int sortNo,Integer validityDays,Integer purchaseLimit,List<Long>serviceIds,List<ComponentCommand>components,List<SkuCommand>skus){public ProductCommand{if(productType==null||productType.isBlank())productType="SERVICE";}}public record ComponentCommand(long serviceId,BigDecimal quantity,String unitType,Integer sortNo){}public record SkuCommand(String skuCode,String skuName,BigDecimal price,BigDecimal marketPrice,String unitType,BigDecimal unitCount,int minQuantity,Integer maxQuantity,String stockMode,Integer stockQuantity,Integer serviceMinutes,boolean enabled,int sortNo){}
}
