package com.peiwan.platform.player;
import com.peiwan.platform.common.ApiResponse;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController public class GameConfigController{private final GameConfigService service;public GameConfigController(GameConfigService service){this.service=service;}
 @PreAuthorize("hasAuthority('business:game:list') or hasRole('admin')") @GetMapping("/api/business/game/{gameId}/config") public ApiResponse<?> adminConfig(@PathVariable long gameId){return ApiResponse.ok(service.config(gameId,false));}
 @GetMapping("/api/customer/catalog/games/{gameId}/config") public ApiResponse<?> customerConfig(@PathVariable long gameId){return ApiResponse.ok(service.config(gameId,true));}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @PostMapping("/api/business/game/{gameId}/server") public ApiResponse<?> createServer(@PathVariable long gameId,@RequestBody GameConfigService.ServerCommand b){return ApiResponse.ok(Map.of("id",service.saveServer(null,gameId,b)));}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @PutMapping("/api/business/game/{gameId}/server/{id}") public ApiResponse<?> updateServer(@PathVariable long gameId,@PathVariable long id,@RequestBody GameConfigService.ServerCommand b){service.saveServer(id,gameId,b);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @DeleteMapping("/api/business/game/server/{id}") public ApiResponse<?> deleteServer(@PathVariable long id){service.deleteServer(id);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @PostMapping("/api/business/game/{gameId}/rank-system") public ApiResponse<?> createSystem(@PathVariable long gameId,@RequestBody GameConfigService.RankSystemCommand b){return ApiResponse.ok(Map.of("id",service.saveSystem(null,gameId,b)));}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @PutMapping("/api/business/game/{gameId}/rank-system/{id}") public ApiResponse<?> updateSystem(@PathVariable long gameId,@PathVariable long id,@RequestBody GameConfigService.RankSystemCommand b){service.saveSystem(id,gameId,b);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @DeleteMapping("/api/business/game/rank-system/{id}") public ApiResponse<?> deleteSystem(@PathVariable long id){service.deleteSystem(id);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @PostMapping("/api/business/game/rank-system/{systemId}/rank") public ApiResponse<?> createRank(@PathVariable long systemId,@RequestBody GameConfigService.RankCommand b){return ApiResponse.ok(Map.of("id",service.saveRank(null,systemId,b)));}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @PutMapping("/api/business/game/rank-system/{systemId}/rank/{id}") public ApiResponse<?> updateRank(@PathVariable long systemId,@PathVariable long id,@RequestBody GameConfigService.RankCommand b){service.saveRank(id,systemId,b);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @DeleteMapping("/api/business/game/rank/{id}") public ApiResponse<?> deleteRank(@PathVariable long id){service.deleteRank(id);return ApiResponse.ok();}
}
