package com.peiwan.platform.player;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class GameConfigService{
 private final GameMapper games;private final GameServerMapper servers;private final GameRankSystemMapper systems;private final GameRankMapper ranks;private final CustomerGameProfileMapper profiles;private final CustomerGameRankMapper profileRanks;private final PlayerGameMapper playerGames;private final OrderGameProfileMapper orderProfiles;
 public GameConfigService(GameMapper games,GameServerMapper servers,GameRankSystemMapper systems,GameRankMapper ranks,CustomerGameProfileMapper profiles,CustomerGameRankMapper profileRanks,PlayerGameMapper playerGames,OrderGameProfileMapper orderProfiles){this.games=games;this.servers=servers;this.systems=systems;this.ranks=ranks;this.profiles=profiles;this.profileRanks=profileRanks;this.playerGames=playerGames;this.orderProfiles=orderProfiles;}
 public Map<String,Object> config(long gameId,boolean enabledOnly){requireGame(gameId);var sq=new QueryWrapper<GameServerEntity>().eq("game_id",gameId);var yq=new QueryWrapper<GameRankSystemEntity>().eq("game_id",gameId);if(enabledOnly){sq.eq("enabled",true);yq.eq("enabled",true);}sq.orderByAsc("sort_no","id");yq.orderByAsc("sort_no","id");var serverRows=servers.selectList(sq).stream().map(this::serverView).toList();var systemRows=systems.selectList(yq).stream().map(s->{var x=systemView(s);var rq=new QueryWrapper<GameRankEntity>().eq("rank_system_id",s.id);if(enabledOnly)rq.eq("enabled",true);rq.orderByAsc("sort_no","id");x.put("ranks",ranks.selectList(rq).stream().map(this::rankView).toList());return x;}).toList();return Map.of("servers",serverRows,"rankSystems",systemRows);}
 public long saveServer(Long id,long gameId,ServerCommand c){requireGame(gameId);required(c.serverCode(),"区服编码不能为空");required(c.serverName(),"区服名称不能为空");try{var x=id==null?new GameServerEntity():requireServer(id,gameId);x.gameId=gameId;x.serverCode=c.serverCode().trim().toUpperCase(Locale.ROOT);x.serverName=c.serverName().trim();x.sortNo=c.sortNo();x.enabled=c.enabled();if(id==null)servers.insert(x);else servers.updateById(x);return x.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("该游戏的区服编码已存在");}}
 public long saveSystem(Long id,long gameId,RankSystemCommand c){requireGame(gameId);required(c.systemCode(),"段位体系编码不能为空");required(c.systemName(),"段位体系名称不能为空");try{var x=id==null?new GameRankSystemEntity():requireSystem(id,gameId);x.gameId=gameId;x.systemCode=c.systemCode().trim().toUpperCase(Locale.ROOT);x.systemName=c.systemName().trim();x.description=c.description();x.sortNo=c.sortNo();x.enabled=c.enabled();if(id==null)systems.insert(x);else systems.updateById(x);return x.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("该游戏的段位体系编码已存在");}}
 public long saveRank(Long id,long systemId,RankCommand c){var system=systems.selectById(systemId);if(system==null)throw new IllegalArgumentException("段位体系不存在");required(c.rankCode(),"段位编码不能为空");required(c.rankName(),"段位名称不能为空");try{var x=id==null?new GameRankEntity():requireRank(id,systemId);x.rankSystemId=systemId;x.rankCode=c.rankCode().trim().toUpperCase(Locale.ROOT);x.rankName=c.rankName().trim();x.tierNo=c.tierNo();x.sortNo=c.sortNo();x.enabled=c.enabled();if(id==null)ranks.insert(x);else ranks.updateById(x);return x.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("该体系的段位编码已存在");}}
 public void deleteServer(long id){if(profiles.selectCount(new QueryWrapper<CustomerGameProfileEntity>().eq("server_id",id))>0||playerGames.selectCount(new QueryWrapper<PlayerGameEntity>().eq("server_id",id))>0||orderProfiles.selectCount(new QueryWrapper<OrderGameProfileEntity>().eq("server_id",id))>0)throw new IllegalArgumentException("该区服已有账号、陪玩师或订单使用，不能删除");servers.deleteById(id);}
 @Transactional public void deleteSystem(long id){var rankIds=ranks.selectList(new QueryWrapper<GameRankEntity>().select("id").eq("rank_system_id",id)).stream().map(x->x.id).toList();boolean used=profileRanks.selectCount(new QueryWrapper<CustomerGameRankEntity>().eq("rank_system_id",id))>0;if(!rankIds.isEmpty())used=used||playerGames.selectCount(new QueryWrapper<PlayerGameEntity>().in("rank_id",rankIds))>0||orderProfiles.selectCount(new QueryWrapper<OrderGameProfileEntity>().in("current_rank_id",rankIds).or().in("target_rank_id",rankIds))>0;if(used)throw new IllegalArgumentException("该段位体系已有账号、陪玩师或订单使用，不能删除");ranks.delete(new QueryWrapper<GameRankEntity>().eq("rank_system_id",id));systems.deleteById(id);}
 public void deleteRank(long id){if(profileRanks.selectCount(new QueryWrapper<CustomerGameRankEntity>().eq("rank_id",id))>0||playerGames.selectCount(new QueryWrapper<PlayerGameEntity>().eq("rank_id",id))>0||orderProfiles.selectCount(new QueryWrapper<OrderGameProfileEntity>().eq("current_rank_id",id).or().eq("target_rank_id",id))>0)throw new IllegalArgumentException("该段位已有账号、陪玩师或订单使用，不能删除");ranks.deleteById(id);}
 @Transactional public void initializeDefaults(long gameId){saveServer(null,gameId,new ServerCommand("CN","国服",1,true));long systemId=saveSystem(null,gameId,new RankSystemCommand("DEFAULT","综合段位","该游戏默认段位体系",1,true));String[][] values={{"BRONZE","青铜"},{"SILVER","白银"},{"GOLD","黄金"},{"PLATINUM","铂金"},{"DIAMOND","钻石"},{"MASTER","大师"},{"TOP","巅峰"}};for(int i=0;i<values.length;i++)saveRank(null,systemId,new RankCommand(values[i][0],values[i][1],i+1,i+1,true));}
 @Transactional public void deleteByGame(long gameId){var ids=systems.selectList(new QueryWrapper<GameRankSystemEntity>().select("id").eq("game_id",gameId)).stream().map(x->x.id).toList();if(!ids.isEmpty())ranks.delete(new QueryWrapper<GameRankEntity>().in("rank_system_id",ids));systems.delete(new QueryWrapper<GameRankSystemEntity>().eq("game_id",gameId));servers.delete(new QueryWrapper<GameServerEntity>().eq("game_id",gameId));}
 private GameEntity requireGame(long id){var x=games.selectById(id);if(x==null)throw new IllegalArgumentException("游戏不存在");return x;}private GameServerEntity requireServer(long id,long gameId){var x=servers.selectById(id);if(x==null||!Objects.equals(x.gameId,gameId))throw new IllegalArgumentException("区服不存在");return x;}private GameRankSystemEntity requireSystem(long id,long gameId){var x=systems.selectById(id);if(x==null||!Objects.equals(x.gameId,gameId))throw new IllegalArgumentException("段位体系不存在");return x;}private GameRankEntity requireRank(long id,long systemId){var x=ranks.selectById(id);if(x==null||!Objects.equals(x.rankSystemId,systemId))throw new IllegalArgumentException("段位不存在");return x;}private void required(String v,String message){if(v==null||v.isBlank())throw new IllegalArgumentException(message);}
 private Map<String,Object> serverView(GameServerEntity x){return map("id",x.id,"gameId",x.gameId,"serverCode",x.serverCode,"serverName",x.serverName,"sortNo",x.sortNo,"enabled",x.enabled);}private LinkedHashMap<String,Object> systemView(GameRankSystemEntity x){return map("id",x.id,"gameId",x.gameId,"systemCode",x.systemCode,"systemName",x.systemName,"description",x.description,"sortNo",x.sortNo,"enabled",x.enabled);}private Map<String,Object> rankView(GameRankEntity x){return map("id",x.id,"rankSystemId",x.rankSystemId,"rankCode",x.rankCode,"rankName",x.rankName,"tierNo",x.tierNo,"sortNo",x.sortNo,"enabled",x.enabled);}private LinkedHashMap<String,Object> map(Object...v){var x=new LinkedHashMap<String,Object>();for(int i=0;i<v.length;i+=2)x.put((String)v[i],v[i+1]);return x;}
 public record ServerCommand(String serverCode,String serverName,int sortNo,boolean enabled){}public record RankSystemCommand(String systemCode,String systemName,String description,int sortNo,boolean enabled){}public record RankCommand(String rankCode,String rankName,int tierNo,int sortNo,boolean enabled){}
}
