package com.peiwan.platform.player;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.peiwan.platform.persistence.entity.*;
import com.peiwan.platform.persistence.mapper.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Service
public class PlayerService {
  private final GameMapper gameMapper;private final GamePositionMapper positionMapper;private final PlayerTagMapper tagMapper;private final PlayerRelationMapper relations;private final PlayerMapper playerMapper;private final SystemUserMapper userMapper;private final PlayerStatusLogMapper statusLogMapper;private final PlayerAuditMapper auditMapper;private final PlayerDetailMapper details;private final PlayerGameMapper playerGameMapper;private final PlayerLevelMapper playerLevelMapper;private final PlayerMediaMapper mediaMapper;private final GameConfigService gameConfigs;private final GameServerMapper gameServers;private final GameRankMapper gameRanks;private final GameRankSystemMapper rankSystems;
  public PlayerService(GameMapper gameMapper,GamePositionMapper positionMapper,PlayerTagMapper tagMapper,PlayerRelationMapper relations,PlayerMapper playerMapper,SystemUserMapper userMapper,PlayerStatusLogMapper statusLogMapper,PlayerAuditMapper auditMapper,PlayerDetailMapper details,PlayerGameMapper playerGameMapper,PlayerLevelMapper playerLevelMapper,PlayerMediaMapper mediaMapper,GameConfigService gameConfigs,GameServerMapper gameServers,GameRankMapper gameRanks,GameRankSystemMapper rankSystems){this.gameMapper=gameMapper;this.positionMapper=positionMapper;this.tagMapper=tagMapper;this.relations=relations;this.playerMapper=playerMapper;this.userMapper=userMapper;this.statusLogMapper=statusLogMapper;this.auditMapper=auditMapper;this.details=details;this.playerGameMapper=playerGameMapper;this.playerLevelMapper=playerLevelMapper;this.mediaMapper=mediaMapper;this.gameConfigs=gameConfigs;this.gameServers=gameServers;this.gameRanks=gameRanks;this.rankSystems=rankSystems;}
  public void setCapacity(long playerId,int maxActiveOrders,long operator){var p=requirePlayerEntity(playerId);if(maxActiveOrders<1||maxActiveOrders>20)throw new IllegalArgumentException("最大同时接单数必须在1到20之间");long active=relations.activeOrderCount(playerId);if(maxActiveOrders<active)throw new IllegalArgumentException("设置值不能小于当前进行中订单数");p.maxActiveOrders=maxActiveOrders;p.updatedBy=operator;p.updatedAt=java.time.LocalDateTime.now();playerMapper.updateById(p);}
  public List<Map<String,Object>> userOptions(Long playerId){return details.userOptions(playerId==null?-1L:playerId).stream().<Map<String,Object>>map(r->{var x=new LinkedHashMap<String,Object>();x.put("id",r.get("id"));x.put("username",r.get("username"));x.put("label",Objects.toString(r.get("nickname"),Objects.toString(r.get("username"))));x.put("phone",r.get("phone"));return x;}).toList();}

  public Map<String,Object> games(int current,int size,String name,Boolean enabled){current=pageNo(current);size=pageSize(size);var q=new QueryWrapper<GameEntity>().like("game_name",s(name));if(enabled!=null)q.eq("enabled",enabled);q.orderByAsc("sort_no").orderByDesc("id");var result=gameMapper.selectPage(Page.of(current,size),q);return page(result.getRecords().stream().map(this::gameView).toList(),current,size,result.getTotal());}
  public List<Map<String,Object>> gameOptions(){return gameMapper.selectList(new QueryWrapper<GameEntity>().eq("enabled",true).orderByAsc("sort_no","id")).stream().map(this::gameView).toList();}
  @Transactional public long saveGame(Long id,GameCommand c){required(c.gameCode(),"游戏编码不能为空");required(c.gameName(),"游戏名称不能为空");try{var g=id==null?new GameEntity():requireGame(id);g.gameCode=c.gameCode();g.gameName=c.gameName();g.iconUrl=c.iconUrl();g.coverUrl=c.coverUrl();g.platformType=defaultValue(c.platformType(),"OTHER");g.description=c.description();g.sortNo=c.sortNo();g.enabled=c.enabled();if(id==null){gameMapper.insert(g);createDefaultPlayerLevels(g.id);gameConfigs.initializeDefaults(g.id);}else{g.updatedAt=java.time.LocalDateTime.now();gameMapper.updateById(g);}return g.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("游戏编码已存在");}}
  public void gameStatus(long id,boolean enabled){var g=requireGame(id);if(!enabled&&relations.onSaleProductCount(id)>0)throw new IllegalArgumentException("该游戏存在上架商品，不能禁用");g.enabled=enabled;g.updatedAt=java.time.LocalDateTime.now();gameMapper.updateById(g);}
  @Transactional public void deleteGame(long id){requireGame(id);if(relations.playerGameCount(id)>0)throw new IllegalArgumentException("该游戏已有陪玩师资料，不能删除");if(relations.productCount(id)>0)throw new IllegalArgumentException("该游戏已被商品使用，不能删除");relations.deleteGamePositions(id);playerLevelMapper.delete(new QueryWrapper<PlayerLevelEntity>().eq("game_id",id));gameConfigs.deleteByGame(id);gameMapper.deleteById(id);}
  private void createDefaultPlayerLevels(long gameId){String[][] defaults={{"STARTER","新锐","平台认证基础等级"},{"PRO","进阶","经验丰富的进阶陪玩师"},{"MASTER","大神","高水平认证陪玩师"}};for(int i=0;i<defaults.length;i++){var level=new PlayerLevelEntity();level.gameId=gameId;level.levelCode=defaults[i][0];level.levelName=defaults[i][1];level.description=defaults[i][2];level.sortNo=i+1;level.enabled=true;playerLevelMapper.insert(level);}}
  public List<Map<String,Object>> positions(long gameId){requireGame(gameId);return positionMapper.selectList(new QueryWrapper<GamePositionEntity>().eq("game_id",gameId).orderByAsc("sort_no","id")).stream().map(this::positionView).toList();}
  public long savePosition(Long id,long gameId,PositionCommand c){requireGame(gameId);required(c.positionCode(),"位置编码不能为空");required(c.positionName(),"位置名称不能为空");try{var p=id==null?new GamePositionEntity():requirePosition(id);if(id!=null&&!Objects.equals(p.gameId,gameId))throw new IllegalArgumentException("游戏位置不存在");p.gameId=gameId;p.positionCode=c.positionCode();p.positionName=c.positionName();p.iconUrl=c.iconUrl();p.sortNo=c.sortNo();p.enabled=c.enabled();if(id==null)positionMapper.insert(p);else{p.updatedAt=java.time.LocalDateTime.now();positionMapper.updateById(p);}return p.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("该游戏的位置编码已存在");}}
  public void deletePosition(long id){requirePosition(id);if(relations.positionUseCount(id)>0)throw new IllegalArgumentException("该位置已被陪玩师使用，不能删除");positionMapper.deleteById(id);}

  public Map<String,Object> tags(int current,int size,String name,Boolean enabled){current=pageNo(current);size=pageSize(size);var q=new QueryWrapper<PlayerTagEntity>().like("tag_name",s(name));if(enabled!=null)q.eq("enabled",enabled);q.orderByAsc("sort_no").orderByDesc("id");var result=tagMapper.selectPage(Page.of(current,size),q);return page(result.getRecords().stream().map(this::tagView).toList(),current,size,result.getTotal());}
  public List<Map<String,Object>> tagOptions(){return tagMapper.selectList(new QueryWrapper<PlayerTagEntity>().eq("enabled",true).orderByAsc("sort_no","id")).stream().map(this::tagView).toList();}
  public long saveTag(Long id,TagCommand c){required(c.tagCode(),"标签编码不能为空");required(c.tagName(),"标签名称不能为空");try{var t=id==null?new PlayerTagEntity():requireTag(id);t.tagCode=c.tagCode();t.tagName=c.tagName();t.tagColor=c.tagColor();t.tagGroup=defaultValue(c.tagGroup(),"OTHER");t.sortNo=c.sortNo();t.enabled=c.enabled();if(id==null)tagMapper.insert(t);else{t.updatedAt=java.time.LocalDateTime.now();tagMapper.updateById(t);}return t.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("标签编码已存在");}}
  @Transactional public void deleteTag(long id){requireTag(id);relations.deleteTagRelations(id);tagMapper.deleteById(id);}

  public Map<String,Object> players(int current,int size,String keyword,String auditStatus,String workStatus,Boolean enabled){current=pageNo(current);size=pageSize(size);var result=details.players(new Page<>(current,size),s(keyword),auditStatus,workStatus,enabled);return page(result.getRecords().stream().map(this::playerView).toList(),current,size,result.getTotal());}
  public Map<String,Object> customerPlayers(int current,int size,String keyword,String workStatus,Long gameId,Long playerLevelId,Long skuId,Long tagId,String gender,String sort){current=pageNo(current);size=pageSize(size);var result=gameId==null?details.players(new Page<>(current,size),s(keyword),"APPROVED",workStatus,true):details.customerPlayersByGame(new Page<>(current,size),s(keyword),workStatus,gameId,playerLevelId,skuId,tagId,s(gender),defaultValue(sort,"DEFAULT"));return page(result.getRecords().stream().map(this::customerPlayerView).toList(),current,size,result.getTotal());}
  public Map<String,Object> customerPlayer(long id){var row=details.playerDetail(id);if(row==null||!Boolean.TRUE.equals(row.get("enabled"))||!"APPROVED".equals(row.get("audit_status")))throw new IllegalArgumentException("陪玩师不存在或已停止服务");var x=new LinkedHashMap<>(customerPlayerView(row));x.put("games",details.playerGames(id).stream().filter(g->Boolean.TRUE.equals(g.get("enabled"))&&"APPROVED".equals(g.get("audit_status"))).map(this::customerPlayerGameView).toList());x.put("media",details.media(id).stream().filter(m->Boolean.TRUE.equals(m.get("enabled"))&&"APPROVED".equals(m.get("audit_status"))).map(this::customerMediaView).toList());return x;}
  public Map<String,Object> player(long id){var row=details.playerDetail(id);if(row==null)throw new IllegalArgumentException("陪玩师不存在");var x=new LinkedHashMap<>(playerView(row));x.put("tagIds",details.tagIds(id));x.put("games",details.playerGames(id).stream().map(this::playerGameView).toList());x.put("media",details.media(id).stream().map(this::mediaView).toList());x.put("audits",details.audits(id));return x;}
  @Transactional public long createPlayer(PlayerCommand c,long operator){validatePlayer(c);var p=new PlayerEntity();p.playerNo="TMP"+UUID.randomUUID().toString().replace("-","").substring(0,20);applyPlayer(p,c,operator);p.auditStatus="DRAFT";p.workStatus="OFFLINE";p.createdBy=operator;playerMapper.insert(p);p.playerNo=String.format("PW%012d",p.id);playerMapper.updateById(p);replaceRelations(p.id,c);return p.id;}
  @Transactional public void updatePlayer(long id,PlayerCommand c,long operator){var p=requirePlayerEntity(id);validatePlayer(c);applyPlayer(p,c,operator);playerMapper.updateById(p);replaceRelations(id,c);}
  @Transactional public void setStatus(long id,String workStatus,Boolean enabled,String reason,long operator){var p=requirePlayerEntity(id);if(enabled!=null&&!enabled){logStatus(id,"ENABLED",p.enabled,false,reason,operator);p.enabled=false;p.workStatus="SUSPENDED";touch(p,operator);playerMapper.updateById(p);return;}if(enabled!=null){logStatus(id,"ENABLED",p.enabled,true,reason,operator);p.enabled=true;touch(p,operator);playerMapper.updateById(p);}if(notBlank(workStatus)){if(!Set.of("OFFLINE","AVAILABLE","BUSY","SUSPENDED").contains(workStatus))throw new IllegalArgumentException("接单状态无效");var latest=requirePlayerEntity(id);if("AVAILABLE".equals(workStatus)&&(!Boolean.TRUE.equals(latest.enabled)||!"APPROVED".equals(latest.auditStatus)))throw new IllegalArgumentException("只有审核通过且已启用的陪玩师可以接单");logStatus(id,"WORK_STATUS",latest.workStatus,workStatus,reason,operator);latest.workStatus=workStatus;touch(latest,operator);playerMapper.updateById(latest);}}
  @Transactional public void audit(long id,String result,String reason,long operator){var p=requirePlayerEntity(id);if(!Set.of("APPROVED","REJECTED").contains(result))throw new IllegalArgumentException("审核结果无效");if("REJECTED".equals(result)&&!notBlank(reason))throw new IllegalArgumentException("审核拒绝必须填写原因");String before=s(p.auditStatus);var update=new UpdateWrapper<PlayerEntity>().eq("id",id).set("audit_status",result).set("audit_remark",reason).set("approved_at","APPROVED".equals(result)?java.time.LocalDateTime.now():null).set("updated_by",operator).set("updated_at",java.time.LocalDateTime.now());if("REJECTED".equals(result))update.set("work_status","SUSPENDED");playerMapper.update(null,update);playerGameMapper.update(null,new UpdateWrapper<PlayerGameEntity>().eq("player_id",id).set("audit_status",result).set("updated_at",java.time.LocalDateTime.now()));var a=new PlayerAuditEntity();a.playerId=id;a.auditType="PROFILE";a.beforeStatus=before;a.afterStatus=result;a.result=result;a.reason=reason;a.auditorId=operator;a.auditedAt=java.time.LocalDateTime.now();auditMapper.insert(a);logStatus(id,"AUDIT_STATUS",before,result,reason,operator);}

  private void replaceRelations(long id,PlayerCommand c){relations.deletePlayerTags(id);var tags=new LinkedHashSet<>(c.tagIds()==null?List.of():c.tagIds());if(tags.size()>8)throw new IllegalArgumentException("每位陪玩师最多选择8个标签");for(var tag:tags){requireTag(tag);relations.addPlayerTag(id,tag);}relations.deletePlayerGamePositions(id);relations.deletePlayerGames(id);int primary=0;for(var g:c.games()==null?List.<PlayerGameCommand>of():c.games()){requireGame(g.gameId());Long priceLevelId=g.priceLevelId()==null?defaultPriceLevelId(g.gameId()):g.priceLevelId();var priceLevel=playerLevelMapper.selectById(priceLevelId);if(priceLevel==null||!Objects.equals(priceLevel.gameId,g.gameId()))throw new IllegalArgumentException("陪玩等级与所选游戏不匹配");var server=g.serverId()==null?null:gameServers.selectById(g.serverId());if(server!=null&&!Objects.equals(server.gameId,g.gameId()))throw new IllegalArgumentException("区服与所选游戏不匹配");var rank=g.rankId()==null?null:gameRanks.selectById(g.rankId());if(rank!=null){var system=rankSystems.selectById(rank.rankSystemId);if(system==null||!Objects.equals(system.gameId,g.gameId()))throw new IllegalArgumentException("段位与所选游戏不匹配");}if(g.primary())primary++;var pg=new PlayerGameEntity();pg.playerId=id;pg.gameId=g.gameId();pg.priceLevelId=priceLevelId;pg.serverId=server==null?null:server.id;pg.rankId=rank==null?null:rank.id;pg.gameNickname=g.gameNickname();pg.gameAccount=g.gameAccount();pg.serverName=server==null?g.serverName():server.serverName;pg.rankName=rank==null?g.rankName():rank.rankName;pg.rankLevel=g.rankLevel();pg.experienceYears=g.experienceYears();pg.introduction=g.introduction();pg.proofUrl=g.proofUrl();pg.isPrimary=g.primary();pg.auditStatus="PENDING";pg.enabled=g.enabled();playerGameMapper.insert(pg);var positionIds=new LinkedHashSet<>(g.positionIds()==null?List.of():g.positionIds());if(g.primaryPositionId()!=null&&!positionIds.contains(g.primaryPositionId()))throw new IllegalArgumentException("主位置必须包含在擅长位置中");for(var positionId:positionIds){var pos=requirePosition(positionId);if(!Objects.equals(pos.gameId,g.gameId()))throw new IllegalArgumentException("擅长位置与所选游戏不匹配");relations.addGamePosition(pg.id,positionId,Objects.equals(positionId,g.primaryPositionId()));}}if(primary>1)throw new IllegalArgumentException("只能设置一个主游戏");relations.deletePlayerMedia(id);for(var m:c.media()==null?List.<MediaCommand>of():c.media()){if(!notBlank(m.mediaUrl()))continue;var media=new PlayerMediaEntity();media.playerId=id;media.mediaType=defaultValue(m.mediaType(),"PHOTO");media.mediaUrl=m.mediaUrl();media.thumbnailUrl=m.thumbnailUrl();media.title=m.title();media.sortNo=m.sortNo();media.enabled=m.enabled();mediaMapper.insert(media);}}
  private Long defaultPriceLevelId(long gameId){var row=playerLevelMapper.selectOne(new QueryWrapper<PlayerLevelEntity>().eq("game_id",gameId).eq("enabled",true).orderByAsc("sort_no","id").last("limit 1"));if(row==null)throw new IllegalArgumentException("该游戏尚未配置陪玩等级");return row.id;}
  private void validatePlayer(PlayerCommand c){required(c.nickname(),"陪玩师昵称不能为空");if(c.userId()!=null&&userMapper.selectById(c.userId())==null)throw new IllegalArgumentException("绑定用户不存在");}
  private void applyPlayer(PlayerEntity p,PlayerCommand c,long operator){p.userId=c.userId();p.nickname=c.nickname();p.realName=c.realName();p.gender=defaultValue(c.gender(),"UNKNOWN");p.phone=c.phone();p.email=c.email();p.avatarUrl=c.avatarUrl();p.coverUrl=c.coverUrl();p.introduction=c.introduction();p.voiceUrl=c.voiceUrl();p.enabled=c.enabled();p.sortNo=c.sortNo();p.remark=c.remark();p.updatedBy=operator;p.updatedAt=java.time.LocalDateTime.now();}
  private void logStatus(long id,String type,Object before,Object after,String reason,long op){var log=new PlayerStatusLogEntity();log.playerId=id;log.statusType=type;log.beforeValue=s(before);log.afterValue=s(after);log.reason=reason;log.operatorType="ADMIN";log.operatorId=op;statusLogMapper.insert(log);}
  private void touch(PlayerEntity p,long operator){p.updatedBy=operator;p.updatedAt=java.time.LocalDateTime.now();}
  private Map<String,Object> gameView(Map<String,Object> r){return view(r,new String[][]{{"id","id"},{"gameCode","game_code"},{"gameName","game_name"},{"iconUrl","icon_url"},{"coverUrl","cover_url"},{"platformType","platform_type"},{"description","description"},{"sortNo","sort_no"},{"enabled","enabled"},{"createTime","created_at"}});}
  private Map<String,Object> gameView(GameEntity r){var x=new LinkedHashMap<String,Object>();x.put("id",r.id);x.put("gameCode",r.gameCode);x.put("gameName",r.gameName);x.put("iconUrl",r.iconUrl);x.put("coverUrl",r.coverUrl);x.put("platformType",r.platformType);x.put("description",r.description);x.put("sortNo",r.sortNo);x.put("enabled",r.enabled);x.put("createTime",r.createdAt);return x;}
  private Map<String,Object> tagView(Map<String,Object> r){return view(r,new String[][]{{"id","id"},{"tagCode","tag_code"},{"tagName","tag_name"},{"tagColor","tag_color"},{"tagGroup","tag_group"},{"sortNo","sort_no"},{"enabled","enabled"},{"createTime","created_at"}});}
  private Map<String,Object> tagView(PlayerTagEntity r){var x=new LinkedHashMap<String,Object>();x.put("id",r.id);x.put("tagCode",r.tagCode);x.put("tagName",r.tagName);x.put("tagColor",r.tagColor);x.put("tagGroup",r.tagGroup);x.put("sortNo",r.sortNo);x.put("enabled",r.enabled);x.put("createTime",r.createdAt);return x;}
  private Map<String,Object> positionView(Map<String,Object> r){return view(r,new String[][]{{"id","id"},{"gameId","game_id"},{"positionCode","position_code"},{"positionName","position_name"},{"iconUrl","icon_url"},{"sortNo","sort_no"},{"enabled","enabled"}});}
  private Map<String,Object> positionView(GamePositionEntity r){var x=new LinkedHashMap<String,Object>();x.put("id",r.id);x.put("gameId",r.gameId);x.put("positionCode",r.positionCode);x.put("positionName",r.positionName);x.put("iconUrl",r.iconUrl);x.put("sortNo",r.sortNo);x.put("enabled",r.enabled);return x;}
  private Map<String,Object> playerView(Map<String,Object> r){var x=view(r,new String[][]{{"id","id"},{"playerNo","player_no"},{"userId","user_id"},{"nickname","nickname"},{"realName","real_name"},{"gender","gender"},{"phone","phone"},{"email","email"},{"avatarUrl","avatar_url"},{"coverUrl","cover_url"},{"introduction","introduction"},{"voiceUrl","voice_url"},{"auditStatus","audit_status"},{"workStatus","work_status"},{"enabled","enabled"},{"auditRemark","audit_remark"},{"maxActiveOrders","max_active_orders"},{"orderCount","order_count"},{"ratingScore","rating_score"},{"ratingCount","rating_count"},{"sortNo","sort_no"},{"remark","remark"},{"createTime","created_at"}});x.put("primaryGame",r.get("primary_game"));return x;}
  private Map<String,Object> customerPlayerView(Map<String,Object> r){long id=((Number)r.get("id")).longValue();var x=view(r,new String[][]{{"id","id"},{"playerNo","player_no"},{"nickname","nickname"},{"gender","gender"},{"avatarUrl","avatar_url"},{"coverUrl","cover_url"},{"introduction","introduction"},{"workStatus","work_status"},{"orderCount","order_count"},{"ratingScore","rating_score"},{"ratingCount","rating_count"},{"gameId","game_id"},{"gameNickname","game_nickname"},{"playerRankName","player_rank_name"},{"playerLevelId","price_level_id"},{"playerLevelCode","level_code"},{"playerLevelName","level_name"},{"servicePrice","service_price"}});x.put("primaryGame",r.get("primary_game"));x.put("tags",details.playerTags(id).stream().map(this::tagView).toList());return x;}
  private Map<String,Object> customerPlayerGameView(Map<String,Object> r){return view(r,new String[][]{{"id","id"},{"gameId","game_id"},{"gameName","game_name"},{"playerLevelId","price_level_id"},{"playerLevelName","price_level_name"},{"serverName","server_name"},{"rankName","rank_name"},{"experienceYears","experience_years"},{"introduction","introduction"},{"primary","is_primary"}});}
  private Map<String,Object> customerMediaView(Map<String,Object> r){return view(r,new String[][]{{"id","id"},{"mediaType","media_type"},{"mediaUrl","media_url"},{"thumbnailUrl","thumbnail_url"},{"title","title"},{"sortNo","sort_no"}});}
  private Map<String,Object> playerGameView(Map<String,Object> r){var x=view(r,new String[][]{{"id","id"},{"gameId","game_id"},{"gameName","game_name"},{"priceLevelId","price_level_id"},{"priceLevelName","price_level_name"},{"serverId","server_id"},{"rankId","rank_id"},{"gameNickname","game_nickname"},{"gameAccount","game_account"},{"serverName","server_name"},{"rankName","rank_name"},{"rankLevel","rank_level"},{"experienceYears","experience_years"},{"introduction","introduction"},{"proofUrl","proof_url"},{"primary","is_primary"},{"auditStatus","audit_status"},{"enabled","enabled"}});long pgId=((Number)r.get("id")).longValue();x.put("positionIds",details.positionIds(pgId));x.put("primaryPositionId",details.primaryPositionId(pgId));return x;}
  private Map<String,Object> mediaView(Map<String,Object> r){return view(r,new String[][]{{"id","id"},{"mediaType","media_type"},{"mediaUrl","media_url"},{"thumbnailUrl","thumbnail_url"},{"title","title"},{"sortNo","sort_no"},{"auditStatus","audit_status"},{"enabled","enabled"}});}
  private Map<String,Object> view(Map<String,Object> r,String[][] fields){var x=new LinkedHashMap<String,Object>();for(var f:fields)x.put(f[0],r.get(f[1]));return x;}
  private PlayerEntity requirePlayerEntity(long id){var x=playerMapper.selectById(id);if(x==null)throw new IllegalArgumentException("陪玩师不存在");return x;}private GameEntity requireGame(long id){var x=gameMapper.selectById(id);if(x==null)throw new IllegalArgumentException("游戏不存在");return x;}private PlayerTagEntity requireTag(long id){var x=tagMapper.selectById(id);if(x==null)throw new IllegalArgumentException("标签不存在");return x;}private GamePositionEntity requirePosition(long id){var x=positionMapper.selectById(id);if(x==null)throw new IllegalArgumentException("游戏位置不存在");return x;}
  private int pageNo(int n){return Math.max(n,1);}private int pageSize(int n){return Math.min(Math.max(n,1),200);}private Map<String,Object> page(Object r,int c,int s,long t){return Map.of("records",r,"current",c,"size",s,"total",t);}private String s(Object v){return Objects.toString(v,"");}private boolean notBlank(String v){return v!=null&&!v.isBlank();}private String defaultValue(String v,String d){return notBlank(v)?v:d;}private void required(String v,String msg){if(!notBlank(v))throw new IllegalArgumentException(msg);}
  public record GameCommand(String gameCode,String gameName,String iconUrl,String coverUrl,String platformType,String description,int sortNo,boolean enabled){}
  public record PositionCommand(String positionCode,String positionName,String iconUrl,int sortNo,boolean enabled){}
  public record TagCommand(String tagCode,String tagName,String tagColor,String tagGroup,int sortNo,boolean enabled){}
  public record PlayerCommand(Long userId,String nickname,String realName,String gender,String phone,String email,String avatarUrl,String coverUrl,String introduction,String voiceUrl,boolean enabled,int sortNo,String remark,List<Long>tagIds,List<PlayerGameCommand>games,List<MediaCommand>media){}
  public record PlayerGameCommand(long gameId,Long priceLevelId,Long serverId,Long rankId,String gameNickname,String gameAccount,String serverName,String rankName,Integer rankLevel,Integer experienceYears,String introduction,String proofUrl,boolean primary,boolean enabled,List<Long>positionIds,Long primaryPositionId){}
  public record MediaCommand(String mediaType,String mediaUrl,String thumbnailUrl,String title,int sortNo,boolean enabled){}
}
