package com.peiwan.platform.player;

import com.peiwan.platform.common.*;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import java.util.Map;

@RestController
@RequestMapping("/api/business")
public class PlayerController {
  private final PlayerService service;private final AuditService audit;
  public PlayerController(PlayerService service,AuditService audit){this.service=service;this.audit=audit;}
  @PreAuthorize("hasAuthority('business:player:update') or hasRole('admin')") @PutMapping("/player/{id}/capacity") public ApiResponse<?> playerCapacity(Authentication a,@PathVariable long id,@RequestBody CapacityBody b,HttpServletRequest r){service.setCapacity(id,b.maxActiveOrders(),(Long)a.getPrincipal());audit.operation(a,"business:player:update","PLAYER",id,"maxActiveOrders="+b.maxActiveOrders(),r);return ApiResponse.ok();}
  @PreAuthorize("hasAnyAuthority('business:player:create','business:player:update') or hasRole('admin')") @GetMapping("/player/user-options") public ApiResponse<?> playerUserOptions(@RequestParam(required=false)Long playerId){return ApiResponse.ok(service.userOptions(playerId));}
  @PreAuthorize("hasAuthority('business:game:list') or hasRole('admin')") @GetMapping("/game/list") public ApiResponse<?> games(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String gameName,@RequestParam(required=false)Boolean enabled){return ApiResponse.ok(service.games(current,size,gameName,enabled));}
  @PreAuthorize("hasAnyAuthority('business:player:create','business:player:update','business:game:list') or hasRole('admin')") @GetMapping("/game/options") public ApiResponse<?> gameOptions(){return ApiResponse.ok(service.gameOptions());}
  @PreAuthorize("hasAuthority('business:game:create') or hasRole('admin')") @PostMapping("/game") public ApiResponse<?> createGame(Authentication a,@RequestBody PlayerService.GameCommand b,HttpServletRequest r){long id=service.saveGame(null,b);audit.operation(a,"business:game:create","GAME",id,b.gameName(),r);return ApiResponse.ok(Map.of("id",id));}
  @PreAuthorize("hasAuthority('business:game:update') or hasRole('admin')") @PutMapping("/game/{id}") public ApiResponse<?> updateGame(Authentication a,@PathVariable long id,@RequestBody PlayerService.GameCommand b,HttpServletRequest r){service.saveGame(id,b);audit.operation(a,"business:game:update","GAME",id,b.gameName(),r);return ApiResponse.ok();}
  @PreAuthorize("hasAuthority('business:game:status') or hasRole('admin')") @PutMapping("/game/{id}/status") public ApiResponse<?> gameStatus(Authentication a,@PathVariable long id,@RequestBody StatusBody b,HttpServletRequest r){service.gameStatus(id,b.enabled());audit.operation(a,"business:game:status","GAME",id,"enabled="+b.enabled(),r);return ApiResponse.ok();}
  @PreAuthorize("hasAuthority('business:game:delete') or hasRole('admin')") @DeleteMapping("/game/{id}") public ApiResponse<?> deleteGame(Authentication a,@PathVariable long id,HttpServletRequest r){service.deleteGame(id);audit.operation(a,"business:game:delete","GAME",id,"删除游戏",r);return ApiResponse.ok();}
  @PreAuthorize("hasAnyAuthority('business:game-position:list','business:player:create','business:player:update') or hasRole('admin')") @GetMapping("/game/{gameId}/positions") public ApiResponse<?> positions(@PathVariable long gameId){return ApiResponse.ok(service.positions(gameId));}
  @PreAuthorize("hasAuthority('business:game-position:create') or hasRole('admin')") @PostMapping("/game/{gameId}/position") public ApiResponse<?> createPosition(Authentication a,@PathVariable long gameId,@RequestBody PlayerService.PositionCommand b,HttpServletRequest r){long id=service.savePosition(null,gameId,b);audit.operation(a,"business:game-position:create","GAME_POSITION",id,b.positionName(),r);return ApiResponse.ok(Map.of("id",id));}
  @PreAuthorize("hasAuthority('business:game-position:update') or hasRole('admin')") @PutMapping("/game/{gameId}/position/{id}") public ApiResponse<?> updatePosition(Authentication a,@PathVariable long gameId,@PathVariable long id,@RequestBody PlayerService.PositionCommand b,HttpServletRequest r){service.savePosition(id,gameId,b);audit.operation(a,"business:game-position:update","GAME_POSITION",id,b.positionName(),r);return ApiResponse.ok();}
  @PreAuthorize("hasAuthority('business:game-position:delete') or hasRole('admin')") @DeleteMapping("/game/position/{id}") public ApiResponse<?> deletePosition(Authentication a,@PathVariable long id,HttpServletRequest r){service.deletePosition(id);audit.operation(a,"business:game-position:delete","GAME_POSITION",id,"删除游戏位置",r);return ApiResponse.ok();}
  @PreAuthorize("hasAuthority('business:player-tag:list') or hasRole('admin')") @GetMapping("/player-tag/list") public ApiResponse<?> tags(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String tagName,@RequestParam(required=false)Boolean enabled){return ApiResponse.ok(service.tags(current,size,tagName,enabled));}
  @PreAuthorize("hasAnyAuthority('business:player:create','business:player:update','business:player-tag:list') or hasRole('admin')") @GetMapping("/player-tag/options") public ApiResponse<?> tagOptions(){return ApiResponse.ok(service.tagOptions());}
  @PreAuthorize("hasAuthority('business:player-tag:create') or hasRole('admin')") @PostMapping("/player-tag") public ApiResponse<?> createTag(Authentication a,@RequestBody PlayerService.TagCommand b,HttpServletRequest r){long id=service.saveTag(null,b);audit.operation(a,"business:player-tag:create","PLAYER_TAG",id,b.tagName(),r);return ApiResponse.ok(Map.of("id",id));}
  @PreAuthorize("hasAuthority('business:player-tag:update') or hasRole('admin')") @PutMapping("/player-tag/{id}") public ApiResponse<?> updateTag(Authentication a,@PathVariable long id,@RequestBody PlayerService.TagCommand b,HttpServletRequest r){service.saveTag(id,b);audit.operation(a,"business:player-tag:update","PLAYER_TAG",id,b.tagName(),r);return ApiResponse.ok();}
  @PreAuthorize("hasAuthority('business:player-tag:delete') or hasRole('admin')") @DeleteMapping("/player-tag/{id}") public ApiResponse<?> deleteTag(Authentication a,@PathVariable long id,HttpServletRequest r){service.deleteTag(id);audit.operation(a,"business:player-tag:delete","PLAYER_TAG",id,"删除标签",r);return ApiResponse.ok();}
  @PreAuthorize("hasAuthority('business:player:list') or hasRole('admin')") @GetMapping("/player/list") public ApiResponse<?> players(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String keyword,@RequestParam(required=false)String auditStatus,@RequestParam(required=false)String workStatus,@RequestParam(required=false)Boolean enabled){return ApiResponse.ok(service.players(current,size,keyword,auditStatus,workStatus,enabled));}
  @PreAuthorize("hasAuthority('business:player:detail') or hasRole('admin')") @GetMapping("/player/{id}") public ApiResponse<?> player(@PathVariable long id){return ApiResponse.ok(service.player(id));}
  @PreAuthorize("hasAuthority('business:player:create') or hasRole('admin')") @PostMapping("/player") public ApiResponse<?> createPlayer(Authentication a,@RequestBody PlayerService.PlayerCommand b,HttpServletRequest r){long id=service.createPlayer(b,(Long)a.getPrincipal());audit.operation(a,"business:player:create","PLAYER",id,b.nickname(),r);return ApiResponse.ok(Map.of("id",id));}
  @PreAuthorize("hasAuthority('business:player:create') or hasRole('admin')") @PostMapping("/player/batch") public ApiResponse<?> batchCreatePlayers(Authentication a,@RequestBody PlayerService.BatchPlayerCommand b,HttpServletRequest r){var result=service.batchCreatePlayers(b,(Long)a.getPrincipal());audit.operation(a,"business:player:create","PLAYER_BATCH",null,"批量创建陪玩师：成功="+result.createdCount()+"，已存在="+result.existingPhones().size()+"，无效="+result.invalidPhones().size(),r);return ApiResponse.ok(result);}
  @PreAuthorize("hasAuthority('business:player:update') or hasRole('admin')") @PutMapping("/player/{id}") public ApiResponse<?> updatePlayer(Authentication a,@PathVariable long id,@RequestBody PlayerService.PlayerCommand b,HttpServletRequest r){service.updatePlayer(id,b,(Long)a.getPrincipal());audit.operation(a,"business:player:update","PLAYER",id,b.nickname(),r);return ApiResponse.ok();}
  @PreAuthorize("hasAuthority('business:player:status') or hasRole('admin')") @PutMapping("/player/{id}/status") public ApiResponse<?> playerStatus(Authentication a,@PathVariable long id,@RequestBody PlayerStatusBody b,HttpServletRequest r){service.setStatus(id,b.workStatus(),b.enabled(),b.reason(),(Long)a.getPrincipal());audit.operation(a,"business:player:status","PLAYER",id,"workStatus="+b.workStatus()+",enabled="+b.enabled(),r);return ApiResponse.ok();}
  @PreAuthorize("hasAuthority('business:player:audit') or hasRole('admin')") @PutMapping("/player/{id}/audit") public ApiResponse<?> auditPlayer(Authentication a,@PathVariable long id,@RequestBody AuditBody b,HttpServletRequest r){service.audit(id,b.result(),b.reason(),(Long)a.getPrincipal());audit.operation(a,"business:player:audit","PLAYER",id,b.result()+":"+b.reason(),r);return ApiResponse.ok();}
  public record StatusBody(boolean enabled){} public record CapacityBody(int maxActiveOrders){} public record PlayerStatusBody(String workStatus,Boolean enabled,String reason){} public record AuditBody(String result,String reason){}
}
