package com.peiwan.platform.portal;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.peiwan.platform.dispatch.DispatchService;import com.peiwan.platform.order.OrderService;import com.peiwan.platform.order.OrderMemberService;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service public class PlayerPortalService{
 private final PlayerMapper players;private final PlayerStatusLogMapper statusLogs;private final PlayerPortalDataMapper data;private final DispatchService dispatch;private final OrderService orders;private final OrderMemberService orderMembers;
 public PlayerPortalService(PlayerMapper players,PlayerStatusLogMapper statusLogs,PlayerPortalDataMapper data,DispatchService dispatch,OrderService orders,OrderMemberService orderMembers){this.players=players;this.statusLogs=statusLogs;this.data=data;this.dispatch=dispatch;this.orders=orders;this.orderMembers=orderMembers;}
 public Map<String,Object> workbench(long userId){var p=current(userId);var out=new LinkedHashMap<String,Object>();out.put("player",playerView(p));out.put("pendingDispatchCount",data.pendingDispatchCount(p.id));out.put("activeOrderCount",data.activeOrderCount(p.id));out.put("completedOrderCount",data.completedOrderCount(p.id));return out;}
 @Transactional public void workStatus(long userId,String target){var p=current(userId);if(!Set.of("AVAILABLE","OFFLINE").contains(target))throw new IllegalArgumentException("只能切换为可接单或休息状态");String before=p.workStatus;if("BUSY".equals(before))throw new IllegalArgumentException("存在进行中订单，不能手动切换状态");if(Objects.equals(before,target))return;p.workStatus=target;if("AVAILABLE".equals(target))p.lastOnlineAt=LocalDateTime.now();p.updatedBy=userId;p.updatedAt=LocalDateTime.now();players.updateById(p);var l=new PlayerStatusLogEntity();l.playerId=p.id;l.statusType="WORK_STATUS";l.beforeValue=before;l.afterValue=target;l.reason="陪玩师工作台切换";l.operatorType="PLAYER";l.operatorId=userId;statusLogs.insert(l);}
 public List<Map<String,Object>> pendingDispatches(long userId){return data.pendingDispatches(current(userId).id).stream().map(this::dispatchView).toList();}
 @Transactional public void respond(long userId,long taskId,String action,String reason){var p=current(userId);int effective=1;if("ACCEPT".equals(action)){data.lockPlayer(p.id);p=current(userId);if(!Set.of("AVAILABLE","BUSY").contains(p.workStatus))throw new IllegalArgumentException("当前状态不能接受派单");Integer platform=data.platformMaxOrders();if(platform==null)throw new IllegalArgumentException("未配置启用的派单规则");effective=Math.min(p.maxActiveOrders,platform);if(data.capacityOrderCount(p.id)>=effective)throw new IllegalArgumentException("已达到最大同时接单数");}dispatch.respond(taskId,p.id,action,reason,userId);if("ACCEPT".equals(action)){p=players.selectById(p.id);p.workStatus=data.capacityOrderCount(p.id)>=effective?"BUSY":"AVAILABLE";p.updatedAt=LocalDateTime.now();players.updateById(p);}}
 public Map<String,Object> ownOrders(long userId,int current,int size,String status){long player=current(userId).id;current=Math.max(1,current);size=Math.min(100,Math.max(1,size));var result=data.ownOrders(new Page<>(current,size),player,status);return Map.of("records",result.getRecords().stream().map(this::orderView).toList(),"current",current,"size",size,"total",result.getTotal());}
 public Map<String,Object> ownOrder(long userId,long orderId){long player=current(userId).id;if(!orderMembers.belongs(orderId,player))throw new IllegalArgumentException("订单不存在或不属于当前陪玩师");return orders.detail(orderId);}
 private PlayerEntity current(long userId){var p=players.selectOne(new QueryWrapper<PlayerEntity>().eq("user_id",userId));if(p==null)throw new IllegalArgumentException("当前账号尚未绑定陪玩师资料");if(!Boolean.TRUE.equals(p.enabled))throw new IllegalArgumentException("陪玩师账号已停用");if(!"APPROVED".equals(p.auditStatus))throw new IllegalArgumentException("陪玩师资料尚未审核通过");return p;}
 private Map<String,Object> playerView(PlayerEntity r){return map("id",r.id,"playerNo",r.playerNo,"nickname",r.nickname,"avatarUrl",r.avatarUrl,"workStatus",r.workStatus,"ratingScore",r.ratingScore,"orderCount",r.orderCount);}private Map<String,Object> dispatchView(Map<String,Object>r){int required=((Number)r.getOrDefault("required_player_count",1)).intValue(),members=((Number)r.getOrDefault("member_count",0)).intValue();return map("taskId",r.get("task_id"),"taskNo",r.get("task_no"),"dispatchMode",r.get("dispatch_mode"),"deadlineAt",r.get("deadline_at"),"orderId",r.get("order_id"),"orderNo",r.get("order_no"),"orderStatus",r.get("order_status"),"requiredPlayerCount",required,"memberCount",members,"remainingPlayerCount",Math.max(0,required-members),"productName",r.get("product_name"),"skuName",r.get("sku_name"),"gameName",r.get("game_name"),"serverName",r.get("server_name"),"rankName",r.get("rank_name"),"extraRequirement",r.get("extra_requirement"));}private Map<String,Object> orderView(Map<String,Object>r){return map("id",r.get("id"),"orderNo",r.get("order_no"),"orderStatus",r.get("order_status"),"memberStatus",r.get("member_status"),"requiredPlayerCount",r.get("required_player_count"),"memberCount",r.get("member_count"),"productName",r.get("product_name"),"skuName",r.get("sku_name"),"gameName",r.get("game_name"),"serverName",r.get("server_name"),"rankName",r.get("rank_name"),"assignedAt",r.get("assigned_at"),"serviceStartedAt",r.get("service_started_at"),"completedAt",r.get("completed_at"));}private Map<String,Object> map(Object...v){var m=new LinkedHashMap<String,Object>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}
}
