package com.peiwan.platform.wallet;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.peiwan.platform.persistence.entity.*;import com.peiwan.platform.persistence.mapper.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.LocalDateTime;import java.time.format.DateTimeFormatter;import java.util.*;
@Service public class WalletService{
 private final WalletAccountMapper wallets;private final RechargePlanMapper plans;private final RechargeOrderMapper recharges;private final WalletTransactionMapper transactions;private final UserMemberMapper members;private final WalletDataMapper data;
 public WalletService(WalletAccountMapper wallets,RechargePlanMapper plans,RechargeOrderMapper recharges,WalletTransactionMapper transactions,UserMemberMapper members,WalletDataMapper data){this.wallets=wallets;this.plans=plans;this.recharges=recharges;this.transactions=transactions;this.members=members;this.data=data;}
 public Map<String,Object> summary(long uid){var w=ensureWallet(uid);return Map.of("account",walletView(w),"member",Objects.requireNonNullElse(data.member(uid),Map.of()));}
 public List<Map<String,Object>> enabledPlans(){return plans.selectList(new QueryWrapper<RechargePlanEntity>().eq("enabled",true).orderByAsc("sort_no","id")).stream().map(this::planView).toList();}
 public Map<String,Object> transactionPage(long uid,int current,int size,String type){current=Math.max(1,current);size=Math.min(100,Math.max(1,size));var result=data.transactions(new Page<>(current,size),uid,type);return Map.of("records",result.getRecords(),"current",current,"size",size,"total",result.getTotal());}
 @Transactional public Map<String,Object> simulateRecharge(long uid,long planId,String requestNo){if(requestNo==null||requestNo.isBlank()||requestNo.length()>64)throw new IllegalArgumentException("请求流水号不能为空且不能超过64位");requestNo=requestNo.trim();var existing=findRecharge(uid,requestNo);if(existing!=null)return rechargeView(existing,true);var plan=plans.selectById(planId);if(plan==null||!Boolean.TRUE.equals(plan.enabled))throw new IllegalArgumentException("充值套餐不存在或已停用");ensureWallet(uid);var locked=data.lockUserWallet(uid);if(locked==null)throw new IllegalArgumentException("钱包创建失败");existing=findRecharge(uid,requestNo);if(existing!=null)return rechargeView(existing,true);long accountId=((Number)locked.get("id")).longValue();BigDecimal beforeCash=(BigDecimal)locked.get("cash_balance");BigDecimal beforeBonus=(BigDecimal)locked.get("bonus_balance");String no="RC"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))+UUID.randomUUID().toString().replace("-","").substring(0,6).toUpperCase();var order=new RechargeOrderEntity();order.rechargeNo=no;order.requestNo=requestNo;order.userId=uid;order.planId=plan.id;order.rechargeAmount=plan.rechargeAmount;order.bonusAmount=plan.bonusAmount;order.rechargeStatus="PAID";order.paidAt=LocalDateTime.now();recharges.insert(order);data.creditRecharge(accountId,plan.rechargeAmount,plan.bonusAmount);addTransaction(accountId,uid,"CASH",no,plan.rechargeAmount,beforeCash,beforeCash.add(plan.rechargeAmount),"模拟充值");if(plan.bonusAmount.signum()>0)addTransaction(accountId,uid,"BONUS",no,plan.bonusAmount,beforeBonus,beforeBonus.add(plan.bonusAmount),"充值赠送");upgradeMember(uid,plan.rechargeAmount);return rechargeView(order,false);}
 public Map<String,Object> adminPlans(int current,int size){current=Math.max(1,current);size=Math.min(100,Math.max(1,size));var result=plans.selectPage(new Page<>(current,size),new QueryWrapper<RechargePlanEntity>().orderByAsc("sort_no","id"));return Map.of("records",result.getRecords().stream().map(this::planView).toList(),"current",current,"size",size,"total",result.getTotal());}
 public long savePlan(Long id,PlanCommand c){if(c.planCode()==null||c.planCode().isBlank()||c.planName()==null||c.planName().isBlank())throw new IllegalArgumentException("套餐编码和名称不能为空");if(c.rechargeAmount()==null||c.rechargeAmount().signum()<=0||c.bonusAmount()==null||c.bonusAmount().signum()<0)throw new IllegalArgumentException("充值金额必须大于0，赠送金额不能小于0");try{var p=id==null?new RechargePlanEntity():requiredPlan(id);p.planCode=c.planCode();p.planName=c.planName();p.rechargeAmount=c.rechargeAmount();p.bonusAmount=c.bonusAmount();p.memberDays=c.memberDays();p.sortNo=c.sortNo();p.enabled=c.enabled();p.updatedAt=LocalDateTime.now();if(id==null)plans.insert(p);else plans.updateById(p);return p.id;}catch(DuplicateKeyException e){throw new IllegalArgumentException("充值套餐编码已存在");}}
 public void status(long id,boolean enabled){var p=requiredPlan(id);p.enabled=enabled;p.updatedAt=LocalDateTime.now();plans.updateById(p);}
 private WalletAccountEntity ensureWallet(long uid){var w=wallets.selectOne(new QueryWrapper<WalletAccountEntity>().eq("owner_type","USER").eq("owner_id",uid));if(w!=null)return w;try{w=new WalletAccountEntity();w.ownerType="USER";w.ownerId=uid;w.cashBalance=BigDecimal.ZERO;w.bonusBalance=BigDecimal.ZERO;w.frozenBalance=BigDecimal.ZERO;w.version=0L;wallets.insert(w);return w;}catch(DuplicateKeyException e){return wallets.selectOne(new QueryWrapper<WalletAccountEntity>().eq("owner_type","USER").eq("owner_id",uid));}}
 private void upgradeMember(long uid,BigDecimal amount){var m=members.selectOne(new QueryWrapper<UserMemberEntity>().eq("user_id",uid));BigDecimal total=(m==null?BigDecimal.ZERO:m.totalRechargeAmount).add(amount);var level=data.matchedLevel(total);if(level==null)return;if(m==null){m=new UserMemberEntity();m.userId=uid;m.startedAt=LocalDateTime.now();m.growthValue=0L;m.enabled=true;}m.levelId=((Number)level.get("id")).longValue();m.totalRechargeAmount=total;m.growthValue=total.longValue();m.updatedAt=LocalDateTime.now();if(m.id==null)members.insert(m);else members.updateById(m);}
 private void addTransaction(long account,long uid,String balance,String businessNo,BigDecimal amount,BigDecimal before,BigDecimal after,String remark){var t=new WalletTransactionEntity();t.transactionNo="WT"+UUID.randomUUID().toString().replace("-","").toUpperCase();t.accountId=account;t.ownerType="USER";t.ownerId=uid;t.balanceType=balance;t.direction="IN";t.businessType="RECHARGE";t.businessNo=businessNo;t.amount=amount;t.balanceBefore=before;t.balanceAfter=after;t.remark=remark;transactions.insert(t);}
 private RechargeOrderEntity findRecharge(long uid,String requestNo){return recharges.selectOne(new QueryWrapper<RechargeOrderEntity>().eq("user_id",uid).eq("request_no",requestNo));}private Map<String,Object> rechargeView(RechargeOrderEntity o,boolean duplicated){return Map.of("rechargeNo",o.rechargeNo,"requestNo",o.requestNo,"cashAmount",o.rechargeAmount,"bonusAmount",o.bonusAmount,"duplicated",duplicated);}private RechargePlanEntity requiredPlan(long id){var p=plans.selectById(id);if(p==null)throw new IllegalArgumentException("充值套餐不存在");return p;}private Map<String,Object> walletView(WalletAccountEntity w){return Map.of("id",w.id,"cashBalance",w.cashBalance,"bonusBalance",w.bonusBalance,"frozenBalance",w.frozenBalance,"totalBalance",w.cashBalance.add(w.bonusBalance));}private Map<String,Object> planView(RechargePlanEntity p){var x=new LinkedHashMap<String,Object>();x.put("id",p.id);x.put("planCode",p.planCode);x.put("planName",p.planName);x.put("rechargeAmount",p.rechargeAmount);x.put("bonusAmount",p.bonusAmount);x.put("memberDays",p.memberDays);x.put("sortNo",p.sortNo);x.put("enabled",p.enabled);return x;}public record PlanCommand(String planCode,String planName,BigDecimal rechargeAmount,BigDecimal bonusAmount,Integer memberDays,int sortNo,boolean enabled){}
}
