package com.peiwan.platform.wallet;import com.peiwan.platform.common.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.Map;
@RestController public class WalletController{private final WalletService service;private final AuditService audit;public WalletController(WalletService service,AuditService audit){this.service=service;this.audit=audit;}
 @PreAuthorize("hasAuthority('customer:wallet:view')") @GetMapping("/api/customer/wallet") public ApiResponse<?> wallet(Authentication a){return ApiResponse.ok(service.summary(uid(a)));}
 @PreAuthorize("hasAuthority('customer:wallet:view')") @GetMapping("/api/customer/recharge-plans") public ApiResponse<?> plans(){return ApiResponse.ok(service.enabledPlans());}
 @PreAuthorize("hasAuthority('customer:wallet:transaction:list')") @GetMapping("/api/customer/wallet/transactions") public ApiResponse<?> transactions(Authentication a,@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String businessType){return ApiResponse.ok(service.transactionPage(uid(a),current,size,businessType));}
 @PreAuthorize("hasAuthority('customer:wallet:recharge')") @PostMapping("/api/customer/wallet/recharge") public ApiResponse<?> recharge(Authentication a,@RequestBody Recharge b,HttpServletRequest r){var result=service.simulateRecharge(uid(a),b.planId(),b.requestNo());audit.operation(a,"customer:wallet:recharge","WALLET",uid(a),"plan="+b.planId()+",requestNo="+b.requestNo(),r);return ApiResponse.ok(result);}
 @PreAuthorize("hasAuthority('business:recharge-plan:list')") @GetMapping("/api/business/recharge-plan/list") public ApiResponse<?> adminPlans(@RequestParam(defaultValue="1")int current,@RequestParam(defaultValue="20")int size){return ApiResponse.ok(service.adminPlans(current,size));}
 @PreAuthorize("hasAuthority('business:recharge-plan:create')") @PostMapping("/api/business/recharge-plan") public ApiResponse<?> create(Authentication a,@RequestBody WalletService.PlanCommand b,HttpServletRequest r){long id=service.savePlan(null,b);audit.operation(a,"business:recharge-plan:create","RECHARGE_PLAN",id,b.planCode(),r);return ApiResponse.ok(Map.of("id",id));}
 @PreAuthorize("hasAuthority('business:recharge-plan:update')") @PutMapping("/api/business/recharge-plan/{id}") public ApiResponse<?> update(Authentication a,@PathVariable long id,@RequestBody WalletService.PlanCommand b,HttpServletRequest r){service.savePlan(id,b);audit.operation(a,"business:recharge-plan:update","RECHARGE_PLAN",id,b.planCode(),r);return ApiResponse.ok();}
 @PreAuthorize("hasAuthority('business:recharge-plan:status')") @PutMapping("/api/business/recharge-plan/{id}/status") public ApiResponse<?> status(Authentication a,@PathVariable long id,@RequestBody Status b,HttpServletRequest r){service.status(id,b.enabled());audit.operation(a,"business:recharge-plan:status","RECHARGE_PLAN",id,"enabled="+b.enabled(),r);return ApiResponse.ok();}
 private long uid(Authentication a){return(Long)a.getPrincipal();}public record Recharge(long planId,String requestNo){}public record Status(boolean enabled){}
}
